UniJSON::IValueNodeObjectExtensions
static IEnumerable<KeyValuePair<JsonNode, JsonNode> > UniJSON.IValueNodeObjectExtensions.ObjectItems(this JsonNode self)
Referenced by UniJSON.IValueNodeObjectExtensions.GetObjectItem, UniJSON.IValueNodeObjectExtensions.KeyOf, UniJSON.IValueNodeObjectExtensions.TryGet.
static int UniJSON.IValueNodeObjectExtensions.GetObjectCount(this JsonNode self)
static string UniJSON.IValueNodeObjectExtensions.GetObjectValueOrDefault(this JsonNode self, String key, string defualtValue)
static JsonNode UniJSON.IValueNodeObjectExtensions.GetObjectItem(this JsonNode self, String key)
static JsonNode UniJSON.IValueNodeObjectExtensions.GetObjectItem(this JsonNode self, Utf8String key)
References UniJSON.IValueNodeObjectExtensions.ObjectItems.
static bool UniJSON.IValueNodeObjectExtensions.ContainsKey(this JsonNode self, Utf8String key)
static bool UniJSON.IValueNodeObjectExtensions.ContainsKey(this JsonNode self, String key)
static bool UniJSON.IValueNodeObjectExtensions.TryGet(this JsonNode self, Utf8String key, out JsonNode found)
References UniJSON.IValueNodeObjectExtensions.ObjectItems.
static bool UniJSON.IValueNodeObjectExtensions.TryGet(this JsonNode self, String key, out JsonNode found)
static Utf8String UniJSON.IValueNodeObjectExtensions.KeyOf(this JsonNode self, JsonNode node)
References UniJSON.IValueNodeObjectExtensions.ObjectItems.