UniGLTF::MeshImporter
const float UniGLTF.MeshImporter.FrameWeight
Referenced by UniGLTF.MeshImporter.BuildBlendShapeAsync.
UniGLTF.MeshImporter.Mesh
Referenced by UniGLTF.MeshImporter.BuildMeshAsync.
static bool UniGLTF.MeshImporter.HasSharedVertexBuffer(glTFMesh gltfMesh)
Referenced by UniGLTF.MeshImporter.ReadMesh.
static bool UniGLTF.MeshImporter.BuildMesh(MeshContext meshContext)
Referenced by UniGLTF.MeshImporter.BuildMeshAsync.
static async Task UniGLTF.MeshImporter.BuildBlendShapeAsync(IAwaitCaller awaitCaller, Mesh mesh, BlendShape blendShape, Vector3[] emptyVertices)
References UniGLTF.MeshImporter.FrameWeight, UniGLTF.BlendShape.Positions.
Referenced by UniGLTF.MeshImporter.BuildMeshAsync.
MeshContext UniGLTF.MeshImporter.ReadMesh(GltfData data, int meshIndex, IAxisInverter inverter)
References UniGLTF.MeshImporter.HasSharedVertexBuffer.
static async Task<MeshWithMaterials> UniGLTF.MeshImporter.BuildMeshAsync(IAwaitCaller awaitCaller, Func< int, Material > ctx, MeshContext meshContext)
References UniGLTF.MeshContext.BlendShapes, UniGLTF.MeshImporter.BuildBlendShapeAsync, UniGLTF.MeshImporter.BuildMesh, UniGLTF.MeshImporter.Mesh.