UniGLTF::GltfMaterialDescriptorGenerator
MaterialDescriptor UniGLTF.GltfMaterialDescriptorGenerator.Get(GltfData data, int i)
References UniGLTF.GltfMaterialDescriptorGenerator.GetMaterialName, UniGLTF.GltfPbrMaterialImporter.ShaderName, UniGLTF.GltfUnlitMaterialImporter.TryCreateParam, UniGLTF.GltfPbrMaterialImporter.TryCreateParam.
static string UniGLTF.GltfMaterialDescriptorGenerator.GetMaterialName(int index, glTFMaterial src)
References UniGLTF.glTFMaterial.name.
Referenced by UniGLTF.GltfMaterialDescriptorGenerator.Get, VRM.VRMMaterialDescriptorGenerator.Get, VRM.VRMUrpMaterialDescriptorGenerator.Get, UniGLTF.GltfUnlitMaterialImporter.TryCreateParam, UniGLTF.GltfPbrUrpMaterialImporter.TryCreateParam, UniGLTF.GltfPbrMaterialImporter.TryCreateParam.