UniHumanoid::HumanBuilderTest::SkeletonBuilder
Dictionary<HumanBodyBones, Transform> UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_skeleton
Referenced by UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddLeg.
Dictionary<HumanBodyBones, Vector3> UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_boneTail
Referenced by UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
Transform UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_root
Referenced by UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddHips, UniHumanoid.HumanBuilderTest.SkeletonBuilder.SkeletonBuilder.
IDictionary<HumanBodyBones, Transform> UniHumanoid.HumanBuilderTest.SkeletonBuilder.Skeleton
UniHumanoid.HumanBuilderTest.SkeletonBuilder.SkeletonBuilder(Transform root)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_root.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddHips(float height, float len)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add, UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_root.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddSpine(float len)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddChest(float len)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddNeck(float len)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddHead(float len)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddArm(float shoulder, float upper, float lower, float hand)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddLeg(float distance, float upper, float lower, float foot, float toe)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add, UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_skeleton.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add(HumanBodyBones key, Transform parent, Vector3 headPosition, Vector3 tailPosition)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_boneTail, UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_skeleton.
Referenced by UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddArm, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddChest, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddHead, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddHips, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddLeg, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddNeck, UniHumanoid.HumanBuilderTest.SkeletonBuilder.AddSpine.
void UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add(HumanBodyBones key, HumanBodyBones parentKey, Vector3 tailPosition)
References UniHumanoid.HumanBuilderTest.SkeletonBuilder.Add, UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_boneTail, UniHumanoid.HumanBuilderTest.SkeletonBuilder.m_skeleton.