UniJSON::BytesStore
Byte [] UniJSON.BytesStore.m_buffer
Referenced by UniJSON.BytesStore.BytesStore, UniJSON.BytesStore.Require, UniJSON.BytesStore.Write, UniJSON.BytesStore.WriteBigEndian, UniJSON.BytesStore.WriteLittleEndian.
int UniJSON.BytesStore.m_pos
Referenced by UniJSON.BytesStore.Clear, UniJSON.BytesStore.Require, UniJSON.BytesStore.Write, UniJSON.BytesStore.WriteBigEndian, UniJSON.BytesStore.WriteLittleEndian.
char [] UniJSON.BytesStore.m_c
Referenced by UniJSON.BytesStore.Write.
ArraySegment<byte> UniJSON.BytesStore.Bytes
UniJSON.BytesStore.BytesStore()
UniJSON.BytesStore.BytesStore(int size)
UniJSON.BytesStore.BytesStore(Byte[] buffer)
References UniJSON.BytesStore.m_buffer.
void UniJSON.BytesStore.Clear()
References UniJSON.BytesStore.m_pos.
void UniJSON.BytesStore.Write(char c)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_c, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.Write(string src)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.Write(ArraySegment< byte > bytes)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.Write(sbyte value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.Write(byte value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(short value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(int value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(long value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(ushort value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(uint value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(ulong value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(float value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteLittleEndian(double value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(short value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(int value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(long value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(ushort value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(uint value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(ulong value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(float value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.WriteBigEndian(double value)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos, UniJSON.BytesStore.Require.
void UniJSON.BytesStore.Require(int size)
References UniJSON.BytesStore.m_buffer, UniJSON.BytesStore.m_pos.
Referenced by UniJSON.BytesStore.Write, UniJSON.BytesStore.WriteBigEndian, UniJSON.BytesStore.WriteLittleEndian.