VRM::MaterialValueBindingMerger
DictionaryKeyMaterialValueBindingComparer VRM.MaterialValueBindingMerger.comparer
Dictionary<string, Material> VRM.MaterialValueBindingMerger.m_materialMap
名前とmaterialのマッピング
Referenced by VRM.MaterialValueBindingMerger.Apply, VRM.MaterialValueBindingMerger.MaterialValueBindingMerger, VRM.MaterialValueBindingMerger.RestoreMaterialInitialValues.
Dictionary<MaterialValueBinding, float> VRM.MaterialValueBindingMerger.m_materialValueMap
MaterialValueの適用値を蓄積する
MaterialValueBinding float
Referenced by VRM.MaterialValueBindingMerger.AccumulateValue, VRM.MaterialValueBindingMerger.Apply.
Dictionary<MaterialValueBinding, Setter> VRM.MaterialValueBindingMerger.m_materialSetterMap
Referenced by VRM.MaterialValueBindingMerger.Apply, VRM.MaterialValueBindingMerger.ImmediatelySetValue, VRM.MaterialValueBindingMerger.MaterialValueBindingMerger.
HashSet<MaterialTarget> VRM.MaterialValueBindingMerger.m_used
Referenced by VRM.MaterialValueBindingMerger.Apply.
delegate void VRM.MaterialValueBindingMerger.Setter(float value, bool firstValue)
Referenced by VRM.MaterialValueBindingMerger.Apply, VRM.MaterialValueBindingMerger.ImmediatelySetValue, VRM.MaterialValueBindingMerger.MaterialValueBindingMerger.
VRM.MaterialValueBindingMerger.MaterialValueBindingMerger(Dictionary< BlendShapeKey, BlendShapeClip > clipMap, Transform root)
References VRM.MaterialValueBindingMerger.m_materialMap, VRM.MaterialValueBindingMerger.m_materialSetterMap, VRM.MaterialValueBindingMerger.Setter.
void VRM.MaterialValueBindingMerger.RestoreMaterialInitialValues(IEnumerable< BlendShapeClip > clips)
References VRM.MaterialValueBindingMerger.m_materialMap.
void VRM.MaterialValueBindingMerger.ImmediatelySetValue(BlendShapeClip clip, float value)
References VRM.MaterialValueBindingMerger.m_materialSetterMap, VRM.MaterialValueBindingMerger.Setter.
void VRM.MaterialValueBindingMerger.AccumulateValue(BlendShapeClip clip, float value)
References VRM.MaterialValueBindingMerger.m_materialValueMap.
void VRM.MaterialValueBindingMerger.Apply()
References VRM.MaterialValueBindingMerger.m_materialMap, VRM.MaterialValueBindingMerger.m_materialSetterMap, VRM.MaterialValueBindingMerger.m_materialValueMap, VRM.MaterialValueBindingMerger.m_used, VRM.MaterialValueBindingMerger.Setter.