PauseSelect
int PauseSelect.MenuNumber
Referenced by Update.
bool PauseSelect.pushScene
Referenced by PushLoadScene, RetryCoroutine, TitleCoroutine, Update.
RectTransform PauseSelect.rect
Referenced by Start.
bool PauseSelect.pushFlag
Referenced by Update.
bool PauseSelect.SEflag
AudioClip PauseSelect.audioClip2
AudioSource PauseSelect.audioSource2
Referenced by Start.
AudioClip PauseSelect.sound1
Referenced by Update.
AudioSource PauseSelect.audioSource1
Referenced by Start.
void PauseSelect.Start()
References audioSource1, audioSource2, rect.
void PauseSelect.Update()
References EndCoroutine, MenuNumber, pushFlag, pushScene, RetryCoroutine, sound1, TitleCoroutine.
IEnumerator PauseSelect.RetryCoroutine()
References pushScene.
Referenced by Update.
IEnumerator PauseSelect.TitleCoroutine()
References pushScene.
Referenced by Update.
IEnumerator PauseSelect.EndCoroutine()
Referenced by Update.
static bool PauseSelect.PushLoadScene()
References pushScene.