VRM::VRMImporterContext
VRMData VRM.VRMImporterContext._data
Referenced by VRM.VRMImporterContext.VRMImporterContext.
VRM.glTF_VRM_extensions VRM.VRMImporterContext.VRM
Referenced by VRM.VRMEditorImporterContext.ConvertAndExtractImages, VRM.VRMImporterContext.VRMImporterContext.
UniHumanoid.AvatarDescription VRM.VRMImporterContext.AvatarDescription
Referenced by VRM.VRMImporterContext.Dispose, VRM.VRMImporterContext.LoadHumanoid.
Avatar VRM.VRMImporterContext.HumanoidAvatar
Referenced by VRM.VRMImporterContext.Dispose, VRM.VRMImporterContext.LoadHumanoid.
BlendShapeAvatar VRM.VRMImporterContext.BlendShapeAvatar
Referenced by VRM.VRMImporterContext.Dispose, VRM.VRMImporterContext.LoadBlendShapeMaster.
VRMMetaObject VRM.VRMImporterContext.Meta
Referenced by VRM.VRMImporterContext.Dispose, VRM.VRMImporterContext.LoadMetaAsync.
VRM.VRMImporterContext.VRMImporterContext(VRMData data, IReadOnlyDictionary< SubAssetKey, Object > externalObjectMap=null, ITextureDeserializer textureDeserializer=null, IMaterialDescriptorGenerator materialGenerator=null)
References VRM.VRMImporterContext._data, UniGLTF.ImporterContext.Data, UniGLTF.ImporterContext.TextureDescriptorGenerator, VRM.VRMImporterContext.VRM.
async Task<VRMMetaObject> VRM.VRMImporterContext.ReadMetaAsync(IAwaitCaller awaitCaller=null, bool createThumbnail=false)
References UniGLTF.ImporterContext.Data.
Referenced by VRM.VRMImporterContext.LoadMetaAsync.
override void VRM.VRMImporterContext.TransferOwnership(TakeResponsibilityForDestroyObjectFunc take)
Root ヒエラルキーで使っているリソース
References VRM.BlendShapeAvatar.Clips.
override void VRM.VRMImporterContext.Dispose()
ImporterContextが所有する UnityEngine.Object を破棄する
References VRM.VRMImporterContext.AvatarDescription, VRM.VRMImporterContext.BlendShapeAvatar, VRM.BlendShapeAvatar.Clips, VRM.VRMImporterContext.HumanoidAvatar, VRM.VRMImporterContext.Meta.
override async Task VRM.VRMImporterContext.OnLoadHierarchy(IAwaitCaller awaitCaller, Func< string, IDisposable > MeasureTime)
References VRM.VRMImporterContext.LoadBlendShapeMaster, VRM.VRMImporterContext.LoadFirstPerson, VRM.VRMImporterContext.LoadHumanoid, VRM.VRMImporterContext.LoadMetaAsync, UniGLTF.ImporterContext.Nodes.
async Task VRM.VRMImporterContext.LoadMetaAsync()
References VRM.VRMImporterContext.Meta, VRM.VRMImporterContext.ReadMetaAsync.
Referenced by VRM.VRMImporterContext.OnLoadHierarchy.
void VRM.VRMImporterContext.LoadFirstPerson()
References UniGLTF.ImporterContext.Nodes.
Referenced by VRM.VRMImporterContext.OnLoadHierarchy.
void VRM.VRMImporterContext.LoadBlendShapeMaster()
References VRM.VRMImporterContext.BlendShapeAvatar, VRM.VRMImporterContext.LoadBlendShapeBind, UniGLTF.ImporterContext.Root.
Referenced by VRM.VRMImporterContext.OnLoadHierarchy.
BlendShapeClip VRM.VRMImporterContext.LoadBlendShapeBind(glTF_VRM_BlendShapeGroup group, Dictionary< Mesh, Transform > transformMeshTable)
References UniGLTF.ImporterContext.Meshes.
Referenced by VRM.VRMImporterContext.LoadBlendShapeMaster.
void VRM.VRMImporterContext.LoadHumanoid()
References VRM.VRMImporterContext.AvatarDescription, VRM.head, VRM.VRMImporterContext.HumanoidAvatar, UniGLTF.ImporterContext.Nodes.
Referenced by VRM.VRMImporterContext.OnLoadHierarchy.
static String VRM.VRMImporterContext.ToHumanBoneName(HumanBodyBones b)
References UniJSON.String.
static SkeletonBone VRM.VRMImporterContext.ToSkeletonBone(Transform t)