VRM::VRMFirstPerson
bool VRM.VRMFirstPerson.TriedSetupLayer
Referenced by VRM.VRMFirstPerson.SetupLayers.
int VRM.VRMFirstPerson.FIRSTPERSON_ONLY_LAYER
Referenced by VRM.VRMFirstPerson.CreateHeadlessModelForSkinnedMeshRenderer, VRM.VRMFirstPerson.SetupLayers, VRM.VRMFirstPerson.SetVisibility.
int VRM.VRMFirstPerson.THIRDPERSON_ONLY_LAYER
Referenced by VRM.VRMFirstPerson.SetupLayers, VRM.VRMFirstPerson.SetVisibility.
Transform VRM.VRMFirstPerson.FirstPersonBone
Referenced by VRM.VRMFirstPerson.CopyTo, VRM.VRMFirstPerson.SetDefault, VRM.VRMFirstPerson.Setup.
Vector3 VRM.VRMFirstPerson.FirstPersonOffset
Referenced by VRM.VRMFirstPerson.CopyTo, VRM.VRMFirstPerson.SetDefault.
List<RendererFirstPersonFlags> VRM.VRMFirstPerson.Renderers
Referenced by VRM.VRMFirstPersonEditor.OnInspectorGUI, VRM.VRMFirstPerson.Setup.
bool VRM.VRMFirstPerson.m_done
Referenced by VRM.VRMFirstPerson.Setup.
List<Mesh> VRM.VRMFirstPerson.m_headlessMeshes
Referenced by VRM.VRMFirstPerson.OnDestroy.
void VRM.VRMFirstPerson.CopyTo(GameObject _dst, Dictionary< Transform, Transform > map)
References VRM.VRMFirstPerson.FirstPersonBone, VRM.VRMFirstPerson.FirstPersonOffset.
void VRM.VRMFirstPerson.SetDefault()
References VRM.VRMFirstPerson.FirstPersonBone, VRM.VRMFirstPerson.FirstPersonOffset.
Referenced by VRM.VRMFirstPerson.Reset.
void VRM.VRMFirstPerson.Reset()
References VRM.VRMFirstPerson.SetDefault, VRM.VRMFirstPerson.TraverseRenderers.
void VRM.VRMFirstPerson.TraverseRenderers(VRMImporterContext context=null)
References VRM.VRMFirstPerson.GetFirstPersonFlag.
Referenced by VRM.VRMFirstPerson.Reset.
delegate void VRM.VRMFirstPerson.SetVisibilityFunc(Renderer renderer, bool firstPerson, bool thirdPerson)
Set target renderer visibility
https://github.com/vrm-c/UniVRM/issues/633#issuecomment-758454045 renderer Target renderer. Player avatar or other firstPerson visibility in HMD camera thirdPerson other camera visibility
delegate void VRM.VRMFirstPerson.SetVisiblityFunc(Renderer renderer, bool firstPerson, bool thirdPerson)
void VRM.VRMFirstPerson.Setup()
References VRM.VRMFirstPerson.SetVisibility.
void VRM.VRMFirstPerson.Setup(bool isSelf, SetVisibilityFunc setVisibility)
from v0.64.0
isSelf
References VRM.VRMFirstPerson.CreateHeadlessModel, VRM.VRMFirstPerson.FirstPersonBone, VRM.VRMFirstPerson.m_done, VRM.VRMFirstPerson.Renderers.
static FirstPersonFlag VRM.VRMFirstPerson.GetFirstPersonFlag(VRMImporterContext context, Renderer r)
Referenced by VRM.VRMFirstPerson.TraverseRenderers.
static void VRM.VRMFirstPerson.CreateHeadlessModelForMeshRenderer(MeshRenderer renderer, Transform eraseRoot, SetVisibilityFunc setVisibility)
Referenced by VRM.VRMFirstPerson.CreateHeadlessModel.
static Mesh VRM.VRMFirstPerson.CreateHeadlessModelForSkinnedMeshRenderer(SkinnedMeshRenderer renderer, Transform eraseRoot, SetVisibilityFunc setVisibility)
ヘッドレスモデルを作成する。
以下の場合は作成しない。 削除対象が無い場合全部削除対象の場合
References VRM.VRMFirstPerson.FIRSTPERSON_ONLY_LAYER.
Referenced by VRM.VRMFirstPerson.CreateHeadlessModel.
Mesh VRM.VRMFirstPerson.CreateHeadlessModel(Renderer _renderer, Transform EraseRoot, SetVisibilityFunc setVisibility)
ヘッドレスモデルを作成した場合に返す
References VRM.VRMFirstPerson.CreateHeadlessModelForMeshRenderer, VRM.VRMFirstPerson.CreateHeadlessModelForSkinnedMeshRenderer.
Referenced by VRM.VRMFirstPerson.Setup.
void VRM.VRMFirstPerson.OnDestroy()
References VRM.VRMFirstPerson.m_headlessMeshes.
static void VRM.VRMFirstPerson.SetupLayers()
References VRM.VRMFirstPerson.FIRSTPERSON_ONLY_LAYER, VRM.VRMFirstPerson.THIRDPERSON_ONLY_LAYER, VRM.VRMFirstPerson.TriedSetupLayer.
Referenced by VRM.VRMFirstPerson.SetVisibility.
static void VRM.VRMFirstPerson.SetVisibility(Renderer renderer, bool firstPerson, bool thirdPerson)
Default implementation. Threre are 4 cases.
renderer firstPerson thirdPerson
References VRM.VRMFirstPerson.FIRSTPERSON_ONLY_LAYER, VRM.VRMFirstPerson.SetupLayers, VRM.VRMFirstPerson.THIRDPERSON_ONLY_LAYER.
Referenced by VRM.VRMFirstPerson.Setup.
static void VRM.VRMFirstPerson.SetVisiblity(Renderer renderer, bool firstPerson, bool thirdPerson)