UniHumanoid::BvhSkeletonEstimator
static IBone UniHumanoid.BvhSkeletonEstimator.GetRoot(IList< IBone > bones)
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
static IBone UniHumanoid.BvhSkeletonEstimator.SelectBone(Func< IBone, IBone, IBone > selector, IList< IBone > bones)
Referenced by UniHumanoid.BvhSkeletonEstimator.GetNeckAndArms, UniHumanoid.BvhSkeletonEstimator.GetSpineAndHips.
static void UniHumanoid.BvhSkeletonEstimator.GetSpineAndHips(IBone hips, out IBone spine, out IBone leg_L, out IBone leg_R)
References UniHumanoid.IBone.Children, UniHumanoid.BvhSkeletonEstimator.SelectBone.
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
static void UniHumanoid.BvhSkeletonEstimator.GetNeckAndArms(IBone chest, out IBone neck, out IBone arm_L, out IBone arm_R)
References UniHumanoid.IBone.Children, UniHumanoid.BvhSkeletonEstimator.SelectBone.
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
Arm UniHumanoid.BvhSkeletonEstimator.GetArm(IBone shoulder)
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
Leg UniHumanoid.BvhSkeletonEstimator.GetLeg(IBone leg)
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
Skeleton UniHumanoid.BvhSkeletonEstimator.Detect(IList< IBone > bones)
References UniHumanoid.BvhSkeletonEstimator.GetArm, UniHumanoid.BvhSkeletonEstimator.GetLeg, UniHumanoid.BvhSkeletonEstimator.GetNeckAndArms, UniHumanoid.BvhSkeletonEstimator.GetRoot, UniHumanoid.BvhSkeletonEstimator.GetSpineAndHips.
Referenced by UniHumanoid.BvhSkeletonEstimator.Detect.
Skeleton UniHumanoid.BvhSkeletonEstimator.Detect(Bvh bvh)
References UniHumanoid.BvhSkeletonEstimator.Detect, UniHumanoid.BvhNode.Name, UniHumanoid.Bvh.Root, UnityEngine.Vector3.zero.
Skeleton UniHumanoid.BvhSkeletonEstimator.Detect(Transform t)
References UniHumanoid.BvhSkeletonEstimator.Detect, UnityEngine.Vector3.zero.