UniGLTF::GltfUnlitMaterialImporter
readonly int UniGLTF.GltfUnlitMaterialImporter.Cutoff
Referenced by UniGLTF.GltfUnlitMaterialImporter.TryCreateParam.
static bool UniGLTF.GltfUnlitMaterialImporter.TryCreateParam(GltfData data, int i, out MaterialDescriptor matDesc)
References UniGLTF.GltfUnlitMaterialImporter.Cutoff, UniGLTF.GltfMaterialDescriptorGenerator.GetMaterialName, UniGLTF.GltfData.GLTF, UniGLTF.glTF_KHR_materials_unlit.IsEnable, UniGLTF.glTF.materials.
Referenced by UniGLTF.GltfMaterialDescriptorGenerator.Get, UniGLTF.GltfUrpMaterialDescriptorGenerator.Get, VRM.VRMMaterialDescriptorGenerator.Get, VRM.VRMUrpMaterialDescriptorGenerator.Get.