UniHumanoid::AvatarDescription
float UniHumanoid.AvatarDescription.armStretch
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.legStretch
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.upperArmTwist
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.lowerArmTwist
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.upperLegTwist
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.lowerLegTwist
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
float UniHumanoid.AvatarDescription.feetSpacing
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
bool UniHumanoid.AvatarDescription.hasTranslationDoF
Referenced by UniHumanoid.AvatarDescription.ToHumanDescription.
BoneLimit [] UniHumanoid.AvatarDescription.human
Referenced by UniHumanoid.AvatarDescription.SetHumanBones, UniHumanoid.AvatarDescription.ToHumanDescription.
HumanDescription UniHumanoid.AvatarDescription.ToHumanDescription(Transform root)
References UniHumanoid.AvatarDescription.armStretch, UniHumanoid.AvatarDescription.feetSpacing, UniHumanoid.AvatarDescription.hasTranslationDoF, UniHumanoid.AvatarDescription.human, UniHumanoid.AvatarDescription.legStretch, UniHumanoid.AvatarDescription.lowerArmTwist, UniHumanoid.AvatarDescription.lowerLegTwist, UniHumanoid.AvatarDescription.upperArmTwist, UniHumanoid.AvatarDescription.upperLegTwist.
Referenced by UniHumanoid.AvatarDescription.CreateAvatar.
Avatar UniHumanoid.AvatarDescription.CreateAvatar(Transform root)
References UniHumanoid.AvatarDescription.ToHumanDescription.
Referenced by UniHumanoid.AvatarDescription.CreateAvatarAndSetup.
Avatar UniHumanoid.AvatarDescription.CreateAvatarAndSetup(Transform root)
References UniHumanoid.AvatarDescription.CreateAvatar.
void UniHumanoid.AvatarDescription.SetHumanBones(IEnumerable< KeyValuePair< HumanBodyBones, Transform >> skeleton)
References UniHumanoid.AvatarDescription.human.
static AvatarDescription UniHumanoid.AvatarDescription.CreateFrom(HumanDescription description)
References UniHumanoid.BoneLimit.From.
static AvatarDescription UniHumanoid.AvatarDescription.Create(AvatarDescription src=null)
Referenced by UniHumanoid.AvatarDescription.Create.
static AvatarDescription UniHumanoid.AvatarDescription.Create(Transform[] boneTransforms, Skeleton skeleton)
References UniHumanoid.Skeleton.Bones, UniHumanoid.AvatarDescription.Create.
static AvatarDescription UniHumanoid.AvatarDescription.Create(IEnumerable< KeyValuePair< HumanBodyBones, Transform >> skeleton)
References UniHumanoid.AvatarDescription.Create.