GenerateUniGLTFSerialization::FormatWriter
TextWriter GenerateUniGLTFSerialization.FormatWriter.m_w
Referenced by GenerateUniGLTFSerialization.FormatWriter.FormatWriter.
string GenerateUniGLTFSerialization.FormatWriter.m_prefix
Referenced by GenerateUniGLTFSerialization.FormatWriter.FormatWriter.
HashSet<string> GenerateUniGLTFSerialization.FormatWriter.m_used
Referenced by GenerateUniGLTFSerialization.FormatWriter.WriteEnumString, GenerateUniGLTFSerialization.FormatWriter.WriteObject.
const string GenerateUniGLTFSerialization.FormatWriter.FieldIndent
GenerateUniGLTFSerialization.FormatWriter.string
GenerateUniGLTFSerialization.FormatWriter.FormatWriter(TextWriter writer, string prefix)
References GenerateUniGLTFSerialization.FormatWriter.m_prefix, GenerateUniGLTFSerialization.FormatWriter.m_w.
Referenced by GenerateUniGLTFSerialization.FormatWriter.Write.
void GenerateUniGLTFSerialization.FormatWriter.WriteObject(ObjectJsonSchema schema, string rootName=default)
References GenerateUniGLTFSerialization.FormatWriter.m_used, GenerateUniGLTFSerialization.FormatWriter.PropType, UniGLTF.JsonSchema.Schemas.JsonSchemaBase.Title.
Referenced by GenerateUniGLTFSerialization.FormatWriter.Traverse.
void GenerateUniGLTFSerialization.FormatWriter.WriteEnumString(EnumStringJsonSchema schema)
References GenerateUniGLTFSerialization.FormatWriter.m_used, UniGLTF.JsonSchema.Schemas.JsonSchemaBase.Title.
Referenced by GenerateUniGLTFSerialization.FormatWriter.Traverse.
void GenerateUniGLTFSerialization.FormatWriter.Traverse(JsonSchemaSource source, string rootName=default)
References GenerateUniGLTFSerialization.FormatWriter.WriteEnumString, GenerateUniGLTFSerialization.FormatWriter.WriteObject.
static string GenerateUniGLTFSerialization.FormatWriter.PropType(JsonSchemaBase schema)
Referenced by GenerateUniGLTFSerialization.FormatWriter.WriteObject.
static void GenerateUniGLTFSerialization.FormatWriter.Write(TextWriter w, JsonSchemaSource root, string rootName)
References GenerateUniGLTFSerialization.FormatWriter.FormatWriter, UniGLTF.JsonSchema.JsonSchemaSource.title.