VRM::BlendShapeClipEditorHelper
VRM.BlendShapeClipEditorHelper.bool
float [] VRM.BlendShapeClipEditorHelper.v2
Referenced by VRM.BlendShapeClipEditorHelper.TilingOffset.
GUIContent [] VRM.BlendShapeClipEditorHelper.l2
Referenced by VRM.BlendShapeClipEditorHelper.TilingOffset.
static bool VRM.BlendShapeClipEditorHelper.DrawBlendShapeBinding(Rect position, SerializedProperty property, PreviewSceneManager scene)
BlendShape List のElement描画
References VRM.BlendShapeClipEditorHelper.FloatSlider, VRM.BlendShapeClipEditorHelper.IntPopup, VRM.BlendShapeClipEditorHelper.StringPopup.
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
static bool VRM.BlendShapeClipEditorHelper.DrawMaterialValueBinding(Rect position, SerializedProperty property, PreviewSceneManager scene)
Material List のElement描画
References VRM.BlendShapeClipEditorHelper.ColorProp, VRM.BlendShapeClipEditorHelper.OffsetProp, VRM.BlendShapeClipEditorHelper.StringPopup.
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
static int VRM.BlendShapeClipEditorHelper.StringPopup(Rect rect, SerializedProperty prop, string[] options, out int newIndex)
Referenced by VRM.BlendShapeClipEditorHelper.DrawBlendShapeBinding, VRM.BlendShapeClipEditorHelper.DrawMaterialValueBinding.
static bool VRM.BlendShapeClipEditorHelper.IntPopup(Rect rect, SerializedProperty prop, string[] options, out int newIndex)
Referenced by VRM.BlendShapeClipEditorHelper.DrawBlendShapeBinding.
static bool VRM.BlendShapeClipEditorHelper.FloatSlider(Rect rect, SerializedProperty prop, float maxValue)
Referenced by VRM.BlendShapeClipEditorHelper.DrawBlendShapeBinding.
static bool VRM.BlendShapeClipEditorHelper.ColorProp(Rect rect, SerializedProperty prop)
Referenced by VRM.BlendShapeClipEditorHelper.DrawMaterialValueBinding.
static Rect VRM.BlendShapeClipEditorHelper.AdvanceRect(ref float x, float y, float w, float h)
Referenced by VRM.BlendShapeClipEditorHelper.TilingOffset.
static Vector4 VRM.BlendShapeClipEditorHelper.TilingOffset(Rect rect, string label, Vector4 src)
References VRM.BlendShapeClipEditorHelper.AdvanceRect, VRM.BlendShapeClipEditorHelper.l2, VRM.BlendShapeClipEditorHelper.v2.
Referenced by VRM.BlendShapeClipEditorHelper.OffsetProp.
static bool VRM.BlendShapeClipEditorHelper.OffsetProp(Rect rect, SerializedProperty prop)
References VRM.BlendShapeClipEditorHelper.TilingOffset.
Referenced by VRM.BlendShapeClipEditorHelper.DrawMaterialValueBinding.