UniGLTF::MeshExportValidatorTests
static GameObject UniGLTF.MeshExportValidatorTests.CreateTestObject(Material[] materials)
Referenced by UniGLTF.MeshExportValidatorTests.NoMaterialTest, UniGLTF.MeshExportValidatorTests.NullMaterialsTest, UniGLTF.MeshExportValidatorTests.NullMaterialTest.
void UniGLTF.MeshExportValidatorTests.NoMaterialTest()
References UniGLTF.MeshExportValidatorTests.CreateTestObject.
void UniGLTF.MeshExportValidatorTests.NullMaterialTest()
References UniGLTF.MeshExportValidatorTests.CreateTestObject.
void UniGLTF.MeshExportValidatorTests.NullMaterialsTest()
References UniGLTF.MeshExportValidatorTests.CreateTestObject.
void UniGLTF.MeshExportValidatorTests.NoMeshTest()
void UniGLTF.MeshExportValidatorTests.NullMeshTest()