UniGLTF::ExportDialogBase
ExporterDialogState UniGLTF.ExportDialogBase.m_state
Referenced by UniGLTF.ExportDialogBase.OnEnable.
Vector2 UniGLTF.ExportDialogBase.m_ScrollPosition
Referenced by UniGLTF.ExportDialogBase.BeginGUI.
ExporterDialogState UniGLTF.ExportDialogBase.State
Referenced by UniGLTF.ExportDialogBase.BeginGUI, VRM.VRMExporterWizard.DoGUI, VRM.VRMExporterWizard.DrawWizardGUI, VRM.VRMExporterWizard.OnBlendShapeGUI, VRM.VRMExporterWizard.OnLayout, UniGLTF.GltfExportWindow.ValidatorFactory, VRM.VRMExporterWizard.ValidatorFactory.
BeginVerticalScrollViewFunc UniGLTF.ExportDialogBase.s_func
BeginVerticalScrollViewFunc UniGLTF.ExportDialogBase.BeginVerticalScrollView
Referenced by UniGLTF.ExportDialogBase.BeginGUI.
abstract string UniGLTF.ExportDialogBase.SaveTitle
Referenced by UniGLTF.ExportDialogBase.EndGUI.
abstract string UniGLTF.ExportDialogBase.SaveName
Referenced by UniGLTF.ExportDialogBase.EndGUI.
abstract string [] UniGLTF.ExportDialogBase.SaveExtensions
Referenced by UniGLTF.ExportDialogBase.EndGUI.
virtual void UniGLTF.ExportDialogBase.OnEnable()
References UniGLTF.ExportDialogBase.Initialize, UniGLTF.ExportDialogBase.m_state.
abstract void UniGLTF.ExportDialogBase.Initialize()
Referenced by UniGLTF.ExportDialogBase.OnEnable.
abstract void UniGLTF.ExportDialogBase.Clear()
Referenced by UniGLTF.ExportDialogBase.OnDisable.
abstract IEnumerable<Validator> UniGLTF.ExportDialogBase.ValidatorFactory()
Referenced by UniGLTF.ExportDialogBase.BeginGUI.
abstract bool UniGLTF.ExportDialogBase.DoGUI(bool isValid)
Referenced by UniGLTF.ExportDialogBase.OnGUI.
virtual void UniGLTF.ExportDialogBase.OnLayout()
Referenced by UniGLTF.ExportDialogBase.BeginGUI.
abstract void UniGLTF.ExportDialogBase.ExportPath(string path)
Referenced by UniGLTF.ExportDialogBase.EndGUI.
void UniGLTF.ExportDialogBase.OnDisable()
References UniGLTF.ExportDialogBase.Clear.
void UniGLTF.ExportDialogBase.OnGUI()
References UniGLTF.ExportDialogBase.BeginGUI, UniGLTF.ExportDialogBase.DoGUI, UniGLTF.ExportDialogBase.EndGUI.
bool UniGLTF.ExportDialogBase.BeginGUI()
References UniGLTF.ExportDialogBase.BeginVerticalScrollView, UniGLTF.ExporterDialogState.ExportRoot, UniGLTF.ExportDialogBase.m_ScrollPosition, UniGLTF.ExportDialogBase.OnLayout, UniGLTF.ExportDialogBase.State, UniGLTF.ExporterDialogState.Validations, UniGLTF.ExportDialogBase.ValidatorFactory.
Referenced by UniGLTF.ExportDialogBase.OnGUI.
void UniGLTF.ExportDialogBase.EndGUI()
References UniGLTF.ExportDialogBase.ExportPath, UniGLTF.ExportDialogBase.SaveExtensions, UniGLTF.ExportDialogBase.SaveName, UniGLTF.ExportDialogBase.SaveTitle.
Referenced by UniGLTF.ExportDialogBase.OnGUI.
delegate Vector2 UniGLTF.ExportDialogBase.BeginVerticalScrollViewFunc(Vector2 scrollPosition, bool alwaysShowVertical, GUIStyle verticalScrollbar, GUIStyle background, params GUILayoutOption[] options)