VRM::VrmDeserializer
static glTF_VRM_extensions VRM.VrmDeserializer.Deserialize(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster, VRM.VrmDeserializer.Deserialize_vrm_firstPerson, VRM.VrmDeserializer.Deserialize_vrm_humanoid, VRM.VrmDeserializer.Deserialize_vrm_materialProperties, VRM.VrmDeserializer.Deserialize_vrm_meta, VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation.
static glTF_VRM_Meta VRM.VrmDeserializer.Deserialize_vrm_meta(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize.
static glTF_VRM_Humanoid VRM.VrmDeserializer.Deserialize_vrm_humanoid(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones.
Referenced by VRM.VrmDeserializer.Deserialize.
static List<VRM.glTF_VRM_HumanoidBone> VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_humanoid.
static glTF_VRM_HumanoidBone VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__center, VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__max, VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__min.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__min(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones_LIST.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__max(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones_LIST.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones__center(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_humanoid_humanBones_LIST.
static glTF_VRM_Firstperson VRM.VrmDeserializer.Deserialize_vrm_firstPerson(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_firstPersonBoneOffset, VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalInner, VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalOuter, VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalDown, VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalUp, VRM.VrmDeserializer.Deserialize_vrm_firstPerson_meshAnnotations.
Referenced by VRM.VrmDeserializer.Deserialize.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_firstPerson_firstPersonBoneOffset(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static List<VRM.glTF_VRM_MeshAnnotation> VRM.VrmDeserializer.Deserialize_vrm_firstPerson_meshAnnotations(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_meshAnnotations_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static glTF_VRM_MeshAnnotation VRM.VrmDeserializer.Deserialize_vrm_firstPerson_meshAnnotations_LIST(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson_meshAnnotations.
static glTF_VRM_DegreeMap VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalInner(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalInner_curve.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalInner_curve(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalInner.
static glTF_VRM_DegreeMap VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalOuter(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalOuter_curve.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalOuter_curve(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtHorizontalOuter.
static glTF_VRM_DegreeMap VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalDown(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalDown_curve.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalDown_curve(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalDown.
static glTF_VRM_DegreeMap VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalUp(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalUp_curve.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalUp_curve(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_firstPerson_lookAtVerticalUp.
static glTF_VRM_BlendShapeMaster VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups.
Referenced by VRM.VrmDeserializer.Deserialize.
static List<VRM.glTF_VRM_BlendShapeGroup> VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster.
static glTF_VRM_BlendShapeGroup VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds, VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups.
static List<VRM.glTF_VRM_BlendShapeBind> VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups_LIST.
static glTF_VRM_BlendShapeBind VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds_LIST(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds.
static List<VRM.glTF_VRM_MaterialValueBind> VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups_LIST.
static glTF_VRM_MaterialValueBind VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_LIST.
static glTF_VRM_SecondaryAnimation VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups, VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups.
Referenced by VRM.VrmDeserializer.Deserialize.
static List<VRM.glTF_VRM_SecondaryAnimationGroup> VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation.
static glTF_VRM_SecondaryAnimationGroup VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__bones, VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__colliderGroups, VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__gravityDir.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__gravityDir(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups_LIST.
static Int32 [] VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__bones(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups_LIST.
static Int32 [] VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups__colliderGroups(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_boneGroups_LIST.
static List<VRM.glTF_VRM_SecondaryAnimationColliderGroup> VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation.
static glTF_VRM_SecondaryAnimationColliderGroup VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups.
static List<VRM.glTF_VRM_SecondaryAnimationCollider> VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders_LIST.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups_LIST.
static glTF_VRM_SecondaryAnimationCollider VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders__offset.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders.
static Vector3 VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders__offset(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_secondaryAnimation_colliderGroups__colliders_LIST.
static List<VRM.glTF_VRM_Material> VRM.VrmDeserializer.Deserialize_vrm_materialProperties(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.
Referenced by VRM.VrmDeserializer.Deserialize.
static glTF_VRM_Material VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_materialProperties__floatProperties, VRM.VrmDeserializer.Deserialize_vrm_materialProperties__keywordMap, VRM.VrmDeserializer.Deserialize_vrm_materialProperties__tagMap, VRM.VrmDeserializer.Deserialize_vrm_materialProperties__textureProperties, VRM.VrmDeserializer.Deserialize_vrm_materialProperties__vectorProperties.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties.
static Dictionary<String, Single> VRM.VrmDeserializer.Deserialize_vrm_materialProperties__floatProperties(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.
static Dictionary<String, Single[]> VRM.VrmDeserializer.Deserialize_vrm_materialProperties__vectorProperties(JsonNode parsed)
References VRM.VrmDeserializer.Deserialize_vrm_materialProperties__vectorProperties_DICT.
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.
static Single [] VRM.VrmDeserializer.Deserialize_vrm_materialProperties__vectorProperties_DICT(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties__vectorProperties.
static Dictionary<String, Int32> VRM.VrmDeserializer.Deserialize_vrm_materialProperties__textureProperties(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.
static Dictionary<String, Boolean> VRM.VrmDeserializer.Deserialize_vrm_materialProperties__keywordMap(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.
static Dictionary<String, String> VRM.VrmDeserializer.Deserialize_vrm_materialProperties__tagMap(JsonNode parsed)
Referenced by VRM.VrmDeserializer.Deserialize_vrm_materialProperties_LIST.