VRMShaders::TextureImporterConfigurator
static void VRMShaders.TextureImporterConfigurator.ConfigureSize(TextureImporter textureImporter)
References VRMShaders.EditorTextureUtility.TryGetOriginalTexturePixelSize.
Referenced by VRMShaders.TextureImporterConfigurator.Configure.
static void VRMShaders.TextureImporterConfigurator.ConfigureNormalMap(TextureImporter textureImporter)
Referenced by VRMShaders.TextureImporterConfigurator.Configure.
static void VRMShaders.TextureImporterConfigurator.ConfigureLinear(TextureImporter textureImporter)
Referenced by VRMShaders.TextureImporterConfigurator.Configure.
static void VRMShaders.TextureImporterConfigurator.ConfigureSampler(TextureDescriptor texDesc, TextureImporter textureImporter)
Referenced by VRMShaders.TextureImporterConfigurator.Configure.
static void VRMShaders.TextureImporterConfigurator.Configure(TextureDescriptor texDesc, TextureImporter importer)
References VRMShaders.TextureImporterConfigurator.ConfigureLinear, VRMShaders.TextureImporterConfigurator.ConfigureNormalMap, VRMShaders.TextureImporterConfigurator.ConfigureSampler, VRMShaders.TextureImporterConfigurator.ConfigureSize, VRMShaders.TextureDescriptor.TextureType.
Referenced by VRMShaders.TextureImporterConfigurator.Configure.
static void VRMShaders.TextureImporterConfigurator.Configure(TextureDescriptor texDesc, IReadOnlyDictionary< SubAssetKey, Texture > externalMap)
References VRMShaders.TextureImporterConfigurator.Configure, VRMShaders.TextureDescriptor.SubAssetKey, VRMShaders.EditorTextureUtility.TryGetAsEditorTexture2DAsset.