VRM::VRMSpringBone
SpringBoneUpdateType
string VRM.VRMSpringBone.m_comment
float VRM.VRMSpringBone.m_stiffnessForce
Referenced by VRM.VRMSpringBone.UpdateProcess.
float VRM.VRMSpringBone.m_gravityPower
Referenced by VRM.VRMSpringBone.UpdateProcess.
Vector3 VRM.VRMSpringBone.m_gravityDir
Referenced by VRM.VRMSpringBone.UpdateProcess.
float VRM.VRMSpringBone.m_dragForce
Referenced by VRM.VRMSpringBone.UpdateProcess.
Transform VRM.VRMSpringBone.m_center
Referenced by VRM.VRMSpringBone.OnDrawGizmos, VRM.VRMSpringBone.Setup, VRM.VRMSpringBone.UpdateProcess.
List<Transform> VRM.VRMSpringBone.RootBones
Referenced by VRM.VRMSpringBone.Setup, VRM.VRMSpringBone.UpdateProcess.
float VRM.VRMSpringBone.m_hitRadius
Referenced by VRM.VRMSpringBone.UpdateProcess.
VRMSpringBoneColliderGroup [] VRM.VRMSpringBone.ColliderGroups
Referenced by VRM.VRMSpringBone.UpdateProcess.
SpringBoneUpdateType VRM.VRMSpringBone.m_updateType
Referenced by VRM.VRMSpringBone.FixedUpdate, VRM.VRMSpringBone.LateUpdate.
bool VRM.VRMSpringBone.m_drawGizmo
Referenced by VRM.VRMSpringBone.OnDrawGizmos.
Color VRM.VRMSpringBone.m_gizmoColor
Referenced by VRM.VRMSpringBone.OnDrawGizmos.
Dictionary<Transform, Quaternion> VRM.VRMSpringBone.m_initialLocalRotationMap
Referenced by VRM.VRMSpringBone.Setup.
List<VRMSpringBoneLogic> VRM.VRMSpringBone.m_verlet
Referenced by VRM.VRMSpringBone.OnDrawGizmos, VRM.VRMSpringBone.SetLocalRotationsIdentity, VRM.VRMSpringBone.UpdateProcess.
List<SphereCollider> VRM.VRMSpringBone.m_colliders
Referenced by VRM.VRMSpringBone.UpdateProcess.
void VRM.VRMSpringBone.Awake()
References VRM.VRMSpringBone.Setup.
void VRM.VRMSpringBone.SetupRecursive(Transform center, Transform parent)
References VRM.VRMSpringBone.GetChildren, UnityEngine.Vector3.x, UnityEngine.Vector3.y, UnityEngine.Vector3.z.
Referenced by VRM.VRMSpringBone.Setup.
void VRM.VRMSpringBone.LateUpdate()
References VRM.VRMSpringBone.m_updateType, VRM.VRMSpringBone.UpdateProcess.
void VRM.VRMSpringBone.FixedUpdate()
References VRM.VRMSpringBone.m_updateType, VRM.VRMSpringBone.UpdateProcess.
void VRM.VRMSpringBone.UpdateProcess(float deltaTime)
References VRM.VRMSpringBone.ColliderGroups, VRM.VRMSpringBone.m_center, VRM.VRMSpringBone.m_colliders, VRM.VRMSpringBone.m_dragForce, VRM.VRMSpringBone.m_gravityDir, VRM.VRMSpringBone.m_gravityPower, VRM.VRMSpringBone.m_hitRadius, VRM.VRMSpringBone.m_stiffnessForce, VRM.VRMSpringBone.m_verlet, VRM.VRMSpringBone.RootBones, VRM.VRMSpringBone.Setup.
Referenced by VRM.VRMSpringBone.FixedUpdate, VRM.VRMSpringBone.LateUpdate.
void VRM.VRMSpringBone.OnDrawGizmos()
References VRM.VRMSpringBone.m_center, VRM.VRMSpringBone.m_drawGizmo, VRM.VRMSpringBone.m_gizmoColor, VRM.VRMSpringBone.m_verlet.
void VRM.VRMSpringBone.Setup(bool force=false)
References VRM.VRMSpringBone.m_center, VRM.VRMSpringBone.m_initialLocalRotationMap, VRM.VRMSpringBone.RootBones, VRM.VRMSpringBone.SetupRecursive.
Referenced by VRM.VRMSpringBone.Awake, VRM.VRMSpringBone.UpdateProcess.
void VRM.VRMSpringBone.SetLocalRotationsIdentity()
References VRM.VRMSpringBone.m_verlet.
static IEnumerable<Transform> VRM.VRMSpringBone.GetChildren(Transform parent)
Referenced by VRM.VRMSpringBone.SetupRecursive.