UniJSON::JsonParser
static ValueNodeType UniJSON.JsonParser.GetValueType(Utf8String segment)
Referenced by UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.ParsePrimitive(JsonNode tree, Utf8String segment, ValueNodeType valueType)
Expected null, boolean, integer, number
segment valueType parentIndex
Referenced by UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.ParseString(JsonNode tree, Utf8String segment)
Referenced by UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.ParseArray(JsonNode tree, Utf8String segment)
References UniJSON.JsonParser.Parse.
Referenced by UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.ParseObject(JsonNode tree, Utf8String segment)
References UniJSON.JsonParser.Parse.
Referenced by UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.Parse(JsonNode tree, Utf8String segment)
References UniJSON.JsonParser.GetValueType, UniJSON.JsonParser.ParseArray, UniJSON.JsonParser.ParseObject, UniJSON.JsonParser.ParsePrimitive, UniJSON.JsonParser.ParseString.
Referenced by UniJSON.JsonDiffTests.DiffTest, UniJSON.JsonParser.Parse, UniJSON.JsonParser.ParseArray, UniJSON.JsonParser.ParseObject, UniJSON.JsonParserTest.ParseTest.
static JsonNode UniJSON.JsonParser.Parse(String json)
References UniJSON.Utf8String.From, UniJSON.JsonParser.Parse.
static JsonNode UniJSON.JsonParser.Parse(Utf8String json)
References UniJSON.JsonParser.Parse.