UniGLTF::GltfDeserializer
static glTF UniGLTF.GltfDeserializer.Deserialize(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_accessors, UniGLTF.GltfDeserializer.Deserialize_gltf_animations, UniGLTF.GltfDeserializer.Deserialize_gltf_asset, UniGLTF.GltfDeserializer.Deserialize_gltf_buffers, UniGLTF.GltfDeserializer.Deserialize_gltf_bufferViews, UniGLTF.GltfDeserializer.Deserialize_gltf_cameras, UniGLTF.GltfDeserializer.Deserialize_gltf_extensionsRequired, UniGLTF.GltfDeserializer.Deserialize_gltf_extensionsUsed, UniGLTF.GltfDeserializer.Deserialize_gltf_images, UniGLTF.GltfDeserializer.Deserialize_gltf_materials, UniGLTF.GltfDeserializer.Deserialize_gltf_meshes, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes, UniGLTF.GltfDeserializer.Deserialize_gltf_samplers, UniGLTF.GltfDeserializer.Deserialize_gltf_scenes, UniGLTF.GltfDeserializer.Deserialize_gltf_skins, UniGLTF.GltfDeserializer.Deserialize_gltf_textures.
Referenced by UniGLTF.Extensions.VRMC_materials_hdr_emissiveMultiplier.GltfDeserializer.TryGet.
static glTFAssets UniGLTF.GltfDeserializer.Deserialize_gltf_asset(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static List<UniGLTF.glTFBuffer> UniGLTF.GltfDeserializer.Deserialize_gltf_buffers(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_buffers_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFBuffer UniGLTF.GltfDeserializer.Deserialize_gltf_buffers_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_buffers.
static List<UniGLTF.glTFBufferView> UniGLTF.GltfDeserializer.Deserialize_gltf_bufferViews(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_bufferViews_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFBufferView UniGLTF.GltfDeserializer.Deserialize_gltf_bufferViews_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_bufferViews.
static List<UniGLTF.glTFAccessor> UniGLTF.GltfDeserializer.Deserialize_gltf_accessors(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_accessors_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFAccessor UniGLTF.GltfDeserializer.Deserialize_gltf_accessors_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__max, UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__min, UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__max(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__min(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors_ITEM.
static glTFSparse UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse_indices, UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse_values.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors_ITEM.
static glTFSparseIndices UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse_indices(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse.
static glTFSparseValues UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse_values(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_accessors__sparse.
static List<UniGLTF.glTFTexture> UniGLTF.GltfDeserializer.Deserialize_gltf_textures(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_textures_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFTexture UniGLTF.GltfDeserializer.Deserialize_gltf_textures_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_textures.
static List<UniGLTF.glTFTextureSampler> UniGLTF.GltfDeserializer.Deserialize_gltf_samplers(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_samplers_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFTextureSampler UniGLTF.GltfDeserializer.Deserialize_gltf_samplers_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_samplers.
static List<UniGLTF.glTFImage> UniGLTF.GltfDeserializer.Deserialize_gltf_images(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_images_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFImage UniGLTF.GltfDeserializer.Deserialize_gltf_images_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_images.
static List<UniGLTF.glTFMaterial> UniGLTF.GltfDeserializer.Deserialize_gltf_materials(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFMaterial UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_materials__emissiveFactor, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__emissiveTexture, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__normalTexture, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__occlusionTexture, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials.
static glTFPbrMetallicRoughness UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_baseColorFactor, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_baseColorTexture, UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
static glTFMaterialBaseColorTextureInfo UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_baseColorTexture(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_baseColorFactor(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness.
static glTFMaterialMetallicRoughnessTextureInfo UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials__pbrMetallicRoughness.
static glTFMaterialNormalTextureInfo UniGLTF.GltfDeserializer.Deserialize_gltf_materials__normalTexture(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
static glTFMaterialOcclusionTextureInfo UniGLTF.GltfDeserializer.Deserialize_gltf_materials__occlusionTexture(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
static glTFMaterialEmissiveTextureInfo UniGLTF.GltfDeserializer.Deserialize_gltf_materials__emissiveTexture(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_materials__emissiveFactor(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_materials_ITEM.
static List<UniGLTF.glTFMesh> UniGLTF.GltfDeserializer.Deserialize_gltf_meshes(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_meshes_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFMesh UniGLTF.GltfDeserializer.Deserialize_gltf_meshes_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives, UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__weights.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes.
static List<UniGLTF.glTFPrimitives> UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes_ITEM.
static glTFPrimitives UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__attributes, UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__targets.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives.
static glTFAttributes UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__attributes(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives_ITEM.
static List<UniGLTF.gltfMorphTarget> UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__targets(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__targets_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives_ITEM.
static gltfMorphTarget UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__targets_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__primitives__targets.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_meshes__weights(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_meshes_ITEM.
static List<UniGLTF.glTFNode> UniGLTF.GltfDeserializer.Deserialize_gltf_nodes(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFNode UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__children, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__matrix, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__rotation, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__scale, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__translation, UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__weights.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes.
static Int32 [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__children(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__matrix(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__translation(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__rotation(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__scale(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static Single [] UniGLTF.GltfDeserializer.Deserialize_gltf_nodes__weights(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_nodes_ITEM.
static List<UniGLTF.glTFSkin> UniGLTF.GltfDeserializer.Deserialize_gltf_skins(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_skins_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFSkin UniGLTF.GltfDeserializer.Deserialize_gltf_skins_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_skins__joints.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_skins.
static Int32 [] UniGLTF.GltfDeserializer.Deserialize_gltf_skins__joints(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_skins_ITEM.
static List<UniGLTF.gltfScene> UniGLTF.GltfDeserializer.Deserialize_gltf_scenes(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_scenes_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static gltfScene UniGLTF.GltfDeserializer.Deserialize_gltf_scenes_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_scenes__nodes.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_scenes.
static Int32 [] UniGLTF.GltfDeserializer.Deserialize_gltf_scenes__nodes(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_scenes_ITEM.
static List<UniGLTF.glTFAnimation> UniGLTF.GltfDeserializer.Deserialize_gltf_animations(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_animations_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFAnimation UniGLTF.GltfDeserializer.Deserialize_gltf_animations_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels, UniGLTF.GltfDeserializer.Deserialize_gltf_animations__samplers.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations.
static List<UniGLTF.glTFAnimationChannel> UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations_ITEM.
static glTFAnimationChannel UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels__target.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels.
static glTFAnimationTarget UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels__target(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations__channels_ITEM.
static List<UniGLTF.glTFAnimationSampler> UniGLTF.GltfDeserializer.Deserialize_gltf_animations__samplers(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_animations__samplers_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations_ITEM.
static glTFAnimationSampler UniGLTF.GltfDeserializer.Deserialize_gltf_animations__samplers_ITEM(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_animations__samplers.
static List<UniGLTF.glTFCamera> UniGLTF.GltfDeserializer.Deserialize_gltf_cameras(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_cameras_ITEM.
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static glTFCamera UniGLTF.GltfDeserializer.Deserialize_gltf_cameras_ITEM(JsonNode parsed)
References UniGLTF.GltfDeserializer.Deserialize_gltf_cameras__orthographic, UniGLTF.GltfDeserializer.Deserialize_gltf_cameras__perspective.
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_cameras.
static glTFOrthographic UniGLTF.GltfDeserializer.Deserialize_gltf_cameras__orthographic(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_cameras_ITEM.
static glTFPerspective UniGLTF.GltfDeserializer.Deserialize_gltf_cameras__perspective(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize_gltf_cameras_ITEM.
static List<System.String> UniGLTF.GltfDeserializer.Deserialize_gltf_extensionsUsed(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize.
static List<System.String> UniGLTF.GltfDeserializer.Deserialize_gltf_extensionsRequired(JsonNode parsed)
Referenced by UniGLTF.GltfDeserializer.Deserialize.