VRM::BlendShapeMerger
Dictionary<BlendShapeKey, BlendShapeClip> VRM.BlendShapeMerger.m_clipMap
Key からBlendShapeClipを得る
Referenced by VRM.BlendShapeMerger.AccumulateValue, VRM.BlendShapeMerger.BlendShapeMerger, VRM.BlendShapeMerger.ImmediatelySetValue.
Dictionary<BlendShapeKey, float> VRM.BlendShapeMerger.m_valueMap
BlendShape のWeightを記録する
Referenced by VRM.BlendShapeMerger.AccumulateValue, VRM.BlendShapeMerger.BlendShapeMerger, VRM.BlendShapeMerger.GetValue, VRM.BlendShapeMerger.ImmediatelySetValue.
BlendShapeBindingMerger VRM.BlendShapeMerger.m_blendShapeBindingMerger
Referenced by VRM.BlendShapeMerger.BlendShapeMerger.
MaterialValueBindingMerger VRM.BlendShapeMerger.m_materialValueBindingMerger
Referenced by VRM.BlendShapeMerger.BlendShapeMerger.
VRM.BlendShapeMerger.BlendShapeMerger(IEnumerable< BlendShapeClip > clips, Transform root)
References VRM.BlendShapeMerger.m_blendShapeBindingMerger, VRM.BlendShapeMerger.m_clipMap, VRM.BlendShapeMerger.m_materialValueBindingMerger, VRM.BlendShapeMerger.m_valueMap.
void VRM.BlendShapeMerger.Apply()
蓄積した値を適用する
Referenced by VRM.BlendShapeMerger.SetValues.
void VRM.BlendShapeMerger.SetValues(IEnumerable< KeyValuePair< BlendShapeKey, float >> values)
まとめて反映する。1フレームに1回呼び出されることを想定
values
References VRM.BlendShapeMerger.AccumulateValue, VRM.BlendShapeMerger.Apply.
void VRM.BlendShapeMerger.AccumulateValue(BlendShapeKey key, float value)
即時に反映しない。後にApplyによって反映する
key value
References VRM.BlendShapeMerger.m_clipMap, VRM.BlendShapeMerger.m_valueMap.
Referenced by VRM.BlendShapeMerger.SetValue, VRM.BlendShapeMerger.SetValues.
void VRM.BlendShapeMerger.ImmediatelySetValue(BlendShapeKey key, float value)
即時に反映する
key value
References VRM.BlendShapeMerger.m_clipMap, VRM.BlendShapeMerger.m_valueMap.
Referenced by VRM.BlendShapeMerger.SetValue.
void VRM.BlendShapeMerger.SetValue(BlendShapeKey key, float value, bool immediately)
References VRM.BlendShapeMerger.AccumulateValue, VRM.BlendShapeMerger.ImmediatelySetValue.
float VRM.BlendShapeMerger.GetValue(BlendShapeKey key)
References VRM.BlendShapeMerger.m_valueMap.
void VRM.BlendShapeMerger.RestoreMaterialInitialValues(IEnumerable< BlendShapeClip > clips)