UniGLTF::ShaderPropMenu
string UniGLTF.ShaderPropMenu.ExportDir
Referenced by UniGLTF.ShaderPropMenu.PreExport.
static void UniGLTF.ShaderPropMenu.PreExport()
static string UniGLTF.ShaderPropMenu.EscapeShaderName(string name)
Referenced by UniGLTF.ShaderPropMenu.PreExport, UniGLTF.ShaderPropMenu.ToString.
static void UniGLTF.ShaderPropMenu.PreExport(SupportedShader supportedShader)
References UniGLTF.ShaderPropMenu.EscapeShaderName, UniGLTF.ShaderPropMenu.ExportDir, UniGLTF.ShaderPropExporter.SupportedShader.ShaderName, UniGLTF.ShaderPropMenu.ToString.
static string UniGLTF.ShaderPropMenu.ToString(ShaderProps props, string shaderName)
References UniGLTF.ShaderPropMenu.EscapeShaderName.
Referenced by UniGLTF.ShaderPropMenu.PreExport.