UniGLTF::GltfPbrTextureImporter
static UniGLTF.GltfPbrTextureImporter::SubAssetKey
static IEnumerable<(SubAssetKey, TextureDescriptor)> UniGLTF.GltfPbrTextureImporter.EnumerateAllTextures(GltfData data, int i)
References UniGLTF.GltfPbrTextureImporter.BaseColorTexture, UniGLTF.GltfPbrTextureImporter.EmissiveTexture, UniGLTF.GltfPbrTextureImporter.NormalTexture, UniGLTF.GltfPbrTextureImporter.StandardTexture.
Referenced by VRM.VrmTextureDescriptorGenerator.EnumerateAllTextures, UniGLTF.GltfTextureDescriptorGenerator.EnumerateAllTextures.
static TextureDescriptor UniGLTF.GltfPbrTextureImporter.BaseColorTexture(GltfData data, glTFMaterial src)
Referenced by UniGLTF.GltfPbrTextureImporter.EnumerateAllTextures.
static TextureDescriptor UniGLTF.GltfPbrTextureImporter.StandardTexture(GltfData data, glTFMaterial src)
References UniGLTF.glTFMaterial.pbrMetallicRoughness.
Referenced by UniGLTF.GltfPbrTextureImporter.EnumerateAllTextures, UniGLTF.GltfPbrUrpMaterialImporter.TryCreateParam, UniGLTF.GltfPbrMaterialImporter.TryCreateParam.
static TextureDescriptor UniGLTF.GltfPbrTextureImporter.NormalTexture(GltfData data, glTFMaterial src)
Referenced by UniGLTF.GltfPbrTextureImporter.EnumerateAllTextures.
static TextureDescriptor UniGLTF.GltfPbrTextureImporter.EmissiveTexture(GltfData data, glTFMaterial src)
Referenced by UniGLTF.GltfPbrTextureImporter.EnumerateAllTextures.