UniGLTF::glTFAnimationTarget
Interpolations
AnimationPropertys
AnimationProperties
int UniGLTF.glTFAnimationTarget.node
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_animations__channels__target.
string UniGLTF.glTFAnimationTarget.path
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_animations__channels__target.
glTFExtension UniGLTF.glTFAnimationTarget.extensions
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_animations__channels__target.
glTFExtension UniGLTF.glTFAnimationTarget.extras
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_animations__channels__target.
const string UniGLTF.glTFAnimationTarget.PATH_TRANSLATION
Referenced by UniGLTF.glTFAnimationTarget.GetAnimationProperty, UniGLTF.glTFAnimationTarget.GetPathName.
const string UniGLTF.glTFAnimationTarget.PATH_EULER_ROTATION
const string UniGLTF.glTFAnimationTarget.PATH_ROTATION
Referenced by UniGLTF.glTFAnimationTarget.GetAnimationProperty, UniGLTF.glTFAnimationTarget.GetPathName.
const string UniGLTF.glTFAnimationTarget.PATH_SCALE
Referenced by UniGLTF.glTFAnimationTarget.GetAnimationProperty, UniGLTF.glTFAnimationTarget.GetPathName.
const string UniGLTF.glTFAnimationTarget.PATH_WEIGHT
Referenced by UniGLTF.glTFAnimationTarget.GetAnimationProperty, UniGLTF.glTFAnimationTarget.GetPathName.
const string UniGLTF.glTFAnimationTarget.NOT_IMPLEMENTED
static AnimationProperties UniGLTF.glTFAnimationTarget.AnimationPropertysToAnimationProperties(AnimationPropertys property)
Referenced by UniGLTF.glTFAnimation.AddChannelAndGetSampler, UniGLTF.glTFAnimationTarget.GetElementCount, UniGLTF.glTFAnimationTarget.GetPathName.
static string UniGLTF.glTFAnimationTarget.GetPathName(AnimationPropertys property)
References UniGLTF.glTFAnimationTarget.AnimationPropertysToAnimationProperties.
static string UniGLTF.glTFAnimationTarget.GetPathName(AnimationProperties property)
References UniGLTF.glTFAnimationTarget.PATH_ROTATION, UniGLTF.glTFAnimationTarget.PATH_SCALE, UniGLTF.glTFAnimationTarget.PATH_TRANSLATION, UniGLTF.glTFAnimationTarget.PATH_WEIGHT.
static AnimationProperties UniGLTF.glTFAnimationTarget.GetAnimationProperty(string path)
References UniGLTF.glTFAnimationTarget.PATH_ROTATION, UniGLTF.glTFAnimationTarget.PATH_SCALE, UniGLTF.glTFAnimationTarget.PATH_TRANSLATION, UniGLTF.glTFAnimationTarget.PATH_WEIGHT.
Referenced by UniGLTF.glTFAnimationTarget.GetElementCount.
static int UniGLTF.glTFAnimationTarget.GetElementCount(AnimationPropertys property)
References UniGLTF.glTFAnimationTarget.AnimationPropertysToAnimationProperties.
Referenced by UniGLTF.gltfExporter.Export, UniGLTF.glTFAnimationTarget.GetElementCount.
static int UniGLTF.glTFAnimationTarget.GetElementCount(AnimationProperties property)
static int UniGLTF.glTFAnimationTarget.GetElementCount(string path)
References UniGLTF.glTFAnimationTarget.GetAnimationProperty, UniGLTF.glTFAnimationTarget.GetElementCount.