MToon::Utils
const string MToon.Utils.ShaderName
Referenced by VRM.VRMUnlitTransparentZWriteMaterialImporter.TryCreateParam.
const string MToon.Utils.PropVersion
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropDebugMode
Referenced by MToon.MToonInspector.OnGUI, MToon.Utils.SetDebugMode, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropOutlineWidthMode
Referenced by MToon.MToonInspector.OnGUI, MToon.Utils.SetOutlineMode, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropOutlineColorMode
Referenced by MToon.MToonInspector.OnGUI, MToon.Utils.SetOutlineMode, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropBlendMode
Referenced by MToon.MToonInspector.OnGUI, MToon.Utils.SetRenderMode, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropCullMode
Referenced by MToon.Utils.GetCullMode, MToon.MToonInspector.OnGUI, MToon.Utils.SetCullMode, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropOutlineCullMode
Referenced by MToon.Utils.SetCullMode.
const string MToon.Utils.PropCutoff
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropColor
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropShadeColor
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropMainTex
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropShadeTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropBumpScale
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetNormalMapping, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropBumpMap
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetNormalMapping, MToon.Utils.ValidateProperties.
const string MToon.Utils.PropReceiveShadowRate
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropReceiveShadowTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropShadingGradeRate
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropShadingGradeTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropShadeShift
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropShadeToony
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropLightColorAttenuation
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropIndirectLightIntensity
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropRimColor
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropRimTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropRimLightingMix
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropRimFresnelPower
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropRimLift
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropSphereAdd
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropEmissionColor
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropEmissionMap
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropOutlineWidthTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropOutlineWidth
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropOutlineScaledMaxDistance
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropOutlineColor
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropOutlineLightingMix
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropUvAnimMaskTexture
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropUvAnimScrollX
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropUvAnimScrollY
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropUvAnimRotation
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.MToonInspector.OnGUI, MToon.Utils.SetMToonParametersToMaterial.
const string MToon.Utils.PropSrcBlend
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.PropDstBlend
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.PropZWrite
Referenced by MToon.Utils.GetBlendMode, MToon.Utils.SetRenderMode.
const string MToon.Utils.PropAlphaToMask
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.KeyNormalMap
Referenced by MToon.Utils.SetNormalMapping.
const string MToon.Utils.KeyAlphaTestOn
Referenced by MToon.Utils.GetBlendMode, MToon.Utils.SetRenderMode.
const string MToon.Utils.KeyAlphaBlendOn
Referenced by MToon.Utils.GetBlendMode, MToon.Utils.SetRenderMode.
const string MToon.Utils.KeyAlphaPremultiplyOn
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.KeyOutlineWidthWorld
Referenced by MToon.Utils.GetOutlineWidthMode, MToon.Utils.SetOutlineMode.
const string MToon.Utils.KeyOutlineWidthScreen
Referenced by MToon.Utils.GetOutlineWidthMode, MToon.Utils.SetOutlineMode.
const string MToon.Utils.KeyOutlineColorFixed
Referenced by MToon.Utils.GetOutlineColorMode, MToon.Utils.SetOutlineMode.
const string MToon.Utils.KeyOutlineColorMixed
Referenced by MToon.Utils.GetOutlineColorMode, MToon.Utils.SetOutlineMode.
const string MToon.Utils.KeyDebugNormal
Referenced by MToon.Utils.SetDebugMode.
const string MToon.Utils.KeyDebugLitShadeRate
Referenced by MToon.Utils.SetDebugMode.
const string MToon.Utils.TagRenderTypeKey
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.TagRenderTypeValueOpaque
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.TagRenderTypeValueTransparentCutout
Referenced by MToon.Utils.SetRenderMode.
const string MToon.Utils.TagRenderTypeValueTransparent
Referenced by MToon.Utils.SetRenderMode.
const int MToon.Utils.DisabledIntValue
Referenced by MToon.Utils.GetBlendMode, MToon.Utils.SetRenderMode.
const int MToon.Utils.EnabledIntValue
Referenced by MToon.Utils.GetBlendMode, MToon.Utils.SetRenderMode.
const string MToon.Utils.Implementation
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
const int MToon.Utils.VersionNumber
Referenced by MToon.MToonInspector.Draw, MToon.Utils.GetMToonParametersFromMaterial.
static RenderQueueRequirement MToon.Utils.GetRenderQueueRequirement(RenderMode renderMode)
Referenced by MToon.Utils.GetRenderQueueOffset, MToon.Utils.SetRenderMode, MToon.Utils.ValidateProperties.
static MToonDefinition MToon.Utils.GetMToonParametersFromMaterial(Material material)
References MToon.Utils.GetBlendMode, MToon.Utils.GetColor, MToon.Utils.GetCullMode, MToon.Utils.GetOutlineColorMode, MToon.Utils.GetOutlineWidthMode, MToon.Utils.GetRenderQueueOffset, MToon.Utils.GetRenderQueueOriginMode, MToon.Utils.GetTexture, MToon.Utils.GetValue, MToon.Utils.Implementation, MToon.Normal, MToon.Utils.PropBumpMap, MToon.Utils.PropBumpScale, MToon.Utils.PropColor, MToon.Utils.PropCutoff, MToon.Utils.PropEmissionColor, MToon.Utils.PropEmissionMap, MToon.Utils.PropIndirectLightIntensity, MToon.Utils.PropLightColorAttenuation, MToon.Utils.PropMainTex, MToon.Utils.PropOutlineColor, MToon.Utils.PropOutlineLightingMix, MToon.Utils.PropOutlineScaledMaxDistance, MToon.Utils.PropOutlineWidth, MToon.Utils.PropOutlineWidthTexture, MToon.Utils.PropReceiveShadowRate, MToon.Utils.PropReceiveShadowTexture, MToon.Utils.PropRimColor, MToon.Utils.PropRimFresnelPower, MToon.Utils.PropRimLift, MToon.Utils.PropRimLightingMix, MToon.Utils.PropRimTexture, MToon.Utils.PropShadeColor, MToon.Utils.PropShadeShift, MToon.Utils.PropShadeTexture, MToon.Utils.PropShadeToony, MToon.Utils.PropShadingGradeRate, MToon.Utils.PropShadingGradeTexture, MToon.Utils.PropSphereAdd, MToon.Utils.PropUvAnimMaskTexture, MToon.Utils.PropUvAnimRotation, MToon.Utils.PropUvAnimScrollX, MToon.Utils.PropUvAnimScrollY, MToon.Utils.PropVersion, MToon.Utils.VersionNumber.
static void MToon.Utils.SetMToonParametersToMaterial(Material material, MToonDefinition parameters)
References MToon.Utils.PropColor, MToon.Utils.PropCutoff, MToon.Utils.PropEmissionColor, MToon.Utils.PropEmissionMap, MToon.Utils.PropIndirectLightIntensity, MToon.Utils.PropLightColorAttenuation, MToon.Utils.PropMainTex, MToon.Utils.PropOutlineColor, MToon.Utils.PropOutlineLightingMix, MToon.Utils.PropOutlineScaledMaxDistance, MToon.Utils.PropOutlineWidth, MToon.Utils.PropOutlineWidthTexture, MToon.Utils.PropReceiveShadowRate, MToon.Utils.PropReceiveShadowTexture, MToon.Utils.PropRimColor, MToon.Utils.PropRimFresnelPower, MToon.Utils.PropRimLift, MToon.Utils.PropRimLightingMix, MToon.Utils.PropRimTexture, MToon.Utils.PropShadeColor, MToon.Utils.PropShadeShift, MToon.Utils.PropShadeTexture, MToon.Utils.PropShadeToony, MToon.Utils.PropShadingGradeRate, MToon.Utils.PropShadingGradeTexture, MToon.Utils.PropSphereAdd, MToon.Utils.PropUvAnimMaskTexture, MToon.Utils.PropUvAnimRotation, MToon.Utils.PropUvAnimScrollX, MToon.Utils.PropUvAnimScrollY, MToon.Utils.PropVersion, MToon.Utils.SetColor, MToon.Utils.SetCullMode, MToon.Utils.SetNormalMapping, MToon.Utils.SetOutlineMode, MToon.Utils.SetRenderMode, MToon.Utils.SetTexture, MToon.Utils.SetValue, MToon.Utils.ValidateProperties.
static void MToon.Utils.ValidateProperties(Material material, bool isBlendModeChangedByUser=false)
Validate properties and Set hidden properties, keywords. if isBlendModeChangedByUser is true, renderQueue will set specified render mode's default value.
material isBlendModeChangedByUser
References MToon.Utils.GetRenderQueueRequirement, MToon.Utils.PropBlendMode, MToon.Utils.PropBumpMap, MToon.Utils.PropBumpScale, MToon.Utils.PropCullMode, MToon.Utils.PropDebugMode, MToon.Utils.PropMainTex, MToon.Utils.PropOutlineColorMode, MToon.Utils.PropOutlineWidthMode, MToon.Utils.PropShadeTexture, MToon.Utils.SetCullMode, MToon.Utils.SetDebugMode, MToon.Utils.SetNormalMapping, MToon.Utils.SetOutlineMode, MToon.Utils.SetRenderMode.
Referenced by MToon.Utils.SetMToonParametersToMaterial.
static float MToon.Utils.GetValue(Material material, string propertyName)
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static Color MToon.Utils.GetColor(Material material, string propertyName)
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static Texture2D MToon.Utils.GetTexture(Material material, string propertyName)
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static RenderMode MToon.Utils.GetBlendMode(Material material)
References MToon.Utils.DisabledIntValue, MToon.Utils.EnabledIntValue, MToon.Utils.KeyAlphaBlendOn, MToon.Utils.KeyAlphaTestOn, MToon.Utils.PropZWrite.
Referenced by MToon.Utils.GetMToonParametersFromMaterial, MToon.Utils.GetRenderQueueOriginMode.
static CullMode MToon.Utils.GetCullMode(Material material)
References MToon.Utils.PropCullMode.
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static OutlineWidthMode MToon.Utils.GetOutlineWidthMode(Material material)
References MToon.Utils.KeyOutlineWidthScreen, MToon.Utils.KeyOutlineWidthWorld.
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static OutlineColorMode MToon.Utils.GetOutlineColorMode(Material material)
References MToon.Utils.KeyOutlineColorFixed, MToon.Utils.KeyOutlineColorMixed.
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static RenderMode MToon.Utils.GetRenderQueueOriginMode(Material material)
References MToon.Utils.GetBlendMode.
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static int MToon.Utils.GetRenderQueueOffset(Material material, RenderMode originMode)
References MToon.Utils.GetRenderQueueRequirement.
Referenced by MToon.Utils.GetMToonParametersFromMaterial.
static void MToon.Utils.SetDebugMode(Material material, DebugMode debugMode)
References MToon.Utils.KeyDebugLitShadeRate, MToon.Utils.KeyDebugNormal, MToon.Utils.PropDebugMode, MToon.Utils.SetKeyword, MToon.Utils.SetValue.
Referenced by MToon.Utils.ValidateProperties.
static void MToon.Utils.SetRenderMode(Material material, RenderMode renderMode, int renderQueueOffset, bool useDefaultRenderQueue)
References MToon.Utils.DisabledIntValue, MToon.Utils.EnabledIntValue, MToon.Utils.GetRenderQueueRequirement, MToon.Utils.KeyAlphaBlendOn, MToon.Utils.KeyAlphaPremultiplyOn, MToon.Utils.KeyAlphaTestOn, MToon.Utils.PropAlphaToMask, MToon.Utils.PropBlendMode, MToon.Utils.PropDstBlend, MToon.Utils.PropSrcBlend, MToon.Utils.PropZWrite, MToon.Utils.SetKeyword, MToon.Utils.SetValue, MToon.Utils.TagRenderTypeKey, MToon.Utils.TagRenderTypeValueOpaque, MToon.Utils.TagRenderTypeValueTransparent, MToon.Utils.TagRenderTypeValueTransparentCutout.
Referenced by MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
static void MToon.Utils.SetOutlineMode(Material material, OutlineWidthMode outlineWidthMode, OutlineColorMode outlineColorMode)
References MToon.Utils.KeyOutlineColorFixed, MToon.Utils.KeyOutlineColorMixed, MToon.Utils.KeyOutlineWidthScreen, MToon.Utils.KeyOutlineWidthWorld, MToon.Utils.PropOutlineColorMode, MToon.Utils.PropOutlineWidthMode, MToon.Utils.SetKeyword, MToon.Utils.SetValue.
Referenced by MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
static void MToon.Utils.SetNormalMapping(Material material, Texture bumpMap, float bumpScale)
References MToon.Utils.KeyNormalMap, MToon.Utils.PropBumpMap, MToon.Utils.PropBumpScale, MToon.Utils.SetKeyword, MToon.Utils.SetTexture, MToon.Utils.SetValue.
Referenced by MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
static void MToon.Utils.SetCullMode(Material material, CullMode cullMode)
References MToon.Utils.PropCullMode, MToon.Utils.PropOutlineCullMode, MToon.Utils.SetValue.
Referenced by MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.ValidateProperties.
static void MToon.Utils.SetValue(Material material, string propertyName, float val)
Referenced by MToon.Utils.SetCullMode, MToon.Utils.SetDebugMode, MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.SetNormalMapping, MToon.Utils.SetOutlineMode, MToon.Utils.SetRenderMode.
static void MToon.Utils.SetColor(Material material, string propertyName, Color color)
Referenced by MToon.Utils.SetMToonParametersToMaterial.
static void MToon.Utils.SetTexture(Material material, string propertyName, Texture texture)
Referenced by MToon.Utils.SetMToonParametersToMaterial, MToon.Utils.SetNormalMapping.
static void MToon.Utils.SetKeyword(Material mat, string keyword, bool required)
Referenced by MToon.Utils.SetDebugMode, MToon.Utils.SetNormalMapping, MToon.Utils.SetOutlineMode, MToon.Utils.SetRenderMode.