MToon::MToonInspector
const float MToon.MToonInspector.RoundsToDegree
Referenced by MToon.MToonInspector.GetInspectorRotationValue, MToon.MToonInspector.GetRawRotationValue.
const float MToon.MToonInspector.RoundsToRadian
Referenced by MToon.MToonInspector.GetInspectorRotationValue, MToon.MToonInspector.GetRawRotationValue.
MaterialProperty MToon.MToonInspector._version
Referenced by MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._blendMode
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._bumpMap
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._bumpScale
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._color
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._cullMode
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._cutoff
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._debugMode
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._emissionColor
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._emissionMap
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._lightColorAttenuation
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._indirectLightIntensity
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._mainTex
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineColor
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineColorMode
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineLightingMix
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineWidth
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineScaledMaxDistance
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineWidthMode
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._outlineWidthTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._receiveShadowRate
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._receiveShadowTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadingGradeRate
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadingGradeTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadeColor
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadeShift
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadeTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._shadeToony
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._sphereAdd
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._rimColor
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._rimTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._rimLightingMix
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._rimFresnelPower
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._rimLift
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._uvAnimMaskTexture
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._uvAnimScrollX
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._uvAnimScrollY
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
MaterialProperty MToon.MToonInspector._uvAnimRotation
Referenced by MToon.MToonInspector.Draw, MToon.MToonInspector.OnGUI.
bool MToon.MToonInspector.isAdvancedLightingPanelFoldout
Referenced by MToon.MToonInspector.Draw.
EditorRotationUnit MToon.MToonInspector.editorRotationUnit
Referenced by MToon.MToonInspector.Draw.
override void MToon.MToonInspector.OnGUI(MaterialEditor materialEditor, MaterialProperty[] properties)
References MToon.MToonInspector._blendMode, MToon.MToonInspector._bumpMap, MToon.MToonInspector._bumpScale, MToon.MToonInspector._color, MToon.MToonInspector._cullMode, MToon.MToonInspector._cutoff, MToon.MToonInspector._debugMode, MToon.MToonInspector._emissionColor, MToon.MToonInspector._emissionMap, MToon.MToonInspector._indirectLightIntensity, MToon.MToonInspector._lightColorAttenuation, MToon.MToonInspector._mainTex, MToon.MToonInspector._outlineColor, MToon.MToonInspector._outlineColorMode, MToon.MToonInspector._outlineLightingMix, MToon.MToonInspector._outlineScaledMaxDistance, MToon.MToonInspector._outlineWidth, MToon.MToonInspector._outlineWidthMode, MToon.MToonInspector._outlineWidthTexture, MToon.MToonInspector._receiveShadowRate, MToon.MToonInspector._receiveShadowTexture, MToon.MToonInspector._rimColor, MToon.MToonInspector._rimFresnelPower, MToon.MToonInspector._rimLift, MToon.MToonInspector._rimLightingMix, MToon.MToonInspector._rimTexture, MToon.MToonInspector._shadeColor, MToon.MToonInspector._shadeShift, MToon.MToonInspector._shadeTexture, MToon.MToonInspector._shadeToony, MToon.MToonInspector._shadingGradeRate, MToon.MToonInspector._shadingGradeTexture, MToon.MToonInspector._sphereAdd, MToon.MToonInspector._uvAnimMaskTexture, MToon.MToonInspector._uvAnimRotation, MToon.MToonInspector._uvAnimScrollX, MToon.MToonInspector._uvAnimScrollY, MToon.MToonInspector._version, MToon.MToonInspector.Draw, MToon.Utils.PropBlendMode, MToon.Utils.PropBumpMap, MToon.Utils.PropBumpScale, MToon.Utils.PropColor, MToon.Utils.PropCullMode, MToon.Utils.PropCutoff, MToon.Utils.PropDebugMode, MToon.Utils.PropEmissionColor, MToon.Utils.PropEmissionMap, MToon.Utils.PropIndirectLightIntensity, MToon.Utils.PropLightColorAttenuation, MToon.Utils.PropMainTex, MToon.Utils.PropOutlineColor, MToon.Utils.PropOutlineColorMode, MToon.Utils.PropOutlineLightingMix, MToon.Utils.PropOutlineScaledMaxDistance, MToon.Utils.PropOutlineWidth, MToon.Utils.PropOutlineWidthMode, MToon.Utils.PropOutlineWidthTexture, MToon.Utils.PropReceiveShadowRate, MToon.Utils.PropReceiveShadowTexture, MToon.Utils.PropRimColor, MToon.Utils.PropRimFresnelPower, MToon.Utils.PropRimLift, MToon.Utils.PropRimLightingMix, MToon.Utils.PropRimTexture, MToon.Utils.PropShadeColor, MToon.Utils.PropShadeShift, MToon.Utils.PropShadeTexture, MToon.Utils.PropShadeToony, MToon.Utils.PropShadingGradeRate, MToon.Utils.PropShadingGradeTexture, MToon.Utils.PropSphereAdd, MToon.Utils.PropUvAnimMaskTexture, MToon.Utils.PropUvAnimRotation, MToon.Utils.PropUvAnimScrollX, MToon.Utils.PropUvAnimScrollY, MToon.Utils.PropVersion.
override void MToon.MToonInspector.AssignNewShaderToMaterial(Material material, Shader oldShader, Shader newShader)
void MToon.MToonInspector.Draw(MaterialEditor materialEditor, Material[] materials)
References MToon.MToonInspector._blendMode, MToon.MToonInspector._bumpMap, MToon.MToonInspector._bumpScale, MToon.MToonInspector._color, MToon.MToonInspector._cullMode, MToon.MToonInspector._cutoff, MToon.MToonInspector._debugMode, MToon.MToonInspector._emissionColor, MToon.MToonInspector._emissionMap, MToon.MToonInspector._indirectLightIntensity, MToon.MToonInspector._lightColorAttenuation, MToon.MToonInspector._mainTex, MToon.MToonInspector._outlineColor, MToon.MToonInspector._outlineColorMode, MToon.MToonInspector._outlineLightingMix, MToon.MToonInspector._outlineScaledMaxDistance, MToon.MToonInspector._outlineWidth, MToon.MToonInspector._outlineWidthMode, MToon.MToonInspector._outlineWidthTexture, MToon.MToonInspector._receiveShadowRate, MToon.MToonInspector._receiveShadowTexture, MToon.MToonInspector._rimColor, MToon.MToonInspector._rimFresnelPower, MToon.MToonInspector._rimLift, MToon.MToonInspector._rimLightingMix, MToon.MToonInspector._rimTexture, MToon.MToonInspector._shadeColor, MToon.MToonInspector._shadeShift, MToon.MToonInspector._shadeTexture, MToon.MToonInspector._shadeToony, MToon.MToonInspector._shadingGradeRate, MToon.MToonInspector._shadingGradeTexture, MToon.MToonInspector._sphereAdd, MToon.MToonInspector._uvAnimMaskTexture, MToon.MToonInspector._uvAnimRotation, MToon.MToonInspector._uvAnimScrollX, MToon.MToonInspector._uvAnimScrollY, MToon.MToonInspector.editorRotationUnit, MToon.MToonInspector.GetInspectorRotationValue, MToon.MToonInspector.GetRawRotationValue, MToon.MToonInspector.isAdvancedLightingPanelFoldout, MToon.MToonInspector.ModeChanged, MToon.MToonInspector.TextureWithHdrColor, MToon.Utils.VersionNumber.
Referenced by MToon.MToonInspector.OnGUI.
static void MToon.MToonInspector.ModeChanged(Material[] materials, bool isBlendModeChangedByUser=false)
Referenced by MToon.MToonInspector.Draw.
static bool MToon.MToonInspector.PopupEnum< T >(string name, MaterialProperty property, MaterialEditor editor)
static void MToon.MToonInspector.TextureWithHdrColor(MaterialEditor materialEditor, string label, string description, MaterialProperty texProp, MaterialProperty colorProp)
Referenced by MToon.MToonInspector.Draw.
static float MToon.MToonInspector.GetRawRotationValue(EditorRotationUnit unit, float inspectorValue)
References MToon.MToonInspector.RoundsToDegree, MToon.MToonInspector.RoundsToRadian.
Referenced by MToon.MToonInspector.Draw.
static float MToon.MToonInspector.GetInspectorRotationValue(EditorRotationUnit unit, float rawValue)
References MToon.MToonInspector.RoundsToDegree, MToon.MToonInspector.RoundsToRadian.
Referenced by MToon.MToonInspector.Draw.