UniGLTF::MeshExportInfo
Mesh UniGLTF.MeshExportInfo.Mesh
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize, UniGLTF.MeshExportInfo.IsSameMeshAndMaterials, UniGLTF.MeshExportInfo.MeshExportInfo.
Material [] UniGLTF.MeshExportInfo.Materials
Referenced by UniGLTF.MeshExportInfo.IsSameMeshAndMaterials, UniGLTF.MeshExportInfo.MeshExportInfo.
IReadOnlyList<(Renderer, Transform[] UniqueBones)> UniGLTF.MeshExportInfo.Renderers
bool UniGLTF.MeshExportInfo.IsRendererActive
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
bool UniGLTF.MeshExportInfo.Skinned
Referenced by UniGLTF.MeshExportInfo.MeshExportInfo.
bool UniGLTF.MeshExportInfo.HasNormal
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
bool UniGLTF.MeshExportInfo.HasUV
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
bool UniGLTF.MeshExportInfo.HasVertexColor
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
bool UniGLTF.MeshExportInfo.HasSkinning
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
VertexColorState UniGLTF.MeshExportInfo.VertexColor
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize, UniGLTF.MeshExportInfo.MeshExportInfo.
int UniGLTF.MeshExportInfo.VertexCount
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.ExportVertexSize
Position, UV, Normal [Color] [SkinningWeight]
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.IndexCount
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.IndicesSize
int UniGLTF.MeshExportInfo.ExportBlendShapeVertexSize
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.TotalBlendShapeCount
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.ExportBlendShapeCount
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize.
int UniGLTF.MeshExportInfo.ExportByteSize
string UniGLTF.MeshExportInfo.Summary
Referenced by UniGLTF.MeshExportInfo.CalcMeshSize, UniGLTF.MeshExportInfo.MeshExportInfo.
bool UniGLTF.MeshExportInfo.CanExport
List<(Renderer, Transform[] UniqueBones)> UniGLTF.MeshExportInfo._renderers
ひとつの Mesh を複数の Renderer が共有することがありうる
Referenced by UniGLTF.MeshExportInfo.MeshExportInfo.
int [] UniGLTF.MeshExportInfo.JointIndexMap
Referenced by UniGLTF.MeshExportInfo.GetBindPoses, UniGLTF.MeshExportInfo.GetJointIndex, UniGLTF.MeshExportInfo.PushRenderer.
bool UniGLTF.MeshExportInfo.IsSameMeshAndMaterials(MeshExportInfo other)
References UniGLTF.MeshExportInfo.Materials, UniGLTF.MeshExportInfo.Mesh.
Referenced by UniGLTF.MeshExportInfo.IsSameMeshAndMaterials, UniGLTF.MeshExportInfo.TryGetSameMeshIndex.
bool UniGLTF.MeshExportInfo.IsSameMeshAndMaterials(Mesh mesh, Material[] materials)
References UniGLTF.MeshExportInfo.Materials, UniGLTF.MeshExportInfo.Mesh.
bool UniGLTF.MeshExportInfo.IsSameMeshAndMaterials(Renderer r)
References UniGLTF.MeshExportInfo.IsSameMeshAndMaterials.
int UniGLTF.MeshExportInfo.GetJointIndex(int index)
glTF は skinning の boneList の重複を許可しない (unity は ok)
index
References UniGLTF.MeshExportInfo.JointIndexMap.
IEnumerable<Matrix4x4> UniGLTF.MeshExportInfo.GetBindPoses()
References UniGLTF.MeshExportInfo.JointIndexMap.
UniGLTF.MeshExportInfo.MeshExportInfo(Renderer renderer, GltfExportSettings settings)
References UniGLTF.MeshExportInfo._renderers, UniGLTF.MeshExportInfo.Materials, UniGLTF.MeshExportInfo.Mesh, UniGLTF.MeshExportInfo.PushRenderer, UniGLTF.MeshExportInfo.Skinned, UniGLTF.MeshExportInfo.Summary, UniGLTF.MeshExportInfo.VertexColor.
void UniGLTF.MeshExportInfo.PushRenderer(Renderer renderer)
References UniGLTF.MeshExportInfo.JointIndexMap.
Referenced by UniGLTF.MeshExportInfo.MeshExportInfo.
void UniGLTF.MeshExportInfo.CalcMeshSize(GameObject root, Renderer renderer, GltfExportSettings settings, IBlendShapeExportFilter blendShapeFilter)
void UniGLTF.MeshExportInfo.CalcMeshSize(string relativePath, GltfExportSettings settings, IBlendShapeExportFilter blendShapeFilter)
References UniGLTF.MeshExportInfo.ExportBlendShapeCount, UniGLTF.MeshExportInfo.ExportBlendShapeVertexSize, UniGLTF.MeshExportInfo.ExportVertexSize, UniGLTF.MeshExportInfo.HasNormal, UniGLTF.MeshExportInfo.HasSkinning, UniGLTF.MeshExportInfo.HasUV, UniGLTF.MeshExportInfo.HasVertexColor, UniGLTF.MeshExportInfo.IndexCount, UniGLTF.MeshExportInfo.IsRendererActive, UniGLTF.MeshExportInfo.Mesh, UniGLTF.MeshExportInfo.Summary, UniGLTF.MeshExportInfo.TotalBlendShapeCount, UniGLTF.IBlendShapeExportFilter.UseBlendShape, UniGLTF.MeshExportInfo.VertexColor, UniGLTF.MeshExportInfo.VertexCount.
static bool UniGLTF.MeshExportInfo.TryGetSameMeshIndex(IReadOnlyList< MeshExportInfo > meshWithRenderers, Mesh mesh, Material[] materials, out int meshIndex)
References UniGLTF.MeshExportInfo.IsSameMeshAndMaterials.
Referenced by UniGLTF.gltfExporter.ExportNode.
static bool UniGLTF.MeshExportInfo.TryGetMeshInfo()