UniHumanoid::BoneTreeView
BoneNode UniHumanoid.BoneTreeView.Skeleton
HumanPoseHandler UniHumanoid.BoneTreeView.m_handler
Referenced by UniHumanoid.BoneTreeView.BoneTreeView.
HumanPose UniHumanoid.BoneTreeView.m_pose
Referenced by UniHumanoid.BoneTreeView.Begin, UniHumanoid.BoneTreeView.End.
bool UniHumanoid.BoneTreeView.m_updated
Referenced by UniHumanoid.BoneTreeView.CellGUI, UniHumanoid.BoneTreeView.End.
void UniHumanoid.BoneTreeView.Begin()
References UniHumanoid.BoneTreeView.m_pose.
void UniHumanoid.BoneTreeView.End()
References UniHumanoid.BoneTreeView.m_pose, UniHumanoid.BoneTreeView.m_updated.
UniHumanoid.BoneTreeView.BoneTreeView(TreeViewState treeViewState, MultiColumnHeader header, HumanPoseHandler handler)
References UniHumanoid.BoneTreeView.m_handler.
override TreeViewItem UniHumanoid.BoneTreeView.BuildRoot()
override IList<TreeViewItem> UniHumanoid.BoneTreeView.BuildRows(TreeViewItem root)
References UniHumanoid.BoneTreeView.AddChildrenRecursive, UniHumanoid.BoneTreeView.CreateTreeViewItemForBone.
override void UniHumanoid.BoneTreeView.RowGUI(RowGUIArgs args)
References UniHumanoid.BoneTreeView.CellGUI.
void UniHumanoid.BoneTreeView.AddChildrenRecursive(BoneNode bone, TreeViewItem item, IList< TreeViewItem > rows)
References UniHumanoid.BoneTreeView.CreateTreeViewItemForBone, UniHumanoid.BoneNode.Muscles.
Referenced by UniHumanoid.BoneTreeView.BuildRows.
void UniHumanoid.BoneTreeView.CellGUI(Rect cellRect, int index, ref RowGUIArgs args)
References UniHumanoid.BoneTreeView.m_updated.
Referenced by UniHumanoid.BoneTreeView.RowGUI.
static TreeViewItem UniHumanoid.BoneTreeView.CreateTreeViewItemForBone(HumanBodyBones bone)
Referenced by UniHumanoid.BoneTreeView.AddChildrenRecursive, UniHumanoid.BoneTreeView.BuildRows.
static MultiColumnHeaderState UniHumanoid.BoneTreeView.CreateDefaultMultiColumnHeaderState()