UniGLTF::TextureSamplerUtil
FilterMode UniGLTF.TextureSamplerUtil.FilterMode
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml
FilterMode filterMode
Referenced by UniGLTF.TextureSamplerUtil.ImportFilterMode.
static glFilter UniGLTF.TextureSamplerUtil.ExportMagFilter(Texture2D texture)
Referenced by UniGLTF.TextureSamplerUtil.Export.
static glFilter UniGLTF.TextureSamplerUtil.ExportMinFilter(Texture2D texture)
MIPMAP: disable, enable, blend
texture
Referenced by UniGLTF.TextureSamplerUtil.Export.
static glWrap UniGLTF.TextureSamplerUtil.ExportWrapMode(TextureWrapMode wrapMode)
Referenced by UniGLTF.TextureSamplerUtil.Export.
static TextureWrapMode UniGLTF.TextureSamplerUtil.ImportWrapMode(glWrap wrap)
Referenced by UniGLTF.TextureSamplerUtil.CreateSampler.
static glTFTextureSampler UniGLTF.TextureSamplerUtil.Export(Texture2D texture)
References UniGLTF.TextureSamplerUtil.ExportMagFilter, UniGLTF.TextureSamplerUtil.ExportMinFilter, UniGLTF.TextureSamplerUtil.ExportWrapMode.
static SamplerParam UniGLTF.TextureSamplerUtil.CreateSampler(glTF gltf, int index)
References UniGLTF.TextureSamplerUtil.ImportFilterMode, UniGLTF.TextureSamplerUtil.ImportWrapMode, UniGLTF.glTF.samplers.
static FilterMode bool EnableMipMap UniGLTF.TextureSamplerUtil.ImportFilterMode(glFilter filterMode)
References UniGLTF.TextureSamplerUtil.FilterMode.
Referenced by UniGLTF.TextureSamplerUtil.CreateSampler.