UniHumanoid::HumanPoseTransferEditor
SerializedProperty UniHumanoid.HumanPoseTransferEditor.m_avatarProp
Referenced by UniHumanoid.HumanPoseTransferEditor.OnEnable, UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI.
SerializedProperty UniHumanoid.HumanPoseTransferEditor.m_typeProp
Referenced by UniHumanoid.HumanPoseTransferEditor.OnEnable.
SerializedProperty UniHumanoid.HumanPoseTransferEditor.m_clipProp
Referenced by UniHumanoid.HumanPoseTransferEditor.OnEnable, UniHumanoid.HumanPoseTransferEditor.PoseClipInspector.
SerializedProperty UniHumanoid.HumanPoseTransferEditor.m_transferProp
Referenced by UniHumanoid.HumanPoseTransferEditor.OnEnable, UniHumanoid.HumanPoseTransferEditor.PoseHandler.
string [] UniHumanoid.HumanPoseTransferEditor.SOURCE_TYPES
Referenced by UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI.
void UniHumanoid.HumanPoseTransferEditor.OnEnable()
References UniHumanoid.HumanPoseTransferEditor.m_avatarProp, UniHumanoid.HumanPoseTransferEditor.m_clipProp, UniHumanoid.HumanPoseTransferEditor.m_transferProp, UniHumanoid.HumanPoseTransferEditor.m_typeProp.
void UniHumanoid.HumanPoseTransferEditor.PoseClipInspector()
References UniHumanoid.HumanPoseTransferEditor.m_clipProp.
Referenced by UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI.
void UniHumanoid.HumanPoseTransferEditor.PoseHandler()
References UniHumanoid.HumanPoseTransferEditor.m_transferProp.
Referenced by UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI.
override void UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI()
References UniHumanoid.HumanPoseTransferEditor.m_avatarProp, UniHumanoid.HumanPoseTransferEditor.PoseClipInspector, UniHumanoid.HumanPoseTransferEditor.PoseHandler, UniHumanoid.HumanPoseTransferEditor.SOURCE_TYPES, UniHumanoid.HumanPoseTransferEditor.ToAssetPath.
static string UniHumanoid.HumanPoseTransferEditor.ToAssetPath(string src)
Referenced by UniHumanoid.HumanPoseTransferEditor.OnInspectorGUI.