UniGLTF::RemapEditorBase
Dictionary<String, Type> UniGLTF.RemapEditorBase.s_typeMap
Dictionary<String, Type> UniGLTF.RemapEditorBase.TypeMap
Referenced by UniGLTF.RemapEditorBase.SubAssetPair.SubAssetPair.
SubAssetKey [] UniGLTF.RemapEditorBase.m_keys
Remap 対象は、このエディタのライフサイクル中に不変
ExternalObjectMap は都度変わりうるのに注意。
Referenced by UniGLTF.RemapEditorBase.CanExtract, UniGLTF.RemapEditorBase.RemapEditorBase.
EditorMapGetterFunc UniGLTF.RemapEditorBase.m_getter
Referenced by UniGLTF.RemapEditorBase.DrawRemapGUI< T >, UniGLTF.RemapEditorBase.RemapEditorBase.
EditorMapSetterFunc UniGLTF.RemapEditorBase.m_setter
Referenced by UniGLTF.RemapEditorBase.DrawRemapGUI< T >, UniGLTF.RemapEditorBase.RemapEditorBase.
bool UniGLTF.RemapEditorBase.HasKeys
Referenced by UniGLTF.RemapEditorAnimation.OnGUI.
UniGLTF.RemapEditorBase.RemapEditorBase(IEnumerable< SubAssetKey > keys, EditorMapGetterFunc getter, EditorMapSetterFunc setter)
References UniGLTF.RemapEditorBase.m_getter, UniGLTF.RemapEditorBase.m_keys, UniGLTF.RemapEditorBase.m_setter.
bool UniGLTF.RemapEditorBase.CanExtract(ScriptedImporter importer)
Extract 対象がすべて SubAsset に含まれるときに可能である
importer
References UniGLTF.RemapEditorBase.m_keys.
Referenced by UniGLTF.RemapEditorAnimation.OnGUI, UniGLTF.RemapEditorMaterial.OnGUI.
void UniGLTF.RemapEditorBase.DrawRemapGUI< T >(Dictionary< ScriptedImporter.SourceAssetIdentifier, UnityEngine.Object > externalObjectMap)
References UniGLTF.RemapEditorBase.m_getter, UniGLTF.RemapEditorBase.m_setter.
static string UniGLTF.RemapEditorBase.GetAndCreateFolder(string assetPath, string suffix)
Referenced by UniGLTF.RemapEditorAnimation.Extract.
static UnityEngine.Object UniGLTF.RemapEditorBase.ExtractSubAsset(UnityEngine.Object subAsset, string destinationPath, bool isForceUpdate)
subAsset を 指定された path に extract する
subAsset destinationPath isForceUpdate
Referenced by UniGLTF.RemapEditorAnimation.Extract, UniGLTF.RemapEditorMaterial.ExtractMaterials.
static void UniGLTF.RemapEditorBase.ClearExternalObjects(ScriptedImporter importer, params Type[] targetTypes)
Referenced by UniGLTF.RemapEditorAnimation.OnGUI, UniGLTF.RemapEditorMaterial.OnGUI.