UniHumanoid::BoneMappingEditor
BoneMapping UniHumanoid.BoneMappingEditor.m_target
Referenced by UniHumanoid.BoneMappingEditor.OnEnable, UniHumanoid.BoneMappingEditor.OnInspectorGUI.
const int UniHumanoid.BoneMappingEditor.LABEL_WIDTH
Referenced by UniHumanoid.BoneMappingEditor.BoneField, UniHumanoid.BoneMappingEditor.OnInspectorGUI.
bool UniHumanoid.BoneMappingEditor.m_handFoldout
Referenced by UniHumanoid.BoneMappingEditor.OnInspectorGUI.
bool UniHumanoid.BoneMappingEditor.m_settingsFoldout
Bone [] UniHumanoid.BoneMappingEditor.m_bones
Referenced by UniHumanoid.BoneMappingEditor.OnEnable, UniHumanoid.BoneMappingEditor.OnSceneGUI.
readonly HumanBodyBones [][] UniHumanoid.BoneMappingEditor.BoneDefs
IEnumerable<BoneDef> UniHumanoid.BoneMappingEditor.EachBoneDefs
void UniHumanoid.BoneMappingEditor.OnEnable()
References UniHumanoid.BoneMappingEditor.m_bones, UniHumanoid.BoneMappingEditor.m_target.
void UniHumanoid.BoneMappingEditor.DrawBone(HumanBodyBones bone, GameObject go)
Referenced by UniHumanoid.BoneMappingEditor.OnSceneGUI.
void UniHumanoid.BoneMappingEditor.OnSceneGUI()
References UniHumanoid.BoneMappingEditor.DrawBone, UniHumanoid.BoneMappingEditor.m_bones.
static GameObject UniHumanoid.BoneMappingEditor.ObjectField(GameObject obj)
Referenced by UniHumanoid.BoneMappingEditor.BoneField.
static GameObject UniHumanoid.BoneMappingEditor.ObjectField(string label, GameObject obj)
static void UniHumanoid.BoneMappingEditor.BoneField(HumanBodyBones bone, GameObject[] bones)
References UniHumanoid.BoneMappingEditor.LABEL_WIDTH, UniHumanoid.BoneMappingEditor.ObjectField.
Referenced by UniHumanoid.BoneMappingEditor.OnInspectorGUI.
static void UniHumanoid.BoneMappingEditor.BoneField(HumanBodyBones left, HumanBodyBones right, GameObject[] bones)
References UniHumanoid.BoneMappingEditor.LABEL_WIDTH, UniHumanoid.BoneMappingEditor.ObjectField.
override void UniHumanoid.BoneMappingEditor.OnInspectorGUI()
References UniHumanoid.BoneMappingEditor.BoneField, UniHumanoid.BoneMappingEditor.LABEL_WIDTH, UniHumanoid.BoneMappingEditor.m_handFoldout, UniHumanoid.BoneMappingEditor.m_target.