UniGLTF::gltfExporter
ExportingGltfData UniGLTF.gltfExporter._data
Referenced by UniGLTF.gltfExporter.Export, UniGLTF.gltfExporter.gltfExporter.
glTF UniGLTF.gltfExporter._gltf
Referenced by UniGLTF.gltfExporter.Export.
ITextureExporter UniGLTF.gltfExporter.TextureExporter
Referenced by UniGLTF.gltfExporter.Export, VRM.VRMExporter.ExportExtensions.
GameObject UniGLTF.gltfExporter.Copy
Referenced by UniGLTF.gltfExporter.Dispose, UniGLTF.gltfExporter.Prepare, VRM.glTF_VRMExtensions.Serialize.
List<Mesh> UniGLTF.gltfExporter.Meshes
Dictionary<Mesh, Dictionary<int, int> > UniGLTF.gltfExporter.MeshBlendShapeIndexMap
Mesh毎に、元のBlendShapeIndex => ExportされたBlendShapeIndex の対応を記録する
BlendShape が空の場合にスキップするので
Referenced by VRM.glTF_VRMExtensions.Create, UniGLTF.gltfExporter.Export.
List<Transform> UniGLTF.gltfExporter.Nodes
Referenced by UniGLTF.gltfExporter.Export, VRM.VRMExporter.ExportExtensions.
List<Material> UniGLTF.gltfExporter.Materials
Referenced by UniGLTF.gltfExporter.Export, VRM.VRMExporter.ExportExtensions.
virtual IEnumerable<string> UniGLTF.gltfExporter.ExtensionUsed
このエクスポーターがサポートするExtension
Referenced by UniGLTF.gltfExporter.gltfExporter.
TextureExporter UniGLTF.gltfExporter._textureExporter
Referenced by UniGLTF.gltfExporter.Export.
GltfExportSettings UniGLTF.gltfExporter.m_settings
Referenced by UniGLTF.gltfExporter.Export, UniGLTF.gltfExporter.gltfExporter.
IProgress<ExportProgress> UniGLTF.gltfExporter.m_progress
Referenced by UniGLTF.gltfExporter.ReportProgress.
GameObject UniGLTF.gltfExporter.m_tmpParent
Referenced by UniGLTF.gltfExporter.Dispose, UniGLTF.gltfExporter.Prepare.
virtual IMaterialExporter UniGLTF.gltfExporter.CreateMaterialExporter()
Referenced by UniGLTF.gltfExporter.Export.
void UniGLTF.gltfExporter.ReportProgress(string msg, float progress)
References UniGLTF.gltfExporter.m_progress.
Referenced by UniGLTF.gltfExporter.Export, UniGLTF.gltfExporter.Prepare.
UniGLTF.gltfExporter.gltfExporter(ExportingGltfData data, GltfExportSettings settings, IProgress< ExportProgress > progress=null)
References UniGLTF.gltfExporter._data, UniGLTF.gltfExporter.ExtensionUsed, UniGLTF.gltfExporter.m_settings, UniGLTF.UniGLTFVersion.VERSION.
virtual void UniGLTF.gltfExporter.Prepare(GameObject go)
References UniGLTF.gltfExporter.Copy, UniGLTF.gltfExporter.m_tmpParent, UniGLTF.gltfExporter.ReportProgress.
void UniGLTF.gltfExporter.Dispose()
References UniGLTF.gltfExporter.Copy, UniGLTF.gltfExporter.m_tmpParent.
virtual void UniGLTF.gltfExporter.ExportExtensions(ITextureSerializer textureSerializer)
Referenced by UniGLTF.gltfExporter.Export.
virtual void UniGLTF.gltfExporter.Export(ITextureSerializer textureSerializer)
References UniGLTF.gltfExporter._data, UniGLTF.gltfExporter._gltf, UniGLTF.gltfExporter._textureExporter, UniGLTF.gltfExporter.CreateMaterialExporter, UniGLTF.gltfExporter.ExportExtensions, UniGLTF.gltfExporter.ExportNode, UniGLTF.gltfExporter.FixName, UniGLTF.glTFAnimationTarget.GetElementCount, UniGLTF.GltfExportSettings.InverseAxis, UniGLTF.gltfExporter.m_settings, UniGLTF.gltfExporter.Materials, UniGLTF.gltfExporter.MeshBlendShapeIndexMap, UniGLTF.gltfExporter.Nodes, UniGLTF.gltfExporter.ReportProgress, UniGLTF.gltfExporter.TextureExporter.
static glTFNode UniGLTF.gltfExporter.ExportNode(Transform x, List< Transform > nodes, IReadOnlyList< MeshExportInfo > meshWithRenderers, List< SkinnedMeshRenderer > skins)
References UniGLTF.MeshExportInfo.TryGetSameMeshIndex.
Referenced by UniGLTF.gltfExporter.Export.
static void UniGLTF.gltfExporter.FixName(glTF gltf)
GlbLowPevelParser.FixNameUnique で付与した Suffix を remove
Referenced by UniGLTF.gltfExporter.Export.