UniGLTF::UriByteBuffer
string UniGLTF.UriByteBuffer.Uri
Referenced by UniGLTF.UriByteBuffer.UriByteBuffer.
Byte [] UniGLTF.UriByteBuffer.m_bytes
Referenced by UniGLTF.UriByteBuffer.UriByteBuffer.
const string UniGLTF.UriByteBuffer.DataPrefix
const string UniGLTF.UriByteBuffer.DataPrefix2
const string UniGLTF.UriByteBuffer.DataPrefix3
ArraySegment<byte> UniGLTF.UriByteBuffer.Bytes
UniGLTF.UriByteBuffer.UriByteBuffer(string baseDir, string uri)
References UniGLTF.UriByteBuffer.m_bytes, UniGLTF.UriByteBuffer.ReadFromUri, UniGLTF.UriByteBuffer.Uri.
glTFBufferView UniGLTF.UriByteBuffer.Extend< T >(ArraySegment< T > array, glBufferTarget target)
void UniGLTF.UriByteBuffer.ExtendCapacity(int capacity)
static Byte [] UniGLTF.UriByteBuffer.ReadEmbeded(string uri)
References UniGLTF.UriByteBuffer.ReadEmbedded.
static Byte [] UniGLTF.UriByteBuffer.ReadEmbedded(string uri)
Referenced by UniGLTF.UriByteBuffer.ReadEmbeded, UniGLTF.UriByteBuffer.ReadFromUri.
Byte [] UniGLTF.UriByteBuffer.ReadFromUri(string baseDir, string uri)
References UniGLTF.UriByteBuffer.ReadEmbedded.
Referenced by UniGLTF.UriByteBuffer.UriByteBuffer.