UniGLTF::PrimitiveExtensions
static bool UniGLTF.PrimitiveExtensions.HasNormal(this glTFPrimitives primitives)
Referenced by UniGLTF.PrimitiveExtensions.GetNormals.
static bool UniGLTF.PrimitiveExtensions.HasTexCoord0(this glTFPrimitives primitives)
Referenced by UniGLTF.PrimitiveExtensions.GetTexCoords0.
static bool UniGLTF.PrimitiveExtensions.HasTexCoord1(this glTFPrimitives primitives)
Referenced by UniGLTF.PrimitiveExtensions.GetTexCoords1.
static bool UniGLTF.PrimitiveExtensions.HasSkin(this glTFPrimitives primitives)
Referenced by UniGLTF.PrimitiveExtensions.GetJoints, UniGLTF.PrimitiveExtensions.GetWeights.
static bool UniGLTF.PrimitiveExtensions.HasColor(this glTFPrimitives primitives)
Referenced by UniGLTF.PrimitiveExtensions.GetColors.
static Vector3 [] UniGLTF.PrimitiveExtensions.GetPositions(this glTFPrimitives primitives, GltfData data)
static Vector3 [] UniGLTF.PrimitiveExtensions.GetNormals(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.PrimitiveExtensions.HasNormal.
static Vector2 [] UniGLTF.PrimitiveExtensions.GetTexCoords0(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.PrimitiveExtensions.HasTexCoord0.
static Vector2 [] UniGLTF.PrimitiveExtensions.GetTexCoords1(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.PrimitiveExtensions.HasTexCoord1.
static Color [] UniGLTF.PrimitiveExtensions.GetColors(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.glTF.accessors, UniGLTF.glTFPrimitives.attributes, UniGLTF.glTFAttributes.COLOR_0, UniGLTF.GltfData.GLTF, UniGLTF.PrimitiveExtensions.HasColor.
static JointsAccessor.Getter UniGLTF.PrimitiveExtensions.GetJoints(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.PrimitiveExtensions.HasSkin.
static WeightsAccessor.Getter UniGLTF.PrimitiveExtensions.GetWeights(this glTFPrimitives primitives, GltfData data, int positionsLength)
References UniGLTF.PrimitiveExtensions.HasSkin.