UniGLTF::AnimationImporterUtil
TangentMode
static TangentMode UniGLTF.AnimationImporterUtil.GetTangentMode(string interpolation)
Referenced by UniGLTF.AnimationImporterUtil.SetAnimationCurve.
static void UniGLTF.AnimationImporterUtil.CalculateTanget(List< Keyframe > keyframes, int current)
Referenced by UniGLTF.AnimationImporterUtil.SetAnimationCurve.
static string UniGLTF.AnimationImporterUtil.RelativePathFrom(List< glTFNode > nodes, glTFNode root, glTFNode target, List< string > path)
References UniGLTF.AnimationImporterUtil.RelativePathFrom.
static Quaternion UniGLTF.AnimationImporterUtil.GetShortest(Quaternion last, Quaternion rot)
static void UniGLTF.AnimationImporterUtil.SetAnimationCurve(AnimationClip targetClip, string relativePath, string[] propertyNames, float[] input, float[] output, string interpolation, Type curveType, ReverseFunc reverse)
References UniGLTF.AnimationImporterUtil.CalculateTanget, UniGLTF.AnimationImporterUtil.GetTangentMode.
static string UniGLTF.AnimationImporterUtil.RelativePathFrom(List< glTFNode > nodes, glTFNode root, glTFNode target)
Referenced by UniGLTF.AnimationImporterUtil.ConvertAnimationClip, UniGLTF.AnimationImporterUtil.RelativePathFrom.
static AnimationClip UniGLTF.AnimationImporterUtil.ConvertAnimationClip(GltfData data, glTFAnimation animation, IAxisInverter inverter, glTFNode root=null)
References UniGLTF.AnimationImporterUtil.RelativePathFrom, UniGLTF.gltf_mesh_extras_targetNames.TryGet.
static IEnumerable<VRMShaders.SubAssetKey> UniGLTF.AnimationImporterUtil.EnumerateSubAssetKeys(glTF gltf)
Referenced by UniGLTF.GltfScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnEnable, UniGLTF.GlbScriptedImporterEditor.OnEnable.
delegate float [] UniGLTF.AnimationImporterUtil.ReverseFunc(float[] current, float[] last)