VRMShaders::EditorTextureUtility
static bool VRMShaders.EditorTextureUtility.TryGetAsEditorTexture2DAsset(Texture texture, out Texture2D texture2D, out TextureImporter assetImporter)
Referenced by VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile, VRMShaders.TextureImporterConfigurator.Configure, VRMShaders.EditorTextureSerializer.ModifyTextureAssetBeforeExporting.
static bool VRMShaders.EditorTextureUtility.TryGetOriginalTexturePixelSize(TextureImporter textureImporter, out Vector2Int size)
Referenced by VRMShaders.TextureImporterConfigurator.ConfigureSize, VRMShaders.EditorTextureSerializer.IsTextureSizeMaintained.