UniGLTF::UnityExtensions
Vector3 UniGLTF.UnityExtensions.T
Referenced by UniGLTF.UnityExtensions.GetOrAddComponent< T >, UniGLTF.UnityExtensions.Has< T >.
Vector3 Quaternion UniGLTF.UnityExtensions.R
static Vector4 UniGLTF.UnityExtensions.ReverseZ(this Vector4 v)
References UnityEngine.Vector4.w, UnityEngine.Vector4.x, UnityEngine.Vector4.y, UnityEngine.Vector4.z.
Referenced by UniGLTF.UnityExtensions.ReverseZ.
static Vector4 UniGLTF.UnityExtensions.ReverseX(this Vector4 v)
References UnityEngine.Vector4.w, UnityEngine.Vector4.x, UnityEngine.Vector4.y, UnityEngine.Vector4.z.
Referenced by UniGLTF.UnityExtensions.ReverseX.
static Vector3 UniGLTF.UnityExtensions.ReverseZ(this Vector3 v)
References UnityEngine.Vector3.x, UnityEngine.Vector3.y, UnityEngine.Vector3.z.
static Vector3 UniGLTF.UnityExtensions.ReverseX(this Vector3 v)
References UnityEngine.Vector3.x, UnityEngine.Vector3.y, UnityEngine.Vector3.z.
static Vector2 UniGLTF.UnityExtensions.ReverseY(this Vector2 v)
References UnityEngine.Vector2.x, UnityEngine.Vector2.y.
static Vector2 UniGLTF.UnityExtensions.ReverseUV(this Vector2 v)
References UnityEngine.Vector2.x, UnityEngine.Vector2.y.
static Quaternion UniGLTF.UnityExtensions.ReverseZ(this Quaternion q)
References UniGLTF.UnityExtensions.ReverseZ.
static Quaternion UniGLTF.UnityExtensions.ReverseX(this Quaternion q)
References UniGLTF.UnityExtensions.ReverseX.
static Matrix4x4 UniGLTF.UnityExtensions.Matrix4x4FromColumns(Vector4 c0, Vector4 c1, Vector4 c2, Vector4 c3)
Referenced by VRM.VRMLookAtHead.LookAtMatrixFromWorld, VRM.VRMLookAt.LookAtMatrixFromWorld.
static Matrix4x4 UniGLTF.UnityExtensions.Matrix4x4FromRotation(Quaternion q)
static Matrix4x4 UniGLTF.UnityExtensions.ReverseZ(this Matrix4x4 m)
References UniGLTF.UnityExtensions.ReverseZ.
static Matrix4x4 UniGLTF.UnityExtensions.ReverseX(this Matrix4x4 m)
References UniGLTF.UnityExtensions.ReverseX.
static Matrix4x4 UniGLTF.UnityExtensions.MatrixFromArray(float[] values)
static Quaternion UniGLTF.UnityExtensions.ExtractRotation(this Matrix4x4 matrix)
static Vector3 UniGLTF.UnityExtensions.ExtractPosition(this Matrix4x4 matrix)
static Vector3 UniGLTF.UnityExtensions.ExtractScale(this Matrix4x4 matrix)
static bool UniGLTF.UnityExtensions.Nearly(in Matrix4x4 lhs, in Matrix4x4 rhs, float epsilon=1e-3f)
static string UniGLTF.UnityExtensions.RelativePathFrom(this Transform self, Transform root)
static Transform UniGLTF.UnityExtensions.GetChildByName(this Transform self, string childName)
static Transform UniGLTF.UnityExtensions.GetFromPath(this Transform self, string path)
static IEnumerable<Transform> UniGLTF.UnityExtensions.GetChildren(this Transform self)
static IEnumerable<Transform> UniGLTF.UnityExtensions.Traverse(this Transform t)
static Transform UniGLTF.UnityExtensions.FindDescenedant(this Transform t, string name)
References UniGLTF.UnityExtensions.FindDescendant.
static Transform UniGLTF.UnityExtensions.FindDescendant(this Transform t, string name)
Referenced by UniGLTF.UnityExtensions.FindDescenedant.
static IEnumerable<Transform> UniGLTF.UnityExtensions.Ancestors(this Transform t)
static float [] UniGLTF.UnityExtensions.ToArray(this Quaternion q)
static float [] UniGLTF.UnityExtensions.ToArray(this Vector3 v)
static float [] UniGLTF.UnityExtensions.ToArray(this Vector4 v)
static void UniGLTF.UnityExtensions.ReverseRecursive(this Transform root, IAxisInverter axisInverter)
References UniGLTF.PosRot.FromGlobalTransform.
static Mesh UniGLTF.UnityExtensions.GetSharedMesh(this Transform t)
static Material [] UniGLTF.UnityExtensions.GetSharedMaterials(this Transform t)
static bool UniGLTF.UnityExtensions.Has< T >(this Transform transform, T t)
References UniGLTF.UnityExtensions.T.
static T UniGLTF.UnityExtensions.GetOrAddComponent< T >(this GameObject go)
References UniGLTF.UnityExtensions.T.
static bool UniGLTF.UnityExtensions.EnableForExport(this Component mono)
static Vector3 Quaternion Vector3 S UniGLTF.UnityExtensions.Extract(this Matrix4x4 m)