UniGLTF::MatrixTests
static void UniGLTF.MatrixTests.AssertFloat(float expected, float value, string template, float epsilon=1e-5f)
Referenced by UniGLTF.MatrixTests.AssertQuaternion, UniGLTF.MatrixTests.AssertVec3.
static void UniGLTF.MatrixTests.AssertQuaternion(in Quaternion expected, in Quaternion value, string message)
References UniGLTF.MatrixTests.AssertFloat.
Referenced by UniGLTF.MatrixTests.AssertExtract.
static void UniGLTF.MatrixTests.AssertVec3(in Vector3 expected, in Vector3 value, string message)
References UniGLTF.MatrixTests.AssertFloat.
Referenced by UniGLTF.MatrixTests.AssertExtract.
static void UniGLTF.MatrixTests.AssertExtract(in Vector3 t, in Quaternion r, in Vector3 s)
References UniGLTF.MatrixTests.AssertQuaternion, UniGLTF.MatrixTests.AssertVec3.
Referenced by UniGLTF.MatrixTests.ExtractMirror_MinusX, UniGLTF.MatrixTests.ExtractTest.
void UniGLTF.MatrixTests.ExtractTest()
References UniGLTF.MatrixTests.AssertExtract.
void UniGLTF.MatrixTests.ExtractMirror_MinusX()
References UniGLTF.MatrixTests.AssertExtract.