UniGLTF::UniGLTFPreference
const string UniGLTF.UniGLTFPreference.UNIGLTF_ENABLE_ZIPARCHVIE_IMPORTER
Referenced by UniGLTF.UniGLTFPreference.OnPreferenceGUI.
const string UniGLTF.UniGLTFPreference.AXIS_KEY
Axes UniGLTF.UniGLTFPreference.s_axis
Axes UniGLTF.UniGLTFPreference.GltfIOAxis
Referenced by UniGLTF.GltfExportWindow.Initialize, UniGLTF.UniGLTFPreference.OnPreferenceGUI, UniGLTF.ScriptedImporterAxesExtensions.ToAxes.
static IEnumerable<string> UniGLTF.UniGLTFPreference.GetReimportPaths()
Referenced by UniGLTF.UniGLTFPreference.OnPreferenceGUI.
static void UniGLTF.UniGLTFPreference.OnPreferenceGUI()
References UniGLTF.UniGLTFPreference.GetReimportPaths, UniGLTF.UniGLTFPreference.GltfIOAxis, UniGLTF.UniGLTFPreference.UNIGLTF_ENABLE_ZIPARCHVIE_IMPORTER.
static bool UniGLTF.UniGLTFPreference.HasSymbol(string symbol)
Referenced by UniGLTF.UniGLTFPreference.ToggleSymbol.
static void UniGLTF.UniGLTFPreference.AddSymbol(string symbol)
Referenced by UniGLTF.UniGLTFPreference.ToggleSymbol.
static void UniGLTF.UniGLTFPreference.RemoveSymbol(string symbol)
Referenced by UniGLTF.UniGLTFPreference.ToggleSymbol.
static void UniGLTF.UniGLTFPreference.ToggleSymbol(string title, string symbol)
References UniGLTF.UniGLTFPreference.AddSymbol, UniGLTF.UniGLTFPreference.HasSymbol, UniGLTF.UniGLTFPreference.RemoveSymbol.