VRM::VRMLoadTest
static IEnumerable<FileInfo> VRM.VRMLoadTest.EnumerateGltfFiles(DirectoryInfo dir)
Referenced by VRM.VRMLoadTest.VrmTestModelsTests.
static void VRM.VRMLoadTest.Message(string path, Exception exception)
Referenced by VRM.VRMLoadTest.Load.
static GameObject VRM.VRMLoadTest.Load(FileInfo gltf, DirectoryInfo root, byte[] bytes=null)
References VRM.VRMLoadTest.Message.
Referenced by VRM.VRMLoadTest.VrmTestModelsTests.
void VRM.VRMLoadTest.VrmTestModelsTests()
References VRM.VRMLoadTest.EnumerateGltfFiles, VRM.VRMLoadTest.Load.