VRM::PreviewEditor
PreviewFaceRenderer VRM.PreviewEditor.m_renderer
PreviewRenderUtilityを管理する。
PreviewRenderUtility.m_cameraのUnityVersionによる切り分け
Referenced by VRM.PreviewEditor.OnDisable, VRM.PreviewEditor.OnEnable, VRM.PreviewEditor.OnPreviewGUI.
PreviewSceneManager VRM.PreviewEditor.m_scene
Prefabをインスタンス化したシーンを管理する。
BlendShapeのBakeMaterialMorphの適用PreviewカメラのコントロールPreviewライティングのコントロール
Referenced by VRM.PreviewEditor.Bake, VRM.PreviewEditor.OnDestroy, VRM.PreviewEditor.OnPreviewGUI.
GameObject VRM.PreviewEditor.m_prefab
Previewシーンに表示するPrefab
float VRM.PreviewEditor.m_yaw
Referenced by VRM.PreviewEditor.OnPreviewGUI.
float VRM.PreviewEditor.m_pitch
Referenced by VRM.PreviewEditor.OnPreviewGUI.
Vector3 VRM.PreviewEditor.m_position
Referenced by VRM.PreviewEditor.OnPreviewGUI.
PreviewSceneManager VRM.PreviewEditor.PreviewSceneManager
GameObject VRM.PreviewEditor.Prefab
Referenced by VRM.PreviewEditor.GetPrefab, VRM.PreviewEditor.OnEnable, VRM.PreviewEditor.OnInspectorGUI.
int VRM.PreviewEditor.sliderHash
Referenced by VRM.PreviewEditor.OnPreviewGUI.
RenderTexture VRM.PreviewEditor.PreviewTexture
Referenced by VRM.BlendShapeClipEditor.OnInspectorGUI, VRM.PreviewEditor.OnPreviewGUI.
abstract PreviewSceneManager.BakeValue VRM.PreviewEditor.GetBakeValue()
Referenced by VRM.PreviewEditor.Bake.
void VRM.PreviewEditor.Bake()
Preview シーンに BlendShape と MaterialValue を適用する
References VRM.PreviewEditor.GetBakeValue, VRM.PreviewEditor.m_scene.
virtual GameObject VRM.PreviewEditor.GetPrefab()
References VRM.PreviewEditor.Prefab.
Referenced by VRM.PreviewEditor.OnEnable.
virtual void VRM.PreviewEditor.OnEnable()
References VRM.PreviewEditor.GetPrefab, VRM.PreviewEditor.m_renderer, VRM.PreviewEditor.Prefab.
virtual void VRM.PreviewEditor.OnDisable()
References VRM.PreviewEditor.m_renderer.
virtual void VRM.PreviewEditor.OnDestroy()
References VRM.PreviewEditor.m_scene.
static void VRM.PreviewEditor.Separator()
Referenced by VRM.BlendShapeClipEditor.OnInspectorGUI, VRM.BlendShapeAvatarEditor.OnInspectorGUI.
override void VRM.PreviewEditor.OnInspectorGUI()
References VRM.PreviewEditor.Prefab.
override bool VRM.PreviewEditor.HasPreviewGUI()
override void VRM.PreviewEditor.OnPreviewGUI(Rect r, GUIStyle background)
References VRM.PreviewEditor.m_pitch, VRM.PreviewEditor.m_position, VRM.PreviewEditor.m_renderer, VRM.PreviewEditor.m_scene, VRM.PreviewEditor.m_yaw, VRM.PreviewEditor.PreviewTexture, VRM.PreviewEditor.sliderHash.