VRM::VRMLookAtHead
bool VRM.VRMLookAtHead.DrawGizmo
Referenced by VRM.VRMLookAtHeadEditor.OnSceneGUI.
UpdateType VRM.VRMLookAtHead.UpdateType
Transform VRM.VRMLookAtHead.Target
Referenced by VRM.VRMLookAtHead.LookWorldPosition, VRM.VRMLookAtHeadEditor.OnSceneGUI.
Transform VRM.VRMLookAtHead.Head
Referenced by VRM.VRMLookAtHead.Awake, VRM.VRMLookAtHead.LateUpdate, VRM.VRMLookAtHead.LookFace, VRM.VRMLookAtHeadEditor.OnSceneGUI, VRM.VRMLookAtHead.Update.
Matrix4x4 VRM.VRMLookAtHead.YawMatrix
float VRM.VRMLookAtHead.Yaw
float VRM.VRMLookAtHead.Pitch
float VRM.VRMLookAtHead.m_yaw
Referenced by VRM.VRMLookAtHead.RaiseYawPitchChanged.
float VRM.VRMLookAtHead.m_pitch
Referenced by VRM.VRMLookAtHead.RaiseYawPitchChanged.
Action<float, float> VRM.VRMLookAtHead.YawPitchChanged
Referenced by VRM.VRMLookAtHead.RaiseYawPitchChanged.
Texture2D VRM.VRMLookAtHead.CreateThumbnail()
void VRM.VRMLookAtHead.LookFace(Transform t)
References VRM.VRMLookAtHead.Head.
Referenced by VRM.VRMLookAtHead.CreateThumbnail.
void VRM.VRMLookAtHead.OnImported(VRMImporterContext context)
Serializableな値を初期化する
imported
void VRM.VRMLookAtHead.RaiseYawPitchChanged(float yaw, float pitch)
References VRM.VRMLookAtHead.m_pitch, VRM.VRMLookAtHead.m_yaw, VRM.VRMLookAtHead.YawPitchChanged.
Referenced by VRM.VRMLookAtHead.LookWorldPosition.
void VRM.VRMLookAtHead.LookWorldPosition()
References VRM.VRMLookAtHead.Target.
Referenced by VRM.VRMLookAtHead.LateUpdate, VRM.VRMLookAtHead.Update.
void VRM.VRMLookAtHead.LookWorldPosition(Vector3 targetPosition, out float yaw, out float pitch)
References VRM.VRMLookAtHead.RaiseYawPitchChanged.
void VRM.VRMLookAtHead.CreateThumbnail(Camera camera, Texture2D dst)
References VRM.VRMLookAtHead.LookFace.
void VRM.VRMLookAtHead.Awake()
References VRM.head, VRM.VRMLookAtHead.Head.
void VRM.VRMLookAtHead.Update()
References VRM.VRMLookAtHead.Head, VRM.VRMLookAtHead.LookWorldPosition.
void VRM.VRMLookAtHead.LateUpdate()
References VRM.VRMLookAtHead.Head, VRM.VRMLookAtHead.LookWorldPosition.
static Matrix4x4 VRM.VRMLookAtHead.LookAtMatrixFromWorld(Vector3 from, Vector3 target)
References VRM.VRMLookAtHead.LookAtMatrix, UniGLTF.UnityExtensions.Matrix4x4FromColumns, UnityEngine.Vector3.x, UnityEngine.Vector3.y, UnityEngine.Vector3.z.
static Matrix4x4 VRM.VRMLookAtHead.LookAtMatrix(Vector3 up_vector, Vector3 localPosition)
Referenced by VRM.VRMLookAtHead.LookAtMatrix, VRM.VRMLookAtHead.LookAtMatrixFromWorld.
static Matrix4x4 VRM.VRMLookAtHead.LookAtMatrix(Matrix4x4 m, Vector3 target)
References VRM.VRMLookAtHead.LookAtMatrix.