VRM::VRMMaterialExporter
readonly string [] VRM.VRMMaterialExporter.TAGS
Referenced by VRM.VRMMaterialExporter.CreateFromMaterial.
static string VRM.VRMMaterialExporter.VrmMaterialName(string shaderName)
static glTF_VRM_Material VRM.VRMMaterialExporter.CreateFromMaterial(Material m, ITextureExporter textureExporter)
References VRM.VRMMaterialExporter.TAGS, VRM.glTF_VRM_Material.VRM_USE_GLTFSHADER, UniGLTF.ShaderPropExporter.PreShaderPropExporter.VRMExtensionShaders.
override glTFMaterial VRM.VRMMaterialExporter.CreateMaterial(Material m)
References VRM.VRMMaterialExporter.Export_VRMMToon, VRM.VRMMaterialExporter.Export_VRMUnlitCutout, VRM.VRMMaterialExporter.Export_VRMUnlitTexture, VRM.VRMMaterialExporter.Export_VRMUnlitTransparent, VRM.VRMMaterialExporter.Export_VRMUnlitTransparentZWrite.
static glTFMaterial VRM.VRMMaterialExporter.Export_VRMUnlitTexture(Material m)
Referenced by VRM.VRMMaterialExporter.CreateMaterial.
static glTFMaterial VRM.VRMMaterialExporter.Export_VRMUnlitTransparent(Material m)
Referenced by VRM.VRMMaterialExporter.CreateMaterial.
static glTFMaterial VRM.VRMMaterialExporter.Export_VRMUnlitCutout(Material m)
Referenced by VRM.VRMMaterialExporter.CreateMaterial.
static glTFMaterial VRM.VRMMaterialExporter.Export_VRMUnlitTransparentZWrite(Material m)
Referenced by VRM.VRMMaterialExporter.CreateMaterial.
static glTFMaterial VRM.VRMMaterialExporter.Export_VRMMToon(Material m)
Referenced by VRM.VRMMaterialExporter.CreateMaterial.