VRM::VRMSerializer
static void VRM.VRMSerializer.Serialize(JsonFormatter f, glTF_VRM_extensions value)
References VRM.glTF_VRM_extensions.blendShapeMaster, VRM.glTF_VRM_extensions.exporterVersion, VRM.glTF_VRM_extensions.firstPerson, VRM.glTF_VRM_extensions.humanoid, VRM.glTF_VRM_extensions.materialProperties, VRM.glTF_VRM_extensions.meta, VRM.glTF_VRM_extensions.secondaryAnimation, VRM.VRMSerializer.Serialize_vrm_blendShapeMaster, VRM.VRMSerializer.Serialize_vrm_firstPerson, VRM.VRMSerializer.Serialize_vrm_humanoid, VRM.VRMSerializer.Serialize_vrm_materialProperties, VRM.VRMSerializer.Serialize_vrm_meta, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation, VRM.glTF_VRM_extensions.specVersion.
static void VRM.VRMSerializer.Serialize_vrm_meta(JsonFormatter f, glTF_VRM_Meta value)
References VRM.glTF_VRM_Meta.allowedUserName, VRM.glTF_VRM_Meta.author, VRM.glTF_VRM_Meta.commercialUssageName, VRM.glTF_VRM_Meta.contactInformation, VRM.glTF_VRM_Meta.licenseName, VRM.glTF_VRM_Meta.otherLicenseUrl, VRM.glTF_VRM_Meta.otherPermissionUrl, VRM.glTF_VRM_Meta.reference, VRM.glTF_VRM_Meta.sexualUssageName, VRM.glTF_VRM_Meta.texture, VRM.glTF_VRM_Meta.title, VRM.glTF_VRM_Meta.version, VRM.glTF_VRM_Meta.violentUssageName.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_humanoid(JsonFormatter f, glTF_VRM_Humanoid value)
References VRM.glTF_VRM_Humanoid.humanBones, VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones(JsonFormatter f, List< glTF_VRM_HumanoidBone > value)
References VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_humanoid.
static void VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones_ITEM(JsonFormatter f, glTF_VRM_HumanoidBone value)
References VRM.glTF_VRM_HumanoidBone.axisLength, VRM.glTF_VRM_HumanoidBone.bone, VRM.glTF_VRM_HumanoidBone.center, VRM.glTF_VRM_HumanoidBone.max, VRM.glTF_VRM_HumanoidBone.min, VRM.glTF_VRM_HumanoidBone.node, VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__center, VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__max, VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__min, UnityEngine.Vector3.zero.
Referenced by VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones.
static void VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__min(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__max(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones__center(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_humanoid_humanBones_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson(JsonFormatter f, glTF_VRM_Firstperson value)
References VRM.glTF_VRM_Firstperson.firstPersonBone, VRM.glTF_VRM_Firstperson.firstPersonBoneOffset, VRM.glTF_VRM_Firstperson.lookAtHorizontalInner, VRM.glTF_VRM_Firstperson.lookAtHorizontalOuter, VRM.glTF_VRM_Firstperson.lookAtTypeName, VRM.glTF_VRM_Firstperson.lookAtVerticalDown, VRM.glTF_VRM_Firstperson.lookAtVerticalUp, VRM.glTF_VRM_Firstperson.meshAnnotations, VRM.VRMSerializer.Serialize_vrm_firstPerson_firstPersonBoneOffset, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalInner, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalOuter, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalDown, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalUp, VRM.VRMSerializer.Serialize_vrm_firstPerson_meshAnnotations.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_firstPersonBoneOffset(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_meshAnnotations(JsonFormatter f, List< glTF_VRM_MeshAnnotation > value)
References VRM.VRMSerializer.Serialize_vrm_firstPerson_meshAnnotations_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_meshAnnotations_ITEM(JsonFormatter f, glTF_VRM_MeshAnnotation value)
References VRM.glTF_VRM_MeshAnnotation.firstPersonFlag, VRM.glTF_VRM_MeshAnnotation.mesh.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson_meshAnnotations.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalInner(JsonFormatter f, glTF_VRM_DegreeMap value)
References VRM.glTF_VRM_DegreeMap.curve, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalInner_curve.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalInner_curve(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalInner.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalOuter(JsonFormatter f, glTF_VRM_DegreeMap value)
References VRM.glTF_VRM_DegreeMap.curve, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalOuter_curve.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalOuter_curve(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtHorizontalOuter.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalDown(JsonFormatter f, glTF_VRM_DegreeMap value)
References VRM.glTF_VRM_DegreeMap.curve, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalDown_curve.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalDown_curve(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalDown.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalUp(JsonFormatter f, glTF_VRM_DegreeMap value)
References VRM.glTF_VRM_DegreeMap.curve, VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalUp_curve.
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson.
static void VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalUp_curve(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_firstPerson_lookAtVerticalUp.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster(JsonFormatter f, glTF_VRM_BlendShapeMaster value)
References VRM.glTF_VRM_BlendShapeMaster.blendShapeGroups, VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups(JsonFormatter f, List< glTF_VRM_BlendShapeGroup > value)
References VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups_ITEM(JsonFormatter f, glTF_VRM_BlendShapeGroup value)
References VRM.glTF_VRM_BlendShapeGroup.binds, VRM.glTF_VRM_BlendShapeGroup.materialValues, VRM.glTF_VRM_BlendShapeGroup.name, VRM.glTF_VRM_BlendShapeGroup.presetName, VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__binds, VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__binds(JsonFormatter f, List< glTF_VRM_BlendShapeBind > value)
References VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__binds_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__binds_ITEM(JsonFormatter f, glTF_VRM_BlendShapeBind value)
References VRM.glTF_VRM_BlendShapeBind.index, VRM.glTF_VRM_BlendShapeBind.mesh, VRM.glTF_VRM_BlendShapeBind.weight.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__binds.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues(JsonFormatter f, List< glTF_VRM_MaterialValueBind > value)
References VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_ITEM(JsonFormatter f, glTF_VRM_MaterialValueBind value)
References VRM.glTF_VRM_MaterialValueBind.materialName, VRM.glTF_VRM_MaterialValueBind.propertyName, VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue, VRM.glTF_VRM_MaterialValueBind.targetValue.
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues.
static void VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation(JsonFormatter f, glTF_VRM_SecondaryAnimation value)
References VRM.glTF_VRM_SecondaryAnimation.boneGroups, VRM.glTF_VRM_SecondaryAnimation.colliderGroups, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups(JsonFormatter f, List< glTF_VRM_SecondaryAnimationGroup > value)
References VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups_ITEM(JsonFormatter f, glTF_VRM_SecondaryAnimationGroup value)
References VRM.glTF_VRM_SecondaryAnimationGroup.bones, VRM.glTF_VRM_SecondaryAnimationGroup.colliderGroups, VRM.glTF_VRM_SecondaryAnimationGroup.comment, VRM.glTF_VRM_SecondaryAnimationGroup.gravityDir, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__bones, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__colliderGroups, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__gravityDir.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__gravityDir(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__bones(JsonFormatter f, Int32[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups__colliderGroups(JsonFormatter f, Int32[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_boneGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups(JsonFormatter f, List< glTF_VRM_SecondaryAnimationColliderGroup > value)
References VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups_ITEM(JsonFormatter f, glTF_VRM_SecondaryAnimationColliderGroup value)
References VRM.glTF_VRM_SecondaryAnimationColliderGroup.colliders, VRM.glTF_VRM_SecondaryAnimationColliderGroup.node, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders(JsonFormatter f, List< glTF_VRM_SecondaryAnimationCollider > value)
References VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders_ITEM(JsonFormatter f, glTF_VRM_SecondaryAnimationCollider value)
References VRM.glTF_VRM_SecondaryAnimationCollider.offset, VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders__offset.
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders.
static void VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders__offset(JsonFormatter f, Vector3 value)
Referenced by VRM.VRMSerializer.Serialize_vrm_secondaryAnimation_colliderGroups__colliders_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties(JsonFormatter f, List< glTF_VRM_Material > value)
References VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.
Referenced by VRM.VRMSerializer.Serialize.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM(JsonFormatter f, glTF_VRM_Material value)
References VRM.glTF_VRM_Material.floatProperties, VRM.glTF_VRM_Material.keywordMap, VRM.glTF_VRM_Material.name, VRM.VRMSerializer.Serialize_vrm_materialProperties__floatProperties, VRM.VRMSerializer.Serialize_vrm_materialProperties__keywordMap, VRM.VRMSerializer.Serialize_vrm_materialProperties__tagMap, VRM.VRMSerializer.Serialize_vrm_materialProperties__textureProperties, VRM.VRMSerializer.Serialize_vrm_materialProperties__vectorProperties, VRM.glTF_VRM_Material.shader, VRM.glTF_VRM_Material.tagMap, VRM.glTF_VRM_Material.textureProperties, VRM.glTF_VRM_Material.vectorProperties.
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__floatProperties(JsonFormatter f, Dictionary< string, Single > value)
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__vectorProperties(JsonFormatter f, Dictionary< string, Single[]> value)
References VRM.VRMSerializer.Serialize_vrm_materialProperties__vectorProperties_ITEM.
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__vectorProperties_ITEM(JsonFormatter f, Single[] value)
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties__vectorProperties.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__textureProperties(JsonFormatter f, Dictionary< string, Int32 > value)
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__keywordMap(JsonFormatter f, Dictionary< string, Boolean > value)
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.
static void VRM.VRMSerializer.Serialize_vrm_materialProperties__tagMap(JsonFormatter f, Dictionary< string, String > value)
Referenced by VRM.VRMSerializer.Serialize_vrm_materialProperties_ITEM.