UniGLTF::gltf_mesh_extras_targetNames
const string UniGLTF.gltf_mesh_extras_targetNames.ExtraName
Referenced by UniGLTF.gltf_mesh_extras_targetNames.Serialize.
readonly Utf8String UniGLTF.gltf_mesh_extras_targetNames.ExtraNameUtf8
Referenced by UniGLTF.gltf_mesh_extras_targetNames.TryGet.
static List<string> UniGLTF.gltf_mesh_extras_targetNames.Deserialize(JsonNode json)
References UniJSON.JsonNode.Value, UniJSON.JsonValue.ValueType.
Referenced by UniGLTF.gltf_mesh_extras_targetNames.TryGet.
static bool UniGLTF.gltf_mesh_extras_targetNames.TryGet(glTFMesh mesh, out List< string > targetNames)
References UniGLTF.gltf_mesh_extras_targetNames.Deserialize, UniGLTF.gltf_mesh_extras_targetNames.ExtraNameUtf8, UniGLTF.glTFMesh.extras, UniGLTF.glTFMesh.primitives.
Referenced by UniGLTF.AnimationImporterUtil.ConvertAnimationClip, UniGLTF.MeshContext.RenameBlendShape.
static glTFExtension UniGLTF.gltf_mesh_extras_targetNames.Serialize(params string[] args)
References UniGLTF.gltf_mesh_extras_targetNames.ExtraName.
static void UniGLTF.gltf_mesh_extras_targetNames.Serialize(glTFMesh gltfMesh, IEnumerable< string > targetNames)
References UniGLTF.gltf_mesh_extras_targetNames.ExtraName.