VRM::SkinnedMeshUtility
const string VRM.SkinnedMeshUtility.MENU_KEY
const int VRM.SkinnedMeshUtility.MENU_PRIORITY
static Object VRM.SkinnedMeshUtility.GetPrefab(GameObject instance)
Referenced by VRM.SkinnedMeshUtility.ApplyChangesToPrefab, VRM.MeshIntegratorEditor.GetRootPrefabPath.
static bool VRM.SkinnedMeshUtility.IsPrefab(Object instance)
Referenced by VRM.SkinnedMeshUtility.InstantiatePrefab.
static void VRM.SkinnedMeshUtility.ApplyChangesToPrefab(GameObject instance)
References VRM.SkinnedMeshUtility.GetPrefab.
static GameObject VRM.SkinnedMeshUtility.InstantiatePrefab(GameObject prefab)
References VRM.SkinnedMeshUtility.IsPrefab.