MToon::EditorUtils
string MToon.EditorUtils.BasePath
string MToon.EditorUtils.ShaderFilePath
Referenced by MToon.EditorUtils.UpdateShaderFile.
string MToon.EditorUtils.ReadMeFilePath
Referenced by MToon.EditorUtils.UpdateReadMeFile.
string MToon.EditorUtils.VersionFilePath
Referenced by MToon.EditorUtils.UpdateVersionFile.
static void MToon.EditorUtils.VerUp(string version)
References MToon.EditorUtils.UpdateReadMeFile, MToon.EditorUtils.UpdateShaderFile, MToon.EditorUtils.UpdateVersionFile.
static void MToon.EditorUtils.UpdateShaderFile(string version)
References MToon.EditorUtils.ShaderFilePath.
Referenced by MToon.EditorUtils.VerUp.
static void MToon.EditorUtils.UpdateReadMeFile(string version)
References MToon.EditorUtils.ReadMeFilePath.
Referenced by MToon.EditorUtils.VerUp.
static void MToon.EditorUtils.UpdateVersionFile(string version)
References MToon.EditorUtils.VersionFilePath.
Referenced by MToon.EditorUtils.VerUp.