VRM::VRMEditorExporter
static byte [] VRM.VRMEditorExporter.Export(GameObject exportRoot, VRMMetaObject meta, VRMExportSettings settings)
Editor向けのエクスポート処理
path 出力先 settings エクスポート設定
static bool VRM.VRMEditorExporter.IsPrefab(GameObject go)
static BlendShapeAvatar VRM.VRMEditorExporter.CopyBlendShapeAvatar(BlendShapeAvatar src, bool removeUnknown)
DeepCopy
src
Referenced by VRM.VRMEditorExporter.Export.
static void VRM.VRMEditorExporter.ReplaceMesh(GameObject target, SkinnedMeshRenderer smr, BlendShapeAvatar copyBlendShapeAvatar)
使用されない BlendShape を間引いた Mesh を作成して置き換える
mesh
Referenced by VRM.VRMEditorExporter.Export.
static void VRM.VRMEditorExporter.ForceUniqueName(Transform transform, Dictionary< string, int > nameCount)
Referenced by VRM.VRMEditorExporter.Export.
static byte [] VRM.VRMEditorExporter.Export(GameObject exportRoot, VRMMetaObject meta, VRMExportSettings settings, List< GameObject > destroy)
path settings destroy 作業が終わったらDestoryするべき一時オブジェクト
References VRM.VRMEditorExporter.CopyBlendShapeAvatar, VRM.VRMEditorExporter.ForceUniqueName, VRM.VRMExportSettings.MeshExportSettings, VRM.VRMExportSettings.PoseFreeze, VRM.VRMExportSettings.ReduceBlendshape, VRM.VRMExportSettings.ReduceBlendshapeClip, VRM.VRMEditorExporter.ReplaceMesh.