VRMShaders::EditorTextureSerializer
readonly RuntimeTextureSerializer VRMShaders.EditorTextureSerializer._runtimeSerializer
byte [] VRMShaders.EditorTextureSerializer.bytes
Referenced by VRMShaders.EditorTextureSerializer.ExportBytesWithMime.
bool VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile(Texture texture, ColorSpace exportColorSpace)
Texture をオリジナルのテクスチャアセット(png/jpg)ファイルのバイト列そのまま出力してよいかどうか判断する。 具体的な条件は以下
TextureAsset が存在するTextureImporter の maxSize が画像の縦横サイズ以上TextureImporter の色空間設定が exportColorSpace と一致する各 Texture Type ごとの判定 Unity の Texture2D のデータは、その参照元であるテクスチャアセットファイルのデータと一致することはむしろ稀。
References VRMShaders.EditorTextureSerializer.IsFileColorSpaceSameWithExportColorSpace, VRMShaders.EditorTextureSerializer.IsTextureSizeMaintained, VRMShaders.EditorTextureUtility.TryGetAsEditorTexture2DAsset.
Referenced by VRMShaders.EditorTextureSerializer.ExportBytesWithMime.
void VRMShaders.EditorTextureSerializer.ModifyTextureAssetBeforeExporting(Texture texture)
出力に使用したいテクスチャに対して、Unity のエディタアセットとしての圧縮設定を OFF にする。
References VRMShaders.EditorTextureUtility.TryGetAsEditorTexture2DAsset.
byte [] string mime VRMShaders.EditorTextureSerializer.ExportBytesWithMime(Texture2D texture, ColorSpace exportColorSpace)
References VRMShaders.EditorTextureSerializer.bytes, VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile, VRMShaders.EditorTextureSerializer.TryGetBytesWithMime.
bool VRMShaders.EditorTextureSerializer.TryGetBytesWithMime(Texture2D texture, out byte[] bytes, out string mime)
Assetから画像のバイト列を得る
Referenced by VRMShaders.EditorTextureSerializer.ExportBytesWithMime.
bool VRMShaders.EditorTextureSerializer.IsTextureSizeMaintained(TextureImporter textureImporter)
Texture2D の画像サイズが、オリジナルの画像サイズを維持しているかどうか
TextureImporter の MaxTextureSize 設定によっては、Texture2D の画像サイズはオリジナルも小さくなりうる。
References VRMShaders.EditorTextureUtility.TryGetOriginalTexturePixelSize.
Referenced by VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile.
bool VRMShaders.EditorTextureSerializer.IsFileColorSpaceSameWithExportColorSpace(TextureImporter textureImporter, ColorSpace colorSpace)
Referenced by VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile.