UniGLTF::BoneInfo
readonly Transform UniGLTF.BoneInfo._head
Referenced by UniGLTF.BoneInfo.BoneInfo, UniGLTF.BoneInfo.GetHeadPosition, UniGLTF.BoneInfo.GetUpVector.
readonly Transform UniGLTF.BoneInfo._tail
Referenced by UniGLTF.BoneInfo.BoneInfo, UniGLTF.BoneInfo.GetTailPosition.
readonly Vector3 UniGLTF.BoneInfo._headLocalForward
Referenced by UniGLTF.BoneInfo.BoneInfo, UniGLTF.BoneInfo.GetTailPosition.
readonly Vector3 UniGLTF.BoneInfo._headLocalUp
Referenced by UniGLTF.BoneInfo.BoneInfo, UniGLTF.BoneInfo.GetUpVector.
HumanBodyBones UniGLTF.BoneInfo.HeadBone
Referenced by UniGLTF.BoneInfo.BoneInfo.
HumanBodyBones UniGLTF.BoneInfo.TailBone
Referenced by UniGLTF.BoneInfo.BoneInfo.
GameObject UniGLTF.BoneInfo.HeadObject
readonly Dictionary<HumanBodyBones, Vector3> UniGLTF.BoneInfo.LeafBoneWithDirection
Referenced by UniGLTF.BoneInfo.GetHumanoidBones.
HumanBodyBones [] UniGLTF.BoneInfo._NotConnectedBones
Referenced by UniGLTF.BoneInfo.GetHumanoidBones.
UniGLTF.BoneInfo.BoneInfo(Transform head, Transform tail, HumanBodyBones headBone, HumanBodyBones tailBone)
References UniGLTF.BoneInfo._head, UniGLTF.BoneInfo._headLocalForward, UniGLTF.BoneInfo._headLocalUp, UniGLTF.BoneInfo._tail, UniGLTF.BoneInfo.CalculateLocalUpVector, UniGLTF.BoneInfo.HeadBone, UniGLTF.BoneInfo.TailBone.
Referenced by UniGLTF.BoneInfo.GetHumanoidBones.
UniGLTF.BoneInfo.BoneInfo(Transform head, Vector3 headLocalDirection, HumanBodyBones headBone)
References UniGLTF.BoneInfo._head, UniGLTF.BoneInfo._headLocalForward, UniGLTF.BoneInfo._headLocalUp, UniGLTF.BoneInfo._tail, UniGLTF.BoneInfo.CalculateLocalUpVector, UniGLTF.BoneInfo.HeadBone.
override string UniGLTF.BoneInfo.ToString()
Vector3 UniGLTF.BoneInfo.GetHeadPosition()
References UniGLTF.BoneInfo._head.
Vector3 UniGLTF.BoneInfo.GetTailPosition()
References UniGLTF.BoneInfo._headLocalForward, UniGLTF.BoneInfo._tail.
Vector3 UniGLTF.BoneInfo.GetUpVector()
References UniGLTF.BoneInfo._head, UniGLTF.BoneInfo._headLocalUp.
static Vector3 UniGLTF.BoneInfo.CalculateLocalUpVector(Vector3 localForward)
Referenced by UniGLTF.BoneInfo.BoneInfo.
static HumanBodyBones UniGLTF.BoneInfo.FindHeadBone(Animator _animator, HumanBodyBones tail)
References UniGLTF.BoneInfo.GetParent.
Referenced by UniGLTF.BoneInfo.GetHumanoidBones.
static HumanBodyBones UniGLTF.BoneInfo.GetParent(HumanBodyBones bone)
Referenced by UniGLTF.BoneInfo.FindHeadBone.
static List<BoneInfo> UniGLTF.BoneInfo.GetHumanoidBones(Animator _animator)
References UniGLTF.BoneInfo._NotConnectedBones, UniGLTF.BoneInfo.BoneInfo, UniGLTF.BoneInfo.FindHeadBone, UniGLTF.BoneInfo.LeafBoneWithDirection, UnityEngine.Vector3.zero.