VRM::MeshIntegratorWizard
const string VRM.MeshIntegratorWizard.MENU_KEY
GameObject VRM.MeshIntegratorWizard.m_root
Referenced by VRM.MeshIntegratorWizard.Integrate, VRM.MeshIntegratorWizard.OnEnable, VRM.MeshIntegratorWizard.OnValidate.
Material [] VRM.MeshIntegratorWizard.m_uniqueMaterials
Referenced by VRM.MeshIntegratorWizard.OnValidate.
MaterialList [] VRM.MeshIntegratorWizard.m_duplicateMaterials
Referenced by VRM.MeshIntegratorWizard.OnValidate.
MeshIntegrationResult [] VRM.MeshIntegratorWizard.integrationResults
Referenced by VRM.MeshIntegratorWizard.Integrate.
static void VRM.MeshIntegratorWizard.CreateWizard()
static object VRM.MeshIntegratorWizard.GetPropertyValue(Shader shader, int i, Material m)
Referenced by VRM.MeshIntegratorWizard.GetMaterialKey.
static MaterialKey VRM.MeshIntegratorWizard.GetMaterialKey(Material m)
References VRM.MeshIntegratorWizard.GetPropertyValue.
Referenced by VRM.MeshIntegratorWizard.OnValidate.
void VRM.MeshIntegratorWizard.OnEnable()
References VRM.MeshIntegratorWizard.m_root, VRM.MeshIntegratorWizard.OnValidate.
void VRM.MeshIntegratorWizard.OnValidate()
References VRM.MeshIntegratorWizard.GetMaterialKey, VRM.MeshIntegratorWizard.m_duplicateMaterials, VRM.MeshIntegratorWizard.m_root, VRM.MeshIntegratorWizard.m_uniqueMaterials.
Referenced by VRM.MeshIntegratorWizard.OnEnable.
void VRM.MeshIntegratorWizard.OnWizardUpdate()
void VRM.MeshIntegratorWizard.Integrate()
References VRM.MeshIntegratorWizard.integrationResults, VRM.MeshIntegratorWizard.m_root.
Referenced by VRM.MeshIntegratorWizard.OnWizardCreate, VRM.MeshIntegratorWizard.OnWizardOtherButton.
void VRM.MeshIntegratorWizard.OnWizardCreate()
References VRM.MeshIntegratorWizard.Integrate.
void VRM.MeshIntegratorWizard.OnWizardOtherButton()
References VRM.MeshIntegratorWizard.Integrate.