UniGLTF::GltfScriptedImporterBase
ScriptedImporterAxes UniGLTF.GltfScriptedImporterBase.m_reverseAxis
Referenced by UniGLTF.GlbScriptedImporter.OnImportAsset, UniGLTF.GltfScriptedImporter.OnImportAsset, UniGLTF.ZipArchivedGltfScriptedImporter.OnImportAsset.
RenderPipelineTypes UniGLTF.GltfScriptedImporterBase.m_renderPipeline
Referenced by UniGLTF.GlbScriptedImporter.OnImportAsset, UniGLTF.GltfScriptedImporter.OnImportAsset, UniGLTF.ZipArchivedGltfScriptedImporter.OnImportAsset, UniGLTF.GltfScriptedImporterBase.OnValidate.
void UniGLTF.GltfScriptedImporterBase.OnValidate()
References UniGLTF.GltfScriptedImporterBase.m_renderPipeline.
static IMaterialDescriptorGenerator UniGLTF.GltfScriptedImporterBase.GetMaterialGenerator(RenderPipelineTypes renderPipeline)
Referenced by UniGLTF.GltfScriptedImporterBase.Import.
static void UniGLTF.GltfScriptedImporterBase.Import(ScriptedImporter scriptedImporter, AssetImportContext context, Axes reverseAxis, RenderPipelineTypes renderPipeline)
glb をパースして、UnityObject化、さらにAsset化する
scriptedImporter context reverseAxis
References UniGLTF.GltfScriptedImporterBase.GetMaterialGenerator.
Referenced by UniGLTF.GlbScriptedImporter.OnImportAsset, UniGLTF.GltfScriptedImporter.OnImportAsset, UniGLTF.ZipArchivedGltfScriptedImporter.OnImportAsset.