UniGLTF::GlbLowLevelParser
readonly string UniGLTF.GlbLowLevelParser.UniqueFixResourceSuffix
readonly Regex UniGLTF.GlbLowLevelParser._removeUniqueFixResourceSuffix
readonly string UniGLTF.GlbLowLevelParser._path
Referenced by UniGLTF.GlbLowLevelParser.GlbLowLevelParser, UniGLTF.GlbLowLevelParser.Parse.
readonly byte [] UniGLTF.GlbLowLevelParser._binary
Referenced by UniGLTF.GlbLowLevelParser.GlbLowLevelParser, UniGLTF.GlbLowLevelParser.Parse.
UniGLTF.GlbLowLevelParser.GlbLowLevelParser(string path, byte[] specifiedBinary)
References UniGLTF.GlbLowLevelParser._binary, UniGLTF.GlbLowLevelParser._path.
GltfData UniGLTF.GlbLowLevelParser.Parse()
References UniGLTF.GlbLowLevelParser._binary, UniGLTF.GlbLowLevelParser._path, UniGLTF.GlbLowLevelParser.ParseGlbChunks, UniGLTF.GlbLowLevelParser.ParseGltf.
static List<GlbChunk> UniGLTF.GlbLowLevelParser.ParseGlbChunks(byte[] data)
Referenced by UniGLTF.GlbLowLevelParser.Parse.
static GltfData UniGLTF.GlbLowLevelParser.ParseGltf(string path, string json, IReadOnlyList< GlbChunk > chunks, IStorage storage, MigrationFlags migrationFlags)
References UniGLTF.GlbLowLevelParser.FixAnimationNameUnique, UniGLTF.GlbLowLevelParser.FixMaterialNameUnique, UniGLTF.GlbLowLevelParser.FixMeshNameUnique, UniGLTF.GlbLowLevelParser.FixNodeName, UniGLTF.GlbLowLevelParser.FixTextureNameUnique, UniGLTF.GlbLowLevelParser.PrepareUri, UniGLTF.GlbLowLevelParser.RestoreOlderVersionValues.
Referenced by UniGLTF.GlbLowLevelParser.Parse.
static string UniGLTF.GlbLowLevelParser.PrepareUri(string uri)
image.uri を前理
uri
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.AppendImageExtension(glTFImage texture, string extension)
References UniGLTF.glTFImage.name.
static string UniGLTF.GlbLowLevelParser.FixNameUnique(HashSet< string > used, string originalName)
Referenced by UniGLTF.GlbLowLevelParser.FixAnimationNameUnique, UniGLTF.GlbLowLevelParser.FixMaterialNameUnique, UniGLTF.GlbLowLevelParser.FixTextureNameUnique.
static bool UniGLTF.GlbLowLevelParser.TryGetOriginalName(string name, out string originalName)
static void UniGLTF.GlbLowLevelParser.FixMeshNameUnique(glTF GLTF)
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.RenameImageFromTexture(glTF GLTF, int i)
static void UniGLTF.GlbLowLevelParser.FixTextureNameUnique(glTF GLTF)
gltfTexture.name を Unity Asset 名として運用する。 ユニークである必要がある。
References UniGLTF.GlbLowLevelParser.FixNameUnique.
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.FixMaterialNameUnique(glTF GLTF)
References UniGLTF.GlbLowLevelParser.FixNameUnique.
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.FixNodeName(glTF GLTF)
rename empty name to $"{index}"
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.FixAnimationNameUnique(glTF GLTF)
References UniGLTF.GlbLowLevelParser.FixNameUnique.
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.
static void UniGLTF.GlbLowLevelParser.RestoreOlderVersionValues(string Json, glTF GLTF)
References UniGLTF.glTF.images.
Referenced by UniGLTF.GlbLowLevelParser.ParseGltf.