UniGLTF::UniGLTFTests
static GameObject UniGLTF.UniGLTFTests.CreateSimpleScene()
Referenced by UniGLTF.UniGLTFTests.GlTFToJsonTest, UniGLTF.UniGLTFTests.UniGLTFSimpleSceneTest.
void UniGLTF.UniGLTFTests.AssertAreEqual(Transform go, Transform other)
Referenced by UniGLTF.UniGLTFTests.UniGLTFSimpleSceneTest.
void UniGLTF.UniGLTFTests.BufferTest(int init, params int[] size)
void UniGLTF.UniGLTFTests.UniGLTFSimpleSceneTest()
References UniGLTF.UniGLTFTests.AssertAreEqual, UniGLTF.UniGLTFTests.CreateSimpleScene.
void UniGLTF.UniGLTFTests.BufferTest()
void UniGLTF.UniGLTFTests.UnityPathTest()
void UniGLTF.UniGLTFTests.VersionChecker()
void UniGLTF.UniGLTFTests.MeshTest()
void UniGLTF.UniGLTFTests.PrimitiveTest()
void UniGLTF.UniGLTFTests.AttributesTest()
void UniGLTF.UniGLTFTests.TextureInfoTest()
void UniGLTF.UniGLTFTests.TextureInfoTestError()
void UniGLTF.UniGLTFTests.MaterialTest()
void UniGLTF.UniGLTFTests.MaterialAlphaTest()
void UniGLTF.UniGLTFTests.GlTFToJsonTest()
References UniGLTF.UniGLTFTests.CreateSimpleScene.
void UniGLTF.UniGLTFTests.MaterialTestError()
void UniGLTF.UniGLTFTests.NodeTest()
void UniGLTF.UniGLTFTests.NodeMeshTest()
void UniGLTF.UniGLTFTests.NodeTestError()
void UniGLTF.UniGLTFTests.SkinTest()
void UniGLTF.UniGLTFTests.SkinTestEmptyName()
void UniGLTF.UniGLTFTests.SkinTestErrorNull()
void UniGLTF.UniGLTFTests.SkinTestError()
void UniGLTF.UniGLTFTests.AssetsTest()
void UniGLTF.UniGLTFTests.AssetsTestError()
void UniGLTF.UniGLTFTests.GLTFTest()
void UniGLTF.UniGLTFTests.SameMeshButDifferentMaterialExport()
void UniGLTF.UniGLTFTests.MeshHasNoRendererTest()
void UniGLTF.UniGLTFTests.ExportingNullMeshTest()
void UniGLTF.UniGLTFTests.JsonUtilityTest()