UniGLTF::ImporterContext
ITextureDescriptorGenerator UniGLTF.ImporterContext.TextureDescriptorGenerator
Referenced by VRM.VRMEditorImporterContext.ConvertAndExtractImages, UniGLTF.ImporterContext.ImporterContext, VRM.VRMImporterContext.VRMImporterContext.
IMaterialDescriptorGenerator UniGLTF.ImporterContext.MaterialDescriptorGenerator
Referenced by UniGLTF.ImporterContext.ImporterContext.
TextureFactory UniGLTF.ImporterContext.TextureFactory
Referenced by UniGLTF.ImporterContext.ImporterContext.
MaterialFactory UniGLTF.ImporterContext.MaterialFactory
Referenced by UniGLTF.ImporterContext.ImporterContext.
AnimationClipFactory UniGLTF.ImporterContext.AnimationClipFactory
Referenced by UniGLTF.ImporterContext.ImporterContext.
GltfData UniGLTF.ImporterContext.Data
Referenced by UniGLTF.ImporterContext.ImporterContext, UniGLTF.ImporterContext.LoadAnimationAsync, UniGLTF.ImporterContext.LoadGeometryAsync, UniGLTF.ImporterContext.LoadMaterialsAsync, VRM.VRMImporterContext.ReadMetaAsync, VRM.VRMImporterContext.VRMImporterContext.
IReadOnlyDictionary<SubAssetKey, UnityEngine.Object> UniGLTF.ImporterContext.ExternalObjectMap
Referenced by UniGLTF.ImporterContext.ImporterContext.
String UniGLTF.ImporterContext.Json
glTF UniGLTF.ImporterContext.GLTF
Referenced by UniGLTF.ImporterContext.LoadAnimationAsync, UniGLTF.ImporterContext.LoadAsync, UniGLTF.ImporterContext.LoadGeometryAsync.
Axes UniGLTF.ImporterContext.InvertAxis
GLTF から Unity に変換するときに反転させる軸
List<Transform> UniGLTF.ImporterContext.Nodes
Referenced by VRM.VRMImporterContext.LoadFirstPerson, UniGLTF.ImporterContext.LoadGeometryAsync, VRM.VRMImporterContext.LoadHumanoid, VRM.VRMImporterContext.OnLoadHierarchy.
List<MeshWithMaterials> UniGLTF.ImporterContext.Meshes
Referenced by UniGLTF.ImporterContext.Dispose, VRM.VRMImporterContext.LoadBlendShapeBind, UniGLTF.ImporterContext.LoadGeometryAsync, UniGLTF.ImporterContext.TransferOwnership.
List<string> UniGLTF.ImporterContext.UnsupportedExtensions
Referenced by UniGLTF.ImporterContext.LoadAsync.
GameObject UniGLTF.ImporterContext.Root
Referenced by UniGLTF.ImporterContext.LoadAsync, VRM.VRMImporterContext.LoadBlendShapeMaster, UniGLTF.ImporterContext.LoadGeometryAsync.
UniGLTF.ImporterContext.ImporterContext(GltfData data, IReadOnlyDictionary< SubAssetKey, UnityEngine.Object > externalObjectMap=null, ITextureDeserializer textureDeserializer=null, IMaterialDescriptorGenerator materialGenerator=null)
UnityObject の 生成(LoadAsync) と 破棄(Dispose) を行う。 LoadAsync が成功した場合、返り値(RuntimeGltfInstance) に破棄する責務を移動させる。
data Jsonからデシリアライズされた GLTF 情報など externalObjectMap 外部オブジェクトのリスト(主にScriptedImporterのRemapで使う) textureDeserializer Textureロードをカスタマイズする materialGenerator Materialロードをカスタマイズする(URP向け)
References UniGLTF.ImporterContext.AnimationClipFactory, UniGLTF.ImporterContext.Data, UniGLTF.ImporterContext.ExternalObjectMap, UniGLTF.ImporterContext.MaterialDescriptorGenerator, UniGLTF.ImporterContext.MaterialFactory, UniGLTF.ImporterContext.TextureDescriptorGenerator, UniGLTF.ImporterContext.TextureFactory.
virtual async Task<RuntimeGltfInstance> UniGLTF.ImporterContext.LoadAsync(IAwaitCaller awaitCaller=null, Func< string, IDisposable > MeasureTime=null)
References UniGLTF.glTF.extensionsRequired, UniGLTF.ImporterContext.GLTF, UniGLTF.ImporterContext.LoadAnimationAsync, UniGLTF.ImporterContext.LoadGeometryAsync, UniGLTF.ImporterContext.LoadMaterialsAsync, UniGLTF.ImporterContext.LoadTexturesAsync, UniGLTF.ImporterContext.OnLoadHierarchy, UniGLTF.ImporterContext.Root, UniGLTF.ImporterContext.SetupAnimationsAsync, UniGLTF.ImporterContext.UnsupportedExtensions.
virtual async Task UniGLTF.ImporterContext.LoadAnimationAsync(IAwaitCaller awaitCaller)
References UniGLTF.glTF.animations, UniGLTF.ImporterContext.Data, UniGLTF.ImporterContext.GLTF.
Referenced by UniGLTF.ImporterContext.LoadAsync.
async Task UniGLTF.ImporterContext.LoadTexturesAsync(IAwaitCaller awaitCaller=null)
Referenced by UniGLTF.ImporterContext.LoadAsync.
async Task UniGLTF.ImporterContext.LoadMaterialsAsync(IAwaitCaller awaitCaller=null)
References UniGLTF.ImporterContext.Data, UniGLTF.GltfData.GLTF, UniGLTF.glTF.materials.
Referenced by UniGLTF.ImporterContext.LoadAsync.
virtual void UniGLTF.ImporterContext.Dispose()
ImporterContextが所有する UnityEngine.Object を破棄する
References UniGLTF.ImporterContext.Meshes.
virtual void UniGLTF.ImporterContext.TransferOwnership(TakeResponsibilityForDestroyObjectFunc take)
Root ヒエラルキーで使っているリソース
References UniGLTF.ImporterContext.Meshes.
virtual async Task UniGLTF.ImporterContext.SetupAnimationsAsync(IAwaitCaller awaitCaller)
AnimationClips を AnimationComponent に載せる
References VRMShaders.AnimationClipFactory.LoadedClipKeys.
Referenced by UniGLTF.ImporterContext.LoadAsync.
virtual async Task UniGLTF.ImporterContext.LoadGeometryAsync(IAwaitCaller awaitCaller, Func< string, IDisposable > MeasureTime)
References UniGLTF.ImporterContext.BuildMeshAsync, UniGLTF.ImporterContext.Data, UniGLTF.ImporterContext.GLTF, UniGLTF.glTF.meshes, UniGLTF.ImporterContext.Meshes, UniGLTF.glTF.nodes, UniGLTF.ImporterContext.Nodes, UniGLTF.ImporterContext.Root.
Referenced by UniGLTF.ImporterContext.LoadAsync.
virtual Task UniGLTF.ImporterContext.OnLoadHierarchy(IAwaitCaller awaitCaller, Func< string, IDisposable > MeasureTime)
Referenced by UniGLTF.ImporterContext.LoadAsync.
async Task<MeshWithMaterials> UniGLTF.ImporterContext.BuildMeshAsync(IAwaitCaller awaitCaller, Func< string, IDisposable > MeasureTime, MeshContext x, int i)
Referenced by UniGLTF.ImporterContext.LoadGeometryAsync.