UniGLTF::GltfLoadTests
string [] UniGLTF.GltfLoadTests.Skip
Referenced by UniGLTF.GltfLoadTests.RuntimeLoadExport.
static IEnumerable<FileInfo> UniGLTF.GltfLoadTests.EnumerateGltfFiles(DirectoryInfo dir)
Referenced by UniGLTF.GltfLoadTests.GltfSampleModelsTests.
static void UniGLTF.GltfLoadTests.Message(string path, Exception exception)
Referenced by UniGLTF.GltfLoadTests.RuntimeLoadExport.
static Byte [] UniGLTF.GltfLoadTests.Export(GameObject root)
Referenced by UniGLTF.GltfLoadTests.RuntimeLoadExport.
static void UniGLTF.GltfLoadTests.RuntimeLoadExport(FileInfo gltf, int subStrStart)
References UniGLTF.GltfLoadTests.Export, UniGLTF.GltfLoadTests.Message, UniGLTF.GltfLoadTests.Skip.
Referenced by UniGLTF.GltfLoadTests.GltfSampleModelsTest_BrainStem, UniGLTF.GltfLoadTests.GltfSampleModelsTests.
static void UniGLTF.GltfLoadTests.EditorLoad(FileInfo gltf, int subStrStart)
Extract をテスト
gltf root
Referenced by UniGLTF.GltfLoadTests.GltfSampleModelsTest_BrainStem, UniGLTF.GltfLoadTests.GltfSampleModelsTests.
static bool UniGLTF.GltfLoadTests.Exclude(FileInfo f)
Referenced by UniGLTF.GltfLoadTests.GltfSampleModelsTests.
void UniGLTF.GltfLoadTests.GltfSampleModelsTests()
References UniGLTF.GltfLoadTests.EditorLoad, UniGLTF.GltfLoadTests.EnumerateGltfFiles, UniGLTF.GltfLoadTests.Exclude, UniGLTF.GltfLoadTests.RuntimeLoadExport.
void UniGLTF.GltfLoadTests.GltfSampleModelsTest_BrainStem()
References UniGLTF.GltfLoadTests.EditorLoad, UniGLTF.GltfLoadTests.RuntimeLoadExport.
void UniGLTF.GltfLoadTests.GltfSampleModelsTest_DamagedHelmet()