UniGLTF::GltfSerializer
static void UniGLTF.GltfSerializer.Serialize(JsonFormatter f, glTF value)
References UniGLTF.glTF.accessors, UniGLTF.glTF.animations, UniGLTF.glTF.asset, UniGLTF.glTF.buffers, UniGLTF.glTF.bufferViews, UniGLTF.glTF.cameras, UniGLTF.glTF.extensions, UniGLTF.glTF.extensionsRequired, UniGLTF.glTF.extensionsUsed, UniGLTF.glTF.extras, UniGLTF.glTF.images, UniGLTF.glTF.materials, UniGLTF.glTF.meshes, UniGLTF.glTF.nodes, UniGLTF.glTF.samplers, UniGLTF.glTF.scene, UniGLTF.glTF.scenes, UniGLTF.GltfSerializer.Serialize_gltf_accessors, UniGLTF.GltfSerializer.Serialize_gltf_animations, UniGLTF.GltfSerializer.Serialize_gltf_asset, UniGLTF.GltfSerializer.Serialize_gltf_buffers, UniGLTF.GltfSerializer.Serialize_gltf_bufferViews, UniGLTF.GltfSerializer.Serialize_gltf_cameras, UniGLTF.GltfSerializer.Serialize_gltf_extensionsRequired, UniGLTF.GltfSerializer.Serialize_gltf_extensionsUsed, UniGLTF.GltfSerializer.Serialize_gltf_images, UniGLTF.GltfSerializer.Serialize_gltf_materials, UniGLTF.GltfSerializer.Serialize_gltf_meshes, UniGLTF.GltfSerializer.Serialize_gltf_nodes, UniGLTF.GltfSerializer.Serialize_gltf_samplers, UniGLTF.GltfSerializer.Serialize_gltf_scenes, UniGLTF.GltfSerializer.Serialize_gltf_skins, UniGLTF.GltfSerializer.Serialize_gltf_textures, UniGLTF.glTF.skins, UniGLTF.glTF.textures.
Referenced by UniGLTF.Extensions.VRMC_materials_hdr_emissiveMultiplier.GltfSerializer.Serialize, UniGLTF.Extensions.VRMC_materials_hdr_emissiveMultiplier.GltfSerializer.SerializeTo.
static void UniGLTF.GltfSerializer.Serialize_gltf_asset(JsonFormatter f, glTFAssets value)
References UniGLTF.glTFAssets.copyright, UniGLTF.glTFAssets.extensions, UniGLTF.glTFAssets.extras, UniGLTF.glTFAssets.generator, UniGLTF.glTFAssets.minVersion, UniGLTF.glTFAssets.version.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_buffers(JsonFormatter f, List< glTFBuffer > value)
References UniGLTF.GltfSerializer.Serialize_gltf_buffers_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_buffers_ITEM(JsonFormatter f, glTFBuffer value)
References UniGLTF.glTFBuffer.byteLength, UniGLTF.glTFBuffer.extensions, UniGLTF.glTFBuffer.extras, UniGLTF.glTFBuffer.name, UniGLTF.glTFBuffer.uri.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_buffers.
static void UniGLTF.GltfSerializer.Serialize_gltf_bufferViews(JsonFormatter f, List< glTFBufferView > value)
References UniGLTF.GltfSerializer.Serialize_gltf_bufferViews_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_bufferViews_ITEM(JsonFormatter f, glTFBufferView value)
References UniGLTF.glTFBufferView.buffer, UniGLTF.glTFBufferView.byteLength, UniGLTF.glTFBufferView.byteOffset, UniGLTF.glTFBufferView.byteStride, UniGLTF.glTFBufferView.extensions, UniGLTF.glTFBufferView.extras, UniGLTF.glTFBufferView.name, UniGLTF.glTFBufferView.target.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_bufferViews.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors(JsonFormatter f, List< glTFAccessor > value)
References UniGLTF.GltfSerializer.Serialize_gltf_accessors_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors_ITEM(JsonFormatter f, glTFAccessor value)
References UniGLTF.glTFAccessor.bufferView, UniGLTF.glTFAccessor.byteOffset, UniGLTF.glTFAccessor.componentType, UniGLTF.glTFAccessor.count, UniGLTF.glTFAccessor.extensions, UniGLTF.glTFAccessor.extras, UniGLTF.glTFAccessor.max, UniGLTF.glTFAccessor.min, UniGLTF.glTFAccessor.name, UniGLTF.GltfSerializer.Serialize_gltf_accessors__max, UniGLTF.GltfSerializer.Serialize_gltf_accessors__min, UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse, UniGLTF.glTFAccessor.sparse, UniGLTF.glTFAccessor.type.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors__max(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors__min(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse(JsonFormatter f, glTFSparse value)
References UniGLTF.glTFSparse.count, UniGLTF.glTFSparse.extensions, UniGLTF.glTFSparse.extras, UniGLTF.glTFSparse.indices, UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse_indices, UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse_values, UniGLTF.glTFSparse.values.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse_indices(JsonFormatter f, glTFSparseIndices value)
References UniGLTF.glTFSparseIndices.bufferView, UniGLTF.glTFSparseIndices.byteOffset, UniGLTF.glTFSparseIndices.componentType, UniGLTF.glTFSparseIndices.extensions, UniGLTF.glTFSparseIndices.extras.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse.
static void UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse_values(JsonFormatter f, glTFSparseValues value)
References UniGLTF.glTFSparseValues.bufferView, UniGLTF.glTFSparseValues.byteOffset, UniGLTF.glTFSparseValues.extensions, UniGLTF.glTFSparseValues.extras.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_accessors__sparse.
static void UniGLTF.GltfSerializer.Serialize_gltf_textures(JsonFormatter f, List< glTFTexture > value)
References UniGLTF.GltfSerializer.Serialize_gltf_textures_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_textures_ITEM(JsonFormatter f, glTFTexture value)
References UniGLTF.glTFTexture.extensions, UniGLTF.glTFTexture.extras, UniGLTF.glTFTexture.name, UniGLTF.glTFTexture.sampler, UniGLTF.glTFTexture.source.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_textures.
static void UniGLTF.GltfSerializer.Serialize_gltf_samplers(JsonFormatter f, List< glTFTextureSampler > value)
References UniGLTF.GltfSerializer.Serialize_gltf_samplers_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_samplers_ITEM(JsonFormatter f, glTFTextureSampler value)
References UniGLTF.glTFTextureSampler.extensions, UniGLTF.glTFTextureSampler.extras, UniGLTF.glTFTextureSampler.magFilter, UniGLTF.glTFTextureSampler.minFilter, UniGLTF.glTFTextureSampler.name, UniGLTF.glTFTextureSampler.wrapS, UniGLTF.glTFTextureSampler.wrapT.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_samplers.
static void UniGLTF.GltfSerializer.Serialize_gltf_images(JsonFormatter f, List< glTFImage > value)
References UniGLTF.GltfSerializer.Serialize_gltf_images_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_images_ITEM(JsonFormatter f, glTFImage value)
References UniGLTF.glTFImage.bufferView, UniGLTF.glTFImage.extensions, UniGLTF.glTFImage.extras, UniGLTF.glTFImage.mimeType, UniGLTF.glTFImage.name, UniGLTF.glTFImage.uri.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_images.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials(JsonFormatter f, List< glTFMaterial > value)
References UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM(JsonFormatter f, glTFMaterial value)
References UniGLTF.glTFMaterial.alphaCutoff, UniGLTF.glTFMaterial.alphaMode, UniGLTF.glTFMaterial.emissiveFactor, UniGLTF.glTFMaterial.emissiveTexture, UniGLTF.glTFMaterial.extensions, UniGLTF.glTFMaterial.extras, UniGLTF.glTFMaterial.name, UniGLTF.glTFMaterial.normalTexture, UniGLTF.glTFMaterial.occlusionTexture, UniGLTF.glTFMaterial.pbrMetallicRoughness, UniGLTF.GltfSerializer.Serialize_gltf_materials__emissiveFactor, UniGLTF.GltfSerializer.Serialize_gltf_materials__emissiveTexture, UniGLTF.GltfSerializer.Serialize_gltf_materials__normalTexture, UniGLTF.GltfSerializer.Serialize_gltf_materials__occlusionTexture, UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness(JsonFormatter f, glTFPbrMetallicRoughness value)
References UniGLTF.glTFPbrMetallicRoughness.baseColorFactor, UniGLTF.glTFPbrMetallicRoughness.baseColorTexture, UniGLTF.glTFPbrMetallicRoughness.extensions, UniGLTF.glTFPbrMetallicRoughness.extras, UniGLTF.glTFPbrMetallicRoughness.metallicFactor, UniGLTF.glTFPbrMetallicRoughness.metallicRoughnessTexture, UniGLTF.glTFPbrMetallicRoughness.roughnessFactor, UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_baseColorFactor, UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_baseColorTexture, UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_baseColorTexture(JsonFormatter f, glTFMaterialBaseColorTextureInfo value)
References UniGLTF.glTFTextureInfo.extensions, UniGLTF.glTFTextureInfo.extras, UniGLTF.glTFTextureInfo.index, UniGLTF.glTFTextureInfo.texCoord.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_baseColorFactor(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture(JsonFormatter f, glTFMaterialMetallicRoughnessTextureInfo value)
References UniGLTF.glTFTextureInfo.extensions, UniGLTF.glTFTextureInfo.extras, UniGLTF.glTFTextureInfo.index, UniGLTF.glTFTextureInfo.texCoord.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials__pbrMetallicRoughness.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__normalTexture(JsonFormatter f, glTFMaterialNormalTextureInfo value)
References UniGLTF.glTFTextureInfo.extensions, UniGLTF.glTFTextureInfo.extras, UniGLTF.glTFTextureInfo.index, UniGLTF.glTFTextureInfo.texCoord.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__occlusionTexture(JsonFormatter f, glTFMaterialOcclusionTextureInfo value)
References UniGLTF.glTFTextureInfo.extensions, UniGLTF.glTFTextureInfo.extras, UniGLTF.glTFTextureInfo.index, UniGLTF.glTFMaterialOcclusionTextureInfo.strength, UniGLTF.glTFTextureInfo.texCoord.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__emissiveTexture(JsonFormatter f, glTFMaterialEmissiveTextureInfo value)
References UniGLTF.glTFTextureInfo.extensions, UniGLTF.glTFTextureInfo.extras, UniGLTF.glTFTextureInfo.index, UniGLTF.glTFTextureInfo.texCoord.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_materials__emissiveFactor(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_materials_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes(JsonFormatter f, List< glTFMesh > value)
References UniGLTF.GltfSerializer.Serialize_gltf_meshes_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes_ITEM(JsonFormatter f, glTFMesh value)
References UniGLTF.glTFMesh.extensions, UniGLTF.glTFMesh.extras, UniGLTF.glTFMesh.name, UniGLTF.glTFMesh.primitives, UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives, UniGLTF.GltfSerializer.Serialize_gltf_meshes__weights, UniGLTF.glTFMesh.weights.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives(JsonFormatter f, List< glTFPrimitives > value)
References UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives_ITEM(JsonFormatter f, glTFPrimitives value)
References UniGLTF.glTFPrimitives.attributes, UniGLTF.glTFPrimitives.extensions, UniGLTF.glTFPrimitives.extras, UniGLTF.glTFPrimitives.indices, UniGLTF.glTFPrimitives.material, UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__attributes, UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__targets, UniGLTF.glTFPrimitives.targets.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__attributes(JsonFormatter f, glTFAttributes value)
References UniGLTF.glTFAttributes.COLOR_0, UniGLTF.glTFAttributes.JOINTS_0, UniGLTF.glTFAttributes.NORMAL, UniGLTF.glTFAttributes.POSITION, UniGLTF.glTFAttributes.TANGENT, UniGLTF.glTFAttributes.TEXCOORD_0, UniGLTF.glTFAttributes.TEXCOORD_1, UniGLTF.glTFAttributes.WEIGHTS_0.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__targets(JsonFormatter f, List< gltfMorphTarget > value)
References UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__targets_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__targets_ITEM(JsonFormatter f, gltfMorphTarget value)
References UniGLTF.gltfMorphTarget.NORMAL, UniGLTF.gltfMorphTarget.POSITION, UniGLTF.gltfMorphTarget.TANGENT.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes__primitives__targets.
static void UniGLTF.GltfSerializer.Serialize_gltf_meshes__weights(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_meshes_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes(JsonFormatter f, List< glTFNode > value)
References UniGLTF.GltfSerializer.Serialize_gltf_nodes_ITEM.
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes_ITEM(JsonFormatter f, glTFNode value)
References UniGLTF.glTFNode.children, UniGLTF.glTFNode.matrix, UniGLTF.glTFNode.name, UniGLTF.GltfSerializer.Serialize_gltf_nodes__children, UniGLTF.GltfSerializer.Serialize_gltf_nodes__matrix, UniGLTF.glTFNode.translation.
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_nodes.
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__children(JsonFormatter f, Int32[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_nodes_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__matrix(JsonFormatter f, Single[] value)
Referenced by UniGLTF.GltfSerializer.Serialize_gltf_nodes_ITEM.
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__translation(JsonFormatter f, Single[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__rotation(JsonFormatter f, Single[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__scale(JsonFormatter f, Single[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_nodes__weights(JsonFormatter f, Single[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_skins(JsonFormatter f, List< glTFSkin > value)
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_skins_ITEM(JsonFormatter f, glTFSkin value)
References UniGLTF.glTFSkin.extensions, UniGLTF.glTFSkin.extras, UniGLTF.glTFSkin.inverseBindMatrices, UniGLTF.glTFSkin.joints, UniGLTF.glTFSkin.name, UniGLTF.glTFSkin.skeleton.
static void UniGLTF.GltfSerializer.Serialize_gltf_skins__joints(JsonFormatter f, Int32[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_scenes(JsonFormatter f, List< gltfScene > value)
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_scenes_ITEM(JsonFormatter f, gltfScene value)
References UniGLTF.gltfScene.extensions, UniGLTF.gltfScene.extras, UniGLTF.gltfScene.name, UniGLTF.gltfScene.nodes.
static void UniGLTF.GltfSerializer.Serialize_gltf_scenes__nodes(JsonFormatter f, Int32[] value)
static void UniGLTF.GltfSerializer.Serialize_gltf_animations(JsonFormatter f, List< glTFAnimation > value)
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_animations_ITEM(JsonFormatter f, glTFAnimation value)
References UniGLTF.glTFAnimation.channels, UniGLTF.glTFAnimation.extensions, UniGLTF.glTFAnimation.extras, UniGLTF.glTFAnimation.name, UniGLTF.glTFAnimation.samplers.
static void UniGLTF.GltfSerializer.Serialize_gltf_animations__channels(JsonFormatter f, List< glTFAnimationChannel > value)
static void UniGLTF.GltfSerializer.Serialize_gltf_animations__channels_ITEM(JsonFormatter f, glTFAnimationChannel value)
References UniGLTF.glTFAnimationChannel.extensions, UniGLTF.glTFAnimationChannel.extras, UniGLTF.glTFAnimationChannel.sampler, UniGLTF.glTFAnimationChannel.target.
static void UniGLTF.GltfSerializer.Serialize_gltf_animations__channels__target(JsonFormatter f, glTFAnimationTarget value)
References UniGLTF.glTFAnimationTarget.extensions, UniGLTF.glTFAnimationTarget.extras, UniGLTF.glTFAnimationTarget.node, UniGLTF.glTFAnimationTarget.path.
static void UniGLTF.GltfSerializer.Serialize_gltf_animations__samplers(JsonFormatter f, List< glTFAnimationSampler > value)
static void UniGLTF.GltfSerializer.Serialize_gltf_animations__samplers_ITEM(JsonFormatter f, glTFAnimationSampler value)
References UniGLTF.glTFAnimationSampler.extensions, UniGLTF.glTFAnimationSampler.extras, UniGLTF.glTFAnimationSampler.input, UniGLTF.glTFAnimationSampler.interpolation, UniGLTF.glTFAnimationSampler.output.
static void UniGLTF.GltfSerializer.Serialize_gltf_cameras(JsonFormatter f, List< glTFCamera > value)
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_cameras_ITEM(JsonFormatter f, glTFCamera value)
References UniGLTF.glTFCamera.extensions, UniGLTF.glTFCamera.extras, UniGLTF.glTFCamera.name, UniGLTF.glTFCamera.orthographic, UniGLTF.glTFCamera.perspective.
static void UniGLTF.GltfSerializer.Serialize_gltf_cameras__orthographic(JsonFormatter f, glTFOrthographic value)
References UniGLTF.glTFOrthographic.extensions, UniGLTF.glTFOrthographic.extras, UniGLTF.glTFOrthographic.zfar, UniGLTF.glTFOrthographic.znear.
static void UniGLTF.GltfSerializer.Serialize_gltf_cameras__perspective(JsonFormatter f, glTFPerspective value)
References UniGLTF.glTFPerspective.aspectRatio, UniGLTF.glTFPerspective.extensions, UniGLTF.glTFPerspective.extras, UniGLTF.glTFPerspective.yfov, UniGLTF.glTFPerspective.zfar, UniGLTF.glTFPerspective.znear.
static void UniGLTF.GltfSerializer.Serialize_gltf_extensionsUsed(JsonFormatter f, List< String > value)
Referenced by UniGLTF.GltfSerializer.Serialize.
static void UniGLTF.GltfSerializer.Serialize_gltf_extensionsRequired(JsonFormatter f, List< String > value)
Referenced by UniGLTF.GltfSerializer.Serialize.