VRMShaders::TextureExporter
readonly ITextureSerializer VRMShaders.TextureExporter._textureSerializer
Referenced by VRMShaders.TextureExporter.RegisterExportingAsCombinedGltfPbrParameterTextureFromUnityStandardTextures, VRMShaders.TextureExporter.TextureExporter.
readonly List<TextureExportParam> VRMShaders.TextureExporter._exportingList
Referenced by VRMShaders.TextureExporter.Export, VRMShaders.TextureExporter.RegisterExportingSimple.
VRMShaders.TextureExporter.TextureExporter(ITextureSerializer textureSerializer)
References VRMShaders.TextureExporter._textureSerializer.
void VRMShaders.TextureExporter.Dispose()
List<(Texture2D, ColorSpace)> VRMShaders.TextureExporter.Export()
実際にテクスチャを変換する
References VRMShaders.TextureExporter._exportingList.
int VRMShaders.TextureExporter.RegisterExportingAsSRgb(Texture src, bool needsAlpha)
指定の Texture を、 sRGB 色空間の値を持つ Texture に出力するように指示する。
References VRMShaders.TextureExporter.RegisterExportingSimple.
int VRMShaders.TextureExporter.RegisterExportingAsLinear(Texture src, bool needsAlpha)
指定の Texture を、 Linear の値を持つ Texture に出力するように指示する。
References VRMShaders.TextureExporter.RegisterExportingSimple.
int VRMShaders.TextureExporter.RegisterExportingAsCombinedGltfPbrParameterTextureFromUnityStandardTextures(Texture metallicSmoothTexture, float smoothness, Texture occlusionTexture)
Unity Standard Shader の Metallic, Roughness, Occlusion 情報を、 glTF 仕様に準拠した 1 枚の合成テクスチャとして出力するように指示する。
References VRMShaders.TextureExporter._textureSerializer, VRMShaders.ITextureSerializer.ModifyTextureAssetBeforeExporting.
int VRMShaders.TextureExporter.RegisterExportingAsNormal(Texture src)
指定の Texture を、glTF 仕様に準拠した Normal Texture に出力するように指示する。
int VRMShaders.TextureExporter.RegisterExportingSimple(Texture src, bool needsAlpha, bool isLinear)
References VRMShaders.TextureExporter._exportingList, VRMShaders.TextureExporter.ConvertTextureSimple, VRMShaders.TextureExporter.TryGetExistsParam.
Referenced by VRMShaders.TextureExporter.RegisterExportingAsLinear, VRMShaders.TextureExporter.RegisterExportingAsSRgb.
Texture2D VRMShaders.TextureExporter.ConvertTextureSimple(Texture src, bool needsAlpha, ColorSpace exportColorSpace)
Referenced by VRMShaders.TextureExporter.RegisterExportingSimple.
bool VRMShaders.TextureExporter.TryGetExistsParam(TextureExportParam param, out int existsIdx)
Referenced by VRMShaders.TextureExporter.RegisterExportingSimple.