VRM::VRMMToonTextureImporter
static IEnumerable<(SubAssetKey, TextureDescriptor)> VRM.VRMMToonTextureImporter.EnumerateAllTextures(GltfData data, glTF_VRM_extensions vrm, int materialIdx)
References VRM.VRMMToonTextureImporter.TryGetTextureFromMaterialProperty.
Referenced by VRM.VrmTextureDescriptorGenerator.EnumerateAllTextures.
static bool VRM.VRMMToonTextureImporter.TryGetTextureFromMaterialProperty(GltfData data, glTF_VRM_Material vrmMaterial, string textureKey, out(SubAssetKey, TextureDescriptor) texture)
References VRM.glTF_VRM_Material.textureProperties, VRM.VRMMToonTextureImporter.TryGetTextureOffsetAndScale.
Referenced by VRM.VRMMToonTextureImporter.EnumerateAllTextures, VRM.VRMMToonMaterialImporter.TryCreateParam, VRM.VRMUnlitTransparentZWriteMaterialImporter.TryCreateParam.
static bool VRM.VRMMToonTextureImporter.TryGetTextureOffsetAndScale(glTF_VRM_Material vrmMaterial, string unityTextureKey, out(Vector2 offset, Vector2 scale) os)
References VRM.glTF_VRM_Material.vectorProperties.
Referenced by VRM.VRMMToonTextureImporter.TryGetTextureFromMaterialProperty.