UniJSON::JsonString
static void UniJSON.JsonString.Escape(String s, IStore w)
References UniJSON.String.
Referenced by UniJSON.JsonString.Escape, UniJSON.JsonString.Quote.
static void UniJSON.JsonString.Escape(Utf8String s, IStore w)
References UniJSON.Utf8String.IsEmpty.
static string UniJSON.JsonString.Escape(String s)
References UniJSON.JsonString.Escape.
static void UniJSON.JsonString.Quote(String s, IStore w)
References UniJSON.JsonString.Escape.
Referenced by UniJSON.JsonValue.Key, UniJSON.JsonString.Quote.
static void UniJSON.JsonString.Quote(Utf8String s, IStore w)
References UniJSON.JsonString.Escape.
static string UniJSON.JsonString.Quote(string s)
Added " and Escape
s w
References UniJSON.JsonString.Quote.
static Utf8String UniJSON.JsonString.Quote(Utf8String s)
References UniJSON.Utf8String.ByteLength, UniJSON.JsonString.Quote.
static int UniJSON.JsonString.Unescape(string src, IStore w)
References UniJSON.JsonString.CheckHex.
Referenced by UniJSON.JsonString.Unescape, UniJSON.JsonString.Unquote.
static int UniJSON.JsonString.Unescape(Utf8String s, IStore w)
References UniJSON.JsonString.CheckHex.
static string UniJSON.JsonString.Unescape(string src)
References UniJSON.JsonString.Unescape.
static int UniJSON.JsonString.Unquote(string src, IStore w)
References UniJSON.JsonString.Unescape.
Referenced by UniJSON.JsonString.Unquote.
static int UniJSON.JsonString.Unquote(Utf8String src, IStore w)
References UniJSON.Utf8String.ByteLength, UniJSON.Utf8String.Subbytes, UniJSON.JsonString.Unescape.
static string UniJSON.JsonString.Unquote(string src)
References UniJSON.JsonString.Unquote.
static Utf8String UniJSON.JsonString.Unquote(Utf8String src)
References UniJSON.Utf8String.ByteLength, UniJSON.JsonString.Unquote.
static byte UniJSON.JsonString.CheckHex(int b)
Referenced by UniJSON.JsonString.Unescape.