VRM::SerializedBlendShapeEditor
BlendShapeClip VRM.SerializedBlendShapeEditor.m_targetObject
Referenced by VRM.SerializedBlendShapeEditor.Draw.
SerializedObject VRM.SerializedBlendShapeEditor.m_serializedObject
SerializedProperty VRM.SerializedBlendShapeEditor.m_thumbnail
SerializedProperty VRM.SerializedBlendShapeEditor.m_blendShapeNameProp
Referenced by VRM.SerializedBlendShapeEditor.Draw, VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
SerializedProperty VRM.SerializedBlendShapeEditor.m_presetProp
Referenced by VRM.SerializedBlendShapeEditor.Draw, VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
SerializedProperty VRM.SerializedBlendShapeEditor.m_isBinaryProp
Referenced by VRM.SerializedBlendShapeEditor.Draw, VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
ReorderableList VRM.SerializedBlendShapeEditor.m_ValuesList
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
SerializedProperty VRM.SerializedBlendShapeEditor.m_valuesProp
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
const int VRM.SerializedBlendShapeEditor.MaterialValueBindingHeight
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
ReorderableList VRM.SerializedBlendShapeEditor.m_MaterialValuesList
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
SerializedProperty VRM.SerializedBlendShapeEditor.m_materialsProp
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
bool VRM.SerializedBlendShapeEditor.m_changed
Referenced by VRM.SerializedBlendShapeEditor.ClipGUI, VRM.SerializedBlendShapeEditor.Draw, VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
int VRM.SerializedBlendShapeEditor.m_mode
Referenced by VRM.SerializedBlendShapeEditor.Draw.
MeshPreviewItem [] VRM.SerializedBlendShapeEditor.m_items
Referenced by VRM.SerializedBlendShapeEditor.BlendShapeBindsGUI, VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
List<bool> VRM.SerializedBlendShapeEditor.m_meshFolds
Referenced by VRM.SerializedBlendShapeEditor.BlendShapeBindsGUI.
int VRM.SerializedBlendShapeEditor.BlendShapeBindingHeight
Referenced by VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor.
string [] VRM.SerializedBlendShapeEditor.MODES
Referenced by VRM.SerializedBlendShapeEditor.Draw.
VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor(SerializedObject serializedObject, PreviewSceneManager previewSceneManager)
VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor(BlendShapeClip blendShapeClip, PreviewSceneManager previewSceneManager)
VRM.SerializedBlendShapeEditor.SerializedBlendShapeEditor(SerializedObject serializedObject, BlendShapeClip targetObject, PreviewSceneManager previewSceneManager)
References VRM.SerializedBlendShapeEditor.BlendShapeBindingHeight, VRM.BlendShapeClipEditorHelper.DrawBlendShapeBinding, VRM.BlendShapeClipEditorHelper.DrawMaterialValueBinding, VRM.SerializedBlendShapeEditor.m_blendShapeNameProp, VRM.SerializedBlendShapeEditor.m_changed, VRM.SerializedBlendShapeEditor.m_isBinaryProp, VRM.SerializedBlendShapeEditor.m_items, VRM.SerializedBlendShapeEditor.m_materialsProp, VRM.SerializedBlendShapeEditor.m_MaterialValuesList, VRM.SerializedBlendShapeEditor.m_presetProp, VRM.SerializedBlendShapeEditor.m_ValuesList, VRM.SerializedBlendShapeEditor.m_valuesProp, VRM.SerializedBlendShapeEditor.MaterialValueBindingHeight.
DrawResult VRM.SerializedBlendShapeEditor.Draw()
References VRM.SerializedBlendShapeEditor.ClipGUI, VRM.SerializedBlendShapeEditor.m_blendShapeNameProp, VRM.SerializedBlendShapeEditor.m_changed, VRM.SerializedBlendShapeEditor.m_isBinaryProp, VRM.SerializedBlendShapeEditor.m_mode, VRM.SerializedBlendShapeEditor.m_presetProp, VRM.SerializedBlendShapeEditor.m_targetObject, VRM.SerializedBlendShapeEditor.MODES.
void VRM.SerializedBlendShapeEditor.ClipGUI()
References VRM.SerializedBlendShapeEditor.BlendShapeBindsGUI, VRM.SerializedBlendShapeEditor.GetBindings, VRM.SerializedBlendShapeEditor.m_changed.
Referenced by VRM.SerializedBlendShapeEditor.Draw.
bool VRM.SerializedBlendShapeEditor.BlendShapeBindsGUI()
References VRM.SerializedBlendShapeEditor.m_items, VRM.SerializedBlendShapeEditor.m_meshFolds.
Referenced by VRM.SerializedBlendShapeEditor.ClipGUI.
BlendShapeBinding [] VRM.SerializedBlendShapeEditor.GetBindings(out string _maxWeightName)
Referenced by VRM.SerializedBlendShapeEditor.ClipGUI.