UniGLTF::EditorTextureSerializerTests
readonly string UniGLTF.EditorTextureSerializerTests.AssetPath
readonly string UniGLTF.EditorTextureSerializerTests.SrgbGrayImageName
Referenced by UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty.
readonly string UniGLTF.EditorTextureSerializerTests.LinearGrayImageName
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty.
readonly string UniGLTF.EditorTextureSerializerTests.NormalMapGrayImageName
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty.
readonly Texture2D UniGLTF.EditorTextureSerializerTests.SrgbGrayTex
Referenced by UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture, UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture, UniGLTF.EditorTextureSerializerTests.InputAssetsRawImage.
readonly Texture2D UniGLTF.EditorTextureSerializerTests.LinearGrayTex
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture, UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture, UniGLTF.EditorTextureSerializerTests.InputAssetsRawImage.
readonly Texture2D UniGLTF.EditorTextureSerializerTests.NormalMapGrayTex
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty.
readonly Color32 UniGLTF.EditorTextureSerializerTests.JustGray
readonly Color32 UniGLTF.EditorTextureSerializerTests.SrgbGrayInSrgb
Referenced by UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture, UniGLTF.EditorTextureSerializerTests.InputAssetsRawImage.
readonly Color32 UniGLTF.EditorTextureSerializerTests.SrgbGrayInLinear
Referenced by UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture.
readonly Color32 UniGLTF.EditorTextureSerializerTests.LinearGrayInLinear
Referenced by UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture.
readonly Color32 UniGLTF.EditorTextureSerializerTests.LinearGrayInSrgb
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture.
readonly Color32 UniGLTF.EditorTextureSerializerTests.NormalizedLinearGrayInLinear
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty.
void UniGLTF.EditorTextureSerializerTests.InputAssetsRawImage()
References UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.LinearGrayTex, UniGLTF.EditorTextureSerializerTests.SrgbGrayInSrgb, UniGLTF.EditorTextureSerializerTests.SrgbGrayTex.
void UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture()
References UniGLTF.EditorTextureSerializerTests.GetFirstPixelInRenderTexture, UniGLTF.EditorTextureSerializerTests.LinearGrayInSrgb, UniGLTF.EditorTextureSerializerTests.LinearGrayTex, UniGLTF.EditorTextureSerializerTests.SrgbGrayInSrgb, UniGLTF.EditorTextureSerializerTests.SrgbGrayTex.
void UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture()
References UniGLTF.EditorTextureSerializerTests.GetFirstPixelInRenderTexture, UniGLTF.EditorTextureSerializerTests.LinearGrayInLinear, UniGLTF.EditorTextureSerializerTests.LinearGrayTex, UniGLTF.EditorTextureSerializerTests.SrgbGrayInLinear, UniGLTF.EditorTextureSerializerTests.SrgbGrayTex.
void UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.SrgbGrayImageName, UniGLTF.EditorTextureSerializerTests.SrgbGrayInSrgb, UniGLTF.EditorTextureSerializerTests.SrgbGrayTex.
void UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.LinearGrayImageName, UniGLTF.EditorTextureSerializerTests.LinearGrayInSrgb, UniGLTF.EditorTextureSerializerTests.LinearGrayTex.
void UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToLinearTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.SrgbGrayImageName, UniGLTF.EditorTextureSerializerTests.SrgbGrayTex.
void UniGLTF.EditorTextureSerializerTests.AssignLinearImageToLinearTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.LinearGrayImageName, UniGLTF.EditorTextureSerializerTests.LinearGrayTex.
void UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.LinearGrayImageName, UniGLTF.EditorTextureSerializerTests.LinearGrayTex, UniGLTF.EditorTextureSerializerTests.NormalizedLinearGrayInLinear.
void UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty()
References UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D, UniGLTF.EditorTextureSerializerTests.NormalizedLinearGrayInLinear, UniGLTF.EditorTextureSerializerTests.NormalMapGrayImageName, UniGLTF.EditorTextureSerializerTests.NormalMapGrayTex.
static Texture2D UniGLTF.EditorTextureSerializerTests.AssignTextureToMaterialPropertyAndExportAndExtract(Texture2D srcTex, string srcImageName, string propertyName)
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty.
static Color32 UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D(Texture2D tex)
Referenced by UniGLTF.EditorTextureSerializerTests.AssignLinearImageAsNormalMapSettingsToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToNormalTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignLinearImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToLinearTextureProperty, UniGLTF.EditorTextureSerializerTests.AssignSrgbImageToSrgbTextureProperty, UniGLTF.EditorTextureSerializerTests.GetFirstPixelInRenderTexture, UniGLTF.EditorTextureSerializerTests.InputAssetsRawImage.
static Color32 UniGLTF.EditorTextureSerializerTests.GetFirstPixelInRenderTexture(RenderTexture rt)
References UniGLTF.EditorTextureSerializerTests.GetFirstPixelInTexture2D.
Referenced by UniGLTF.EditorTextureSerializerTests.CopyToLinearRenderTexture, UniGLTF.EditorTextureSerializerTests.CopyToSrgbRenderTexture.