VRM::VRMVersionMenu
string VRM.VRMVersionMenu.UniGltfVersionPath
UNIGLTF
Referenced by VRM.VRMVersionMenu.UpdateUniGLTFVersion.
const string VRM.VRMVersionMenu.UniGltfVersionTemplate
Referenced by VRM.VRMVersionMenu.UpdateUniGLTFVersion.
const string VRM.VRMVersionMenu.VrmVersionPath
VRM
Referenced by VRM.VRMVersionMenu.UpdateVrmVersion.
const string VRM.VRMVersionMenu.VrmVersionTemplate
Referenced by VRM.VRMVersionMenu.UpdateVrmVersion.
UpmPackage [] VRM.VRMVersionMenu.Packages
Referenced by VRM.VRMVersionMenu.UpdateVrmVersion.
UpmPackage VRM.VRMVersionMenu.UniGLTFPackage
string VRM.VRMVersionMenu.m_vrmVersion
Referenced by VRM.VRMVersionMenu.OnGUI.
VRM.VRMVersionMenu.int
int VRM.VRMVersionMenu.m_uniGltfVersion
Referenced by VRM.VRMVersionMenu.OnGUI.
static bool VRM.VRMVersionMenu.TryGetVersion(string src, out(int, int, int) version)
Referenced by VRM.VRMVersionMenu.OnGUI.
void VRM.VRMVersionMenu.OnGUI()
バージョン管理ダイアログ
References VRM.VRMVersionMenu.m_uniGltfVersion, VRM.VRMVersionMenu.m_vrmVersion, VRM.VRMVersionMenu.TryGetVersion, VRM.VRMVersionMenu.UpdateUniGLTFVersion, VRM.VRMVersionMenu.UpdateVrmVersion.
void VRM.VRMVersionMenu.UpdateUniGLTFVersion((int, int, int) uniGltf,(int, int, int) vrm)
References VRM.VRMVersionMenu.UniGltfVersionPath, VRM.VRMVersionMenu.UniGltfVersionTemplate.
Referenced by VRM.VRMVersionMenu.OnGUI.
void VRM.VRMVersionMenu.UpdateVrmVersion((int, int, int) vrm)
References VRM.VRMVersionMenu.Packages, VRM.VRMVersionMenu.VrmVersionPath, VRM.VRMVersionMenu.VrmVersionTemplate.
Referenced by VRM.VRMVersionMenu.OnGUI.
static void VRM.VRMVersionMenu.ShowVersionDialog()
References VRM.VRMVersion.VERSION.