GenerateUniGLTFSerialization::Generator
static void GenerateUniGLTFSerialization.Generator.DeleteAllInDirectory(DirectoryInfo dir)
Referenced by GenerateUniGLTFSerialization.Generator.CleanDirectory.
static void GenerateUniGLTFSerialization.Generator.CleanDirectory(DirectoryInfo dir)
References GenerateUniGLTFSerialization.Generator.DeleteAllInDirectory.
Referenced by GenerateUniGLTFSerialization.Generator.GenerateTo.
static string GenerateUniGLTFSerialization.Generator.CleanupTitle(string title)
Referenced by GenerateUniGLTFSerialization.Generator.GenerateTo.
static string GenerateUniGLTFSerialization.Generator.GetStem(string filename)
Referenced by GenerateUniGLTFSerialization.Generator.GenerateTo.
static void GenerateUniGLTFSerialization.Generator.WriteAllTextForce(string path, string contents)
Referenced by GenerateUniGLTFSerialization.Generator.GenerateTo.
static void GenerateUniGLTFSerialization.Generator.GenerateTo(JsonSchemaSource root, DirectoryInfo formatDir, DirectoryInfo serializerDir)
References GenerateUniGLTFSerialization.Generator.CleanDirectory, GenerateUniGLTFSerialization.Generator.CleanupTitle, GenerateUniGLTFSerialization.Generator.GetStem, GenerateUniGLTFSerialization.Generator.WriteAllTextForce.