UniGLTF::RemapScriptedImporterEditorBase
ScriptedImporter UniGLTF.RemapScriptedImporterEditorBase.m_importer
Referenced by UniGLTF.GltfScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnEnable, UniGLTF.GlbScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnInspectorGUI, UniGLTF.GltfScriptedImporterEditor.OnInspectorGUI, UniGLTF.GlbScriptedImporterEditor.OnInspectorGUI.
List<RemapEditorBase.SubAssetPair> UniGLTF.RemapScriptedImporterEditorBase.m_editMap
Apply されていない変更を保持する
Undo SubAssetKey UnityEngine.Object
Referenced by UniGLTF.RemapScriptedImporterEditorBase.Apply, UniGLTF.RemapScriptedImporterEditorBase.HasModified.
Dictionary<SubAssetKey, UnityEngine.Object> UniGLTF.RemapScriptedImporterEditorBase.GetEditorMap()
Referenced by UniGLTF.GltfScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnEnable, UniGLTF.GlbScriptedImporterEditor.OnEnable.
void UniGLTF.RemapScriptedImporterEditorBase.SetEditorMap(Dictionary< SubAssetKey, UnityEngine.Object > value)
Referenced by UniGLTF.GltfScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnEnable, UniGLTF.GlbScriptedImporterEditor.OnEnable.
override void UniGLTF.RemapScriptedImporterEditorBase.ResetValues()
Revert
override void UniGLTF.RemapScriptedImporterEditorBase.Apply()
Apply
References UniGLTF.RemapScriptedImporterEditorBase.m_editMap.
override bool UniGLTF.RemapScriptedImporterEditorBase.HasModified()
References UniGLTF.RemapScriptedImporterEditorBase.m_editMap.