UniHumanoid::Bvh
BvhNode UniHumanoid.Bvh.Root
Referenced by UniHumanoid.Bvh.Bvh, UniHumanoid.BvhSkeletonEstimator.Detect, UniHumanoid.Bvh.GetChannel, UniHumanoid.Bvh.GetParent, UniHumanoid.BvhImporterContext.Load, UniHumanoid.Bvh.TryGetPathWithPropertyFromChannel.
TimeSpan UniHumanoid.Bvh.FrameTime
Referenced by UniHumanoid.BvhAnimation.CurveSet.AddCurve, UniHumanoid.BvhAnimation.CurveSet.AddCurves, UniHumanoid.Bvh.Bvh.
ChannelCurve [] UniHumanoid.Bvh.Channels
Referenced by UniHumanoid.Bvh.Bvh, UniHumanoid.Bvh.GetChannel, UniHumanoid.Bvh.ParseFrame.
int UniHumanoid.Bvh.FrameCount
int UniHumanoid.Bvh.m_frames
Referenced by UniHumanoid.Bvh.Bvh, UniHumanoid.Bvh.ToString.
bool UniHumanoid.Bvh.TryGetPathWithPropertyFromChannel(ChannelCurve channel, out PathWithProperty pathWithProp)
References UniHumanoid.Bvh.GetPath, UniHumanoid.Bvh.Root, UniHumanoid.BvhNode.Traverse.
string UniHumanoid.Bvh.GetPath(BvhNode node)
References UniHumanoid.Bvh.GetParent.
Referenced by UniHumanoid.Bvh.TryGetPathWithPropertyFromChannel.
ChannelCurve UniHumanoid.Bvh.GetChannel(BvhNode target, Channel channel)
References UniHumanoid.Bvh.Channels, UniHumanoid.Bvh.Root, UniHumanoid.BvhNode.Traverse.
override string UniHumanoid.Bvh.ToString()
References UniHumanoid.Bvh.m_frames.
UniHumanoid.Bvh.Bvh(BvhNode root, int frames, float seconds)
References UniHumanoid.Bvh.Channels, UniHumanoid.Bvh.FrameTime, UniHumanoid.Bvh.m_frames, UniHumanoid.Bvh.Root.
Referenced by UniHumanoid.Bvh.Parse.
void UniHumanoid.Bvh.ParseFrame(int frame, string line)
References UniHumanoid.Bvh.Channels.
BvhNode UniHumanoid.Bvh.GetParent(BvhNode node)
References UniHumanoid.Bvh.Root, UniHumanoid.BvhNode.Traverse.
Referenced by UniHumanoid.Bvh.GetPath.
static Bvh UniHumanoid.Bvh.Parse(string src)
References UniHumanoid.Bvh.Bvh, UniHumanoid.Bvh.ParseNode.
static BvhNode UniHumanoid.Bvh.ParseNode(StringReader r, int level=0)
Referenced by UniHumanoid.Bvh.Parse.