UniHumanoid::BvhNode
String UniHumanoid.BvhNode.Name
Referenced by UniHumanoid.BvhImporterContext.BuildHierarchy, UniHumanoid.BvhNode.BvhNode, UniHumanoid.BvhSkeletonEstimator.Detect.
Single3 UniHumanoid.BvhNode.Offset
Referenced by UniHumanoid.BvhNode.Parse.
Channel [] UniHumanoid.BvhNode.Channels
Referenced by UniHumanoid.BvhNode.Parse.
List<BvhNode> UniHumanoid.BvhNode.Children
Referenced by UniHumanoid.BvhNode.BvhNode, UniHumanoid.BvhNode.Traverse.
UniHumanoid.BvhNode.BvhNode(string name)
References UniHumanoid.BvhNode.Children, UniHumanoid.BvhNode.Name.
virtual void UniHumanoid.BvhNode.Parse(StringReader r)
References UniHumanoid.BvhNode.Channels, UniHumanoid.BvhNode.Offset, UniHumanoid.BvhNode.ParseChannel, UniHumanoid.BvhNode.ParseOffset.
Referenced by UniHumanoid.BvhNode.ParseOffset.
IEnumerable<BvhNode> UniHumanoid.BvhNode.Traverse()
References UniHumanoid.BvhNode.Children.
Referenced by UniHumanoid.Bvh.GetChannel, UniHumanoid.Bvh.GetParent, UniHumanoid.Bvh.TryGetPathWithPropertyFromChannel.
static Single3 UniHumanoid.BvhNode.ParseOffset(string line)
References UniHumanoid.BvhNode.Parse.
Referenced by UniHumanoid.BvhNode.Parse.
static Channel [] UniHumanoid.BvhNode.ParseChannel(string line)
Referenced by UniHumanoid.BvhNode.Parse.