UniGLTF::GltfData
string UniGLTF.GltfData.TargetPath
Source file path. Maybe empty if source file was on memory.
Referenced by UniGLTF.GltfData.GltfData.
IReadOnlyList<GlbChunk> UniGLTF.GltfData.Chunks
Chunk Data. Maybe empty if source file was not glb format. https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#chunks [0] must JSON [1] must BIN [2...] may exists.
Referenced by UniGLTF.GltfData.GltfData.
string UniGLTF.GltfData.Json
JSON chunk ToString This chunk MUST be the very first chunk of Binary glTF asset
Referenced by UniGLTF.GltfData.GltfData.
glTF UniGLTF.GltfData.GLTF
GLTF parsed from JSON chunk
Referenced by UniGLTF.GltfData.FlatternFloatArrayFromAccessor, UniGLTF.GltfData.GetArrayFromAccessor< T >, UniGLTF.GltfData.GetBytesFromImage, UniGLTF.PrimitiveExtensions.GetColors, UniGLTF.GltfTextureImporter.GetImageBytesFromTextureIndex, UniGLTF.GltfTextureImporter.GetImageIndexFromTexture, UniGLTF.GltfData.GetIndices, UniGLTF.GltfData.GltfData, UniGLTF.ImporterContext.LoadMaterialsAsync, UniGLTF.GltfData.MaterialHasVertexColor, UniGLTF.GltfScriptedImporterEditor.OnEnable, UniGLTF.ZipArchivedGltfScriptedImporterEditor.OnEnable, UniGLTF.GlbScriptedImporterEditor.OnEnable, UniGLTF.NodeImporter.SetupSkinning, UniGLTF.GltfUnlitMaterialImporter.TryCreateParam, UniGLTF.GltfPbrUrpMaterialImporter.TryCreateParam, UniGLTF.GltfPbrMaterialImporter.TryCreateParam, VRM.VRMData.VRMData.
ArraySegment<byte> UniGLTF.GltfData.Bin
BIN chunk This chunk MUST be the second chunk of the Binary glTF asset
Referenced by UniGLTF.GltfData.GetBytesFromBuffer.
MigrationFlags UniGLTF.GltfData.MigrationFlags
Migration Flags used by ImporterContext
Referenced by UniGLTF.GltfData.CreateFromGltfDataForTest.
IStorage UniGLTF.GltfData._storage
URI access
Referenced by UniGLTF.GltfData.GltfData.
Dictionary<string, ArraySegment<byte> > UniGLTF.GltfData._UriCache
uri = data: base64デコード uri = 相対パス。File.ReadAllBytes
Referenced by UniGLTF.GltfData.GetBytesFromUri.
ArraySegment<byte> UniGLTF.GltfData.binary
readonly UnityEngine.Color UniGLTF.GltfData.ZERO
UniGLTF.GltfData.GltfData(string targetPath, string json, glTF gltf, IReadOnlyList< GlbChunk > chunks, IStorage storage, MigrationFlags migrationFlags)
References UniGLTF.GltfData._storage, UniGLTF.GltfData.Chunks, UniGLTF.GltfData.GLTF, UniGLTF.GltfData.Json, UniGLTF.GltfData.TargetPath.
Referenced by UniGLTF.GltfData.CreateFromGltfDataForTest.
ArraySegment<Byte> UniGLTF.GltfData.GetBytesFromBuffer(int bufferIndex)
References UniGLTF.GltfData.Bin, UniGLTF.GltfData.GetBytesFromUri.
Referenced by UniGLTF.GltfData.FlatternFloatArrayFromAccessor, UniGLTF.GltfData.GetBytesFromBufferView, UniGLTF.GltfData.GetTypedFromBufferView< T >.
ArraySegment<Byte> UniGLTF.GltfData.GetBytesFromBufferView(int bufferView)
References UniGLTF.GltfData.GetBytesFromBuffer.
Referenced by UniGLTF.GltfData.GetBytesFromImage.
int [] UniGLTF.GltfData.GetIndices(int accessorIndex)
References UniGLTF.glTF.accessors, UniGLTF.GltfData.GetIntIndicesFromAccessor, UniGLTF.GltfData.GLTF.
T [] UniGLTF.GltfData.GetArrayFromAccessor< T >(int accessorIndex)
References UniGLTF.glTF.bufferViews, UniGLTF.GltfData.GetIntIndicesFromView, UniGLTF.GltfData.GetTypedFromAccessor< T >, UniGLTF.GltfData.GetTypedFromBufferView< T >, UniGLTF.GltfData.GLTF.
float [] UniGLTF.GltfData.FlatternFloatArrayFromAccessor(int accessorIndex)
References UniGLTF.glTF.bufferViews, UniGLTF.GltfData.GetBytesFromBuffer, UniGLTF.GltfData.GetIntIndicesFromView, UniGLTF.GltfData.GLTF.
bool UniGLTF.GltfData.HasVertexColor(glTFAttributes attributes)
References UniGLTF.glTFAttributes.COLOR_0.
Referenced by UniGLTF.GltfData.MaterialHasVertexColor.
bool UniGLTF.GltfData.MaterialHasVertexColor(int materialIndex)
References UniGLTF.GltfData.GLTF, UniGLTF.GltfData.HasVertexColor, UniGLTF.glTF.materials, UniGLTF.glTF.meshes.
static GltfData UniGLTF.GltfData.CreateFromExportForTest(ExportingGltfData data)
References UniGLTF.ExportingGltfData.BinBytes, UniGLTF.GltfData.CreateFromGltfDataForTest, UniGLTF.ExportingGltfData.GLTF.
static GltfData UniGLTF.GltfData.CreateFromGltfDataForTest(glTF gltf, ArraySegment< byte > bytes)
References UniGLTF.GltfData.GltfData, UniGLTF.GltfData.MigrationFlags.
Referenced by UniGLTF.GltfData.CreateFromExportForTest.
ArraySegment<Byte> UniGLTF.GltfData.GetBytesFromUri(string uri)
References UniGLTF.GltfData._UriCache.
Referenced by UniGLTF.GltfData.GetBytesFromBuffer, UniGLTF.GltfData.GetBytesFromImage.
T [] UniGLTF.GltfData.GetTypedFromBufferView< T >(int count, int byteOffset, glTFBufferView view)
References UniGLTF.GltfData.GetBytesFromBuffer.
Referenced by UniGLTF.GltfData.GetArrayFromAccessor< T >, UniGLTF.GltfData.GetTypedFromAccessor< T >.
T [] UniGLTF.GltfData.GetTypedFromAccessor< T >(glTFAccessor accessor, glTFBufferView view)
References UniGLTF.GltfData.GetTypedFromBufferView< T >.
Referenced by UniGLTF.GltfData.GetArrayFromAccessor< T >.
IEnumerable<int> UniGLTF.GltfData.GetIntIndicesFromView(glTFBufferView view, int count, int byteOffset, glComponentType componentType)
for sparse
view count byteOffset componentType
Referenced by UniGLTF.GltfData.FlatternFloatArrayFromAccessor, UniGLTF.GltfData.GetArrayFromAccessor< T >.
IEnumerable<int> UniGLTF.GltfData.GetIntIndicesFromAccessor(glTFAccessor accessor, out int count)
Get indices and cast to int
accessor count
References UniGLTF.glTFAccessor.componentType.
Referenced by UniGLTF.GltfData.GetIndices.
ArraySegment<byte> string mimeType UniGLTF.GltfData.GetBytesFromImage(int imageIndex)
References UniGLTF.GltfData.GetBytesFromBufferView, UniGLTF.GltfData.GetBytesFromUri, UniGLTF.GltfData.GLTF, UniGLTF.glTF.images.