UniGLTF::MeshContext
readonly List<MeshVertex> UniGLTF.MeshContext._vertices
Referenced by UniGLTF.MeshContext.DropUnusedVertices, UniGLTF.MeshContext.ImportMeshIndependentVertexBuffer, UniGLTF.MeshContext.ImportMeshSharingVertexBuffer, UniGLTF.MeshContext.UploadMeshVertices.
readonly List<int> UniGLTF.MeshContext._indices
Referenced by UniGLTF.MeshContext.UploadMeshIndices.
readonly List<SubMeshDescriptor> UniGLTF.MeshContext._subMeshes
Referenced by UniGLTF.MeshContext.UploadMeshIndices.
readonly List<int> UniGLTF.MeshContext._materialIndices
Referenced by UniGLTF.MeshContext.AddDefaultMaterial.
readonly List<BlendShape> UniGLTF.MeshContext._blendShapes
Referenced by UniGLTF.MeshContext.DropUnusedVertices, UniGLTF.MeshContext.GetOrCreateBlendShape, UniGLTF.MeshContext.ImportMeshSharingVertexBuffer.
IReadOnlyList<int> UniGLTF.MeshContext.MaterialIndices
IReadOnlyList<BlendShape> UniGLTF.MeshContext.BlendShapes
Referenced by UniGLTF.MeshImporter.BuildMeshAsync, UniGLTF.MeshContext.RenameBlendShape.
bool UniGLTF.MeshContext.HasNormal
Referenced by UniGLTF.MeshContext.CheckAttributeUsages.
string UniGLTF.MeshContext.Name
Referenced by UniGLTF.MeshContext.MeshContext.
float UniGLTF.MeshContext.x
Referenced by UniGLTF.MeshContext.ImportMeshSharingVertexBuffer.
float float UniGLTF.MeshContext.y
float float float UniGLTF.MeshContext.z
void UniGLTF.MeshContext.UploadMeshVertices(Mesh mesh)
頂点情報をMeshに対して送る
mesh
References UniGLTF.MeshContext._vertices.
void UniGLTF.MeshContext.UploadMeshIndices(Mesh mesh)
インデックス情報をMeshに対して送る
mesh
References UniGLTF.MeshContext._indices, UniGLTF.MeshContext._subMeshes.
UniGLTF.MeshContext.MeshContext(string name, int meshIndex)
References UniGLTF.MeshContext.Name.
void UniGLTF.MeshContext.ImportMeshIndependentVertexBuffer(GltfData data, glTFMesh gltfMesh, IAxisInverter inverter)
各 primitive の attribute の要素が同じでない。=> uv が有るものと無いものが混在するなど glTF 的にはありうる。
primitive を独立した(Independent) Mesh として扱いこれを連結する。 ctx gltfMesh
References UniGLTF.MeshContext._vertices, UniGLTF.MeshContext.CheckAttributeUsages, UniGLTF.MeshContext.GetOrCreateBlendShape, UniGLTF.MeshContext.NormalizeBoneWeight, UnityEngine.Vector3.zero.
void UniGLTF.MeshContext.ImportMeshSharingVertexBuffer(GltfData data, glTFMesh gltfMesh, IAxisInverter inverter)
各primitiveが同じ attribute を共有している場合専用のローダー。 ctx gltfMesh
References UniGLTF.MeshContext._blendShapes, UniGLTF.MeshContext._vertices, UniGLTF.MeshContext.CheckAttributeUsages, UniGLTF.IAxisInverter.InvertVector3, UniGLTF.MeshContext.NormalizeBoneWeight, UniGLTF.MeshContext.x, UnityEngine.Vector3.zero.
void UniGLTF.MeshContext.RenameBlendShape(glTFMesh gltfMesh)
References UniGLTF.MeshContext.BlendShapes, UniGLTF.gltf_mesh_extras_targetNames.TryGet.
void UniGLTF.MeshContext.AddDefaultMaterial()
References UniGLTF.MeshContext._materialIndices.
void UniGLTF.MeshContext.DropUnusedVertices()
https://github.com/vrm-c/UniVRM/issues/610
VertexBuffer の後ろに未使用頂点がある場合に削除する
References UniGLTF.MeshContext._blendShapes, UniGLTF.MeshContext._vertices.
BlendShape UniGLTF.MeshContext.GetOrCreateBlendShape(int i)
References UniGLTF.MeshContext._blendShapes.
Referenced by UniGLTF.MeshContext.ImportMeshIndependentVertexBuffer.
void UniGLTF.MeshContext.CheckAttributeUsages(glTFPrimitives primitives)
各種頂点属性が使われているかどうかをチェックし、使われていなかったらフラグを切る MEMO: O(1)で検知する手段がありそう
References UniGLTF.MeshContext.HasNormal.
Referenced by UniGLTF.MeshContext.ImportMeshIndependentVertexBuffer, UniGLTF.MeshContext.ImportMeshSharingVertexBuffer.
static float float float float w UniGLTF.MeshContext.NormalizeBoneWeight((float x, float y, float z, float w) src)
Referenced by UniGLTF.MeshContext.ImportMeshIndependentVertexBuffer, UniGLTF.MeshContext.ImportMeshSharingVertexBuffer.
static void UniGLTF.MeshContext.Truncate< T >(List< T > list, int maxIndex)