UniGLTF::HierarchyValidator
ExportValidatorMessages
static bool UniGLTF.HierarchyValidator.DuplicateNodeNameExists(GameObject ExportRoot)
ボーン名の重複を確認
Referenced by UniGLTF.HierarchyValidator.Validate.
static bool UniGLTF.HierarchyValidator.HasNoUniqueJoints(Renderer r)
Referenced by UniGLTF.HierarchyValidator.Validate.
static IEnumerable<Validation> UniGLTF.HierarchyValidator.ValidateRoot(GameObject ExportRoot)
Referenced by UniGLTF.GltfExportWindow.ValidatorFactory.
static IEnumerable<Validation> UniGLTF.HierarchyValidator.Validate(GameObject ExportRoot)
References UniGLTF.HierarchyValidator.DuplicateNodeNameExists, UniGLTF.HierarchyValidator.HasNoUniqueJoints.