UniHumanoid::Humanoid
Transform UniHumanoid.Humanoid.m_Hips
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftUpperLeg
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.GetForward, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightUpperLeg
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.GetForward, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftLowerLeg
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightLowerLeg
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftFoot
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightFoot
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftToes
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightToes
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_Spine
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_Chest
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_UpperChest
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_Neck
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_Head
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftEye
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightEye
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_Jaw
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftShoulder
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightShoulder
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftUpperArm
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightUpperArm
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftLowerArm
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightLowerArm
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftHand
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_RightHand
Referenced by UniHumanoid.Humanoid.AssignBones, UniHumanoid.Humanoid.Validate.
Transform UniHumanoid.Humanoid.m_LeftThumbProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftThumbIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftThumbDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftIndexProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftIndexIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftIndexDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftMiddleProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftMiddleIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftMiddleDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftRingProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftRingIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftRingDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftLittleProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftLittleIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_LeftLittleDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightThumbProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightThumbIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightThumbDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightIndexProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightIndexIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightIndexDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightMiddleProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightMiddleIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightMiddleDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightRingProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightRingIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightRingDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightLittleProximal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightLittleIntermediate
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.m_RightLittleDistal
Referenced by UniHumanoid.Humanoid.AssignBones.
Transform UniHumanoid.Humanoid.Hips
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftUpperLeg
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightUpperLeg
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftLowerLeg
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightLowerLeg
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftFoot
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightFoot
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftToes
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightToes
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.Spine
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.Chest
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.UpperChest
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.Neck
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.Head
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftEye
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightEye
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.Jaw
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftShoulder
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightShoulder
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftUpperArm
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightUpperArm
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftLowerArm
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightLowerArm
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftHand
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightHand
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftThumbProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftThumbIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftThumbDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftIndexProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftIndexIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftIndexDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftMiddleProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftMiddleIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftMiddleDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftRingProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftRingIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftRingDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftLittleProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftLittleIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.LeftLittleDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightThumbProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightThumbIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightThumbDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightIndexProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightIndexIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightIndexDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightMiddleProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightMiddleIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightMiddleDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightRingProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightRingIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightRingDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightLittleProximal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightLittleIntermediate
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
Transform UniHumanoid.Humanoid.RightLittleDistal
Referenced by UniHumanoid.Humanoid.GetBoneTransform.
IEnumerable<(Transform, HumanBodyBones)> UniHumanoid.Humanoid.BoneMap
Referenced by UniHumanoid.Humanoid.CreateAvatar.
void UniHumanoid.Humanoid.Reset()
References UniHumanoid.Humanoid.AssignBonesFromAnimator.
IEnumerable<Validation> UniHumanoid.Humanoid.Required(params(string, Transform)[] props)
Referenced by UniHumanoid.Humanoid.Validate.
static Vector3 UniHumanoid.Humanoid.GetForward(Transform l, Transform r)
Vector3 UniHumanoid.Humanoid.GetForward()
References UniHumanoid.Humanoid.m_LeftUpperLeg, UniHumanoid.Humanoid.m_RightUpperLeg.
IEnumerable<Validation> UniHumanoid.Humanoid.Validate()
References UniHumanoid.Humanoid.m_Head, UniHumanoid.Humanoid.m_Hips, UniHumanoid.Humanoid.m_LeftFoot, UniHumanoid.Humanoid.m_LeftHand, UniHumanoid.Humanoid.m_LeftLowerArm, UniHumanoid.Humanoid.m_LeftLowerLeg, UniHumanoid.Humanoid.m_LeftUpperArm, UniHumanoid.Humanoid.m_LeftUpperLeg, UniHumanoid.Humanoid.m_RightFoot, UniHumanoid.Humanoid.m_RightHand, UniHumanoid.Humanoid.m_RightLowerArm, UniHumanoid.Humanoid.m_RightLowerLeg, UniHumanoid.Humanoid.m_RightUpperArm, UniHumanoid.Humanoid.m_RightUpperLeg, UniHumanoid.Humanoid.m_Spine, UniHumanoid.Humanoid.Required.
Referenced by UniHumanoid.HumanoidEditor.OnInspectorGUI.
Avatar UniHumanoid.Humanoid.CreateAvatar()
UnityEngine.Avatar
References UniHumanoid.Humanoid.BoneMap.
Transform UniHumanoid.Humanoid.GetBoneTransform(HumanBodyBones bone)
References UniHumanoid.Humanoid.Chest, UniHumanoid.Humanoid.Head, UniHumanoid.Humanoid.Hips, UniHumanoid.Humanoid.Jaw, UniHumanoid.Humanoid.LeftEye, UniHumanoid.Humanoid.LeftFoot, UniHumanoid.Humanoid.LeftHand, UniHumanoid.Humanoid.LeftIndexDistal, UniHumanoid.Humanoid.LeftIndexIntermediate, UniHumanoid.Humanoid.LeftIndexProximal, UniHumanoid.Humanoid.LeftLittleDistal, UniHumanoid.Humanoid.LeftLittleIntermediate, UniHumanoid.Humanoid.LeftLittleProximal, UniHumanoid.Humanoid.LeftLowerArm, UniHumanoid.Humanoid.LeftLowerLeg, UniHumanoid.Humanoid.LeftMiddleDistal, UniHumanoid.Humanoid.LeftMiddleIntermediate, UniHumanoid.Humanoid.LeftMiddleProximal, UniHumanoid.Humanoid.LeftRingDistal, UniHumanoid.Humanoid.LeftRingIntermediate, UniHumanoid.Humanoid.LeftRingProximal, UniHumanoid.Humanoid.LeftShoulder, UniHumanoid.Humanoid.LeftThumbDistal, UniHumanoid.Humanoid.LeftThumbIntermediate, UniHumanoid.Humanoid.LeftThumbProximal, UniHumanoid.Humanoid.LeftToes, UniHumanoid.Humanoid.LeftUpperArm, UniHumanoid.Humanoid.LeftUpperLeg, UniHumanoid.Humanoid.Neck, UniHumanoid.Humanoid.RightEye, UniHumanoid.Humanoid.RightFoot, UniHumanoid.Humanoid.RightHand, UniHumanoid.Humanoid.RightIndexDistal, UniHumanoid.Humanoid.RightIndexIntermediate, UniHumanoid.Humanoid.RightIndexProximal, UniHumanoid.Humanoid.RightLittleDistal, UniHumanoid.Humanoid.RightLittleIntermediate, UniHumanoid.Humanoid.RightLittleProximal, UniHumanoid.Humanoid.RightLowerArm, UniHumanoid.Humanoid.RightLowerLeg, UniHumanoid.Humanoid.RightMiddleDistal, UniHumanoid.Humanoid.RightMiddleIntermediate, UniHumanoid.Humanoid.RightMiddleProximal, UniHumanoid.Humanoid.RightRingDistal, UniHumanoid.Humanoid.RightRingIntermediate, UniHumanoid.Humanoid.RightRingProximal, UniHumanoid.Humanoid.RightShoulder, UniHumanoid.Humanoid.RightThumbDistal, UniHumanoid.Humanoid.RightThumbIntermediate, UniHumanoid.Humanoid.RightThumbProximal, UniHumanoid.Humanoid.RightToes, UniHumanoid.Humanoid.RightUpperArm, UniHumanoid.Humanoid.RightUpperLeg, UniHumanoid.Humanoid.Spine, UniHumanoid.Humanoid.UpperChest.
void UniHumanoid.Humanoid.AssignBones(IEnumerable<(HumanBodyBones, Transform)> nodes)
nodes
nodes
References UniHumanoid.Humanoid.m_Chest, UniHumanoid.Humanoid.m_Head, UniHumanoid.Humanoid.m_Hips, UniHumanoid.Humanoid.m_Jaw, UniHumanoid.Humanoid.m_LeftEye, UniHumanoid.Humanoid.m_LeftFoot, UniHumanoid.Humanoid.m_LeftHand, UniHumanoid.Humanoid.m_LeftIndexDistal, UniHumanoid.Humanoid.m_LeftIndexIntermediate, UniHumanoid.Humanoid.m_LeftIndexProximal, UniHumanoid.Humanoid.m_LeftLittleDistal, UniHumanoid.Humanoid.m_LeftLittleIntermediate, UniHumanoid.Humanoid.m_LeftLittleProximal, UniHumanoid.Humanoid.m_LeftLowerArm, UniHumanoid.Humanoid.m_LeftLowerLeg, UniHumanoid.Humanoid.m_LeftMiddleDistal, UniHumanoid.Humanoid.m_LeftMiddleIntermediate, UniHumanoid.Humanoid.m_LeftMiddleProximal, UniHumanoid.Humanoid.m_LeftRingDistal, UniHumanoid.Humanoid.m_LeftRingIntermediate, UniHumanoid.Humanoid.m_LeftRingProximal, UniHumanoid.Humanoid.m_LeftShoulder, UniHumanoid.Humanoid.m_LeftThumbDistal, UniHumanoid.Humanoid.m_LeftThumbIntermediate, UniHumanoid.Humanoid.m_LeftThumbProximal, UniHumanoid.Humanoid.m_LeftToes, UniHumanoid.Humanoid.m_LeftUpperArm, UniHumanoid.Humanoid.m_LeftUpperLeg, UniHumanoid.Humanoid.m_Neck, UniHumanoid.Humanoid.m_RightEye, UniHumanoid.Humanoid.m_RightFoot, UniHumanoid.Humanoid.m_RightHand, UniHumanoid.Humanoid.m_RightIndexDistal, UniHumanoid.Humanoid.m_RightIndexIntermediate, UniHumanoid.Humanoid.m_RightIndexProximal, UniHumanoid.Humanoid.m_RightLittleDistal, UniHumanoid.Humanoid.m_RightLittleIntermediate, UniHumanoid.Humanoid.m_RightLittleProximal, UniHumanoid.Humanoid.m_RightLowerArm, UniHumanoid.Humanoid.m_RightLowerLeg, UniHumanoid.Humanoid.m_RightMiddleDistal, UniHumanoid.Humanoid.m_RightMiddleIntermediate, UniHumanoid.Humanoid.m_RightMiddleProximal, UniHumanoid.Humanoid.m_RightRingDistal, UniHumanoid.Humanoid.m_RightRingIntermediate, UniHumanoid.Humanoid.m_RightRingProximal, UniHumanoid.Humanoid.m_RightShoulder, UniHumanoid.Humanoid.m_RightThumbDistal, UniHumanoid.Humanoid.m_RightThumbIntermediate, UniHumanoid.Humanoid.m_RightThumbProximal, UniHumanoid.Humanoid.m_RightToes, UniHumanoid.Humanoid.m_RightUpperArm, UniHumanoid.Humanoid.m_RightUpperLeg, UniHumanoid.Humanoid.m_Spine, UniHumanoid.Humanoid.m_UpperChest.
Referenced by UniHumanoid.Humanoid.AssignBonesFromAnimator.
bool UniHumanoid.Humanoid.AssignBonesFromAnimator()
Animator Bone
References UniHumanoid.Humanoid.AssignBones.
Referenced by UniHumanoid.Humanoid.Reset.