UniJSON::JsonFormatter
Current
IStore UniJSON.JsonFormatter.m_w
Referenced by UniJSON.JsonFormatter._Value, UniJSON.JsonFormatter.GetStore, UniJSON.JsonFormatter.JsonFormatter.
Stack<Context> UniJSON.JsonFormatter.m_stack
Referenced by UniJSON.JsonFormatter.EndList, UniJSON.JsonFormatter.EndMap.
string UniJSON.JsonFormatter.m_indent
Referenced by UniJSON.JsonFormatter.Indent, UniJSON.JsonFormatter.JsonFormatter.
string UniJSON.JsonFormatter.m_colon
Referenced by UniJSON.JsonFormatter.JsonFormatter, UniJSON.JsonFormatter.Key.
IStore UniJSON.JsonFormatter.Store
Utf8String UniJSON.JsonFormatter.s_null
Utf8String UniJSON.JsonFormatter.s_true
Utf8String UniJSON.JsonFormatter.s_false
void UniJSON.JsonFormatter.Indent()
References UniJSON.JsonFormatter.m_indent.
Referenced by UniJSON.JsonFormatter._Value, UniJSON.JsonFormatter.EndMap.
void UniJSON.JsonFormatter._Value(Utf8String key, bool isKey)
References UniJSON.JsonFormatter.CommaCheck, UniJSON.JsonFormatter.Indent, UniJSON.JsonFormatter.m_w.
Referenced by UniJSON.JsonFormatter.Key, UniJSON.JsonFormatter.Value.
UniJSON.JsonFormatter.JsonFormatter(int indent=0)
UniJSON.JsonFormatter.JsonFormatter(IStore w, int indent=0)
References UniJSON.JsonFormatter.m_colon, UniJSON.JsonFormatter.m_indent, UniJSON.JsonFormatter.m_w.
override string UniJSON.JsonFormatter.ToString()
IStore UniJSON.JsonFormatter.GetStore()
References UniJSON.JsonFormatter.m_w.
void UniJSON.JsonFormatter.Clear()
void UniJSON.JsonFormatter.Null()
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.BeginList(int _=0)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.EndList()
References UniJSON.JsonFormatter.m_stack.
void UniJSON.JsonFormatter.BeginMap(int _=0)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.EndMap()
References UniJSON.JsonFormatter.Indent, UniJSON.JsonFormatter.m_stack.
void UniJSON.JsonFormatter.Key(Utf8String key)
References UniJSON.JsonFormatter._Value, UniJSON.JsonFormatter.m_colon.
void UniJSON.JsonFormatter.Value(string x)
References UniJSON.Utf8String.From.
Referenced by UniGLTF.GltfJsonUtil.CopyJson, UniJSON.JsonFormatter.Value.
void UniJSON.JsonFormatter.Value(Utf8String key)
References UniJSON.JsonFormatter._Value.
void UniJSON.JsonFormatter.Value(Boolean x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(SByte x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Int16 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Int32 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Int64 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Byte x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(UInt16 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(UInt32 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(UInt64 x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Single x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(Double x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(ArraySegment< Byte > x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Raw(ArraySegment< Byte > x)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.Value(DateTimeOffset x)
References UniJSON.JsonFormatter.Value.
void UniJSON.JsonFormatter.Value(JsonNode node)
References UniJSON.JsonFormatter.CommaCheck.
void UniJSON.JsonFormatter.CommaCheck(bool isKey=false)
Referenced by UniJSON.JsonFormatter._Value, UniJSON.JsonFormatter.BeginList, UniJSON.JsonFormatter.BeginMap, UniJSON.JsonFormatter.Null, UniJSON.JsonFormatter.Raw, UniJSON.JsonFormatter.Value.