UniGLTF::MaterialExporter
const string UniGLTF.MaterialExporter.COLOR_TEXTURE_PROP
Referenced by UniGLTF.DefaultMaterialValidator.EnumerateTextureProperties, UniGLTF.MaterialExporter.Export_Color, UniGLTF.MaterialExporter.Export_MainTextureTransform.
const string UniGLTF.MaterialExporter.METALLIC_TEX_PROP
Referenced by UniGLTF.DefaultMaterialValidator.EnumerateTextureProperties, UniGLTF.MaterialExporter.Export_OcclusionMetallicRoughness.
const string UniGLTF.MaterialExporter.NORMAL_TEX_PROP
Referenced by UniGLTF.DefaultMaterialValidator.EnumerateTextureProperties, UniGLTF.MaterialExporter.Export_Normal.
const string UniGLTF.MaterialExporter.EMISSION_TEX_PROP
Referenced by UniGLTF.DefaultMaterialValidator.EnumerateTextureProperties, UniGLTF.MaterialExporter.Export_Emission.
const string UniGLTF.MaterialExporter.OCCLUSION_TEX_PROP
Referenced by UniGLTF.DefaultMaterialValidator.EnumerateTextureProperties, UniGLTF.MaterialExporter.Export_OcclusionMetallicRoughness.
virtual glTFMaterial UniGLTF.MaterialExporter.ExportMaterial(Material m, ITextureExporter textureExporter, GltfExportSettings settings)
References UniGLTF.MaterialExporter.CreateMaterial, UniGLTF.MaterialExporter.Export_Color, UniGLTF.MaterialExporter.Export_Emission, UniGLTF.MaterialExporter.Export_Normal, UniGLTF.MaterialExporter.Export_OcclusionMetallicRoughness, UniGLTF.GltfExportSettings.UseEmissiveMultiplier.
static void UniGLTF.MaterialExporter.Export_Color(Material m, ITextureExporter textureManager, glTFMaterial material)
References UniGLTF.glTFPbrMetallicRoughness.baseColorTexture, UniGLTF.MaterialExporter.COLOR_TEXTURE_PROP, UniGLTF.MaterialExporter.Export_MainTextureTransform, UniGLTF.glTFMaterial.pbrMetallicRoughness.
Referenced by UniGLTF.MaterialExporter.ExportMaterial.
static void UniGLTF.MaterialExporter.Export_OcclusionMetallicRoughness(Material m, ITextureExporter textureExporter, glTFMaterial material)
Occlusion, Metallic, Roughness
m textureExporter material
References UniGLTF.MaterialExporter.Export_MainTextureTransform, UniGLTF.MaterialExporter.METALLIC_TEX_PROP, UniGLTF.glTFPbrMetallicRoughness.metallicRoughnessTexture, UniGLTF.MaterialExporter.OCCLUSION_TEX_PROP, UniGLTF.glTFMaterial.occlusionTexture, UniGLTF.glTFMaterial.pbrMetallicRoughness.
Referenced by UniGLTF.MaterialExporter.ExportMaterial.
static void UniGLTF.MaterialExporter.Export_Normal(Material m, ITextureExporter textureExporter, glTFMaterial material)
References UniGLTF.MaterialExporter.Export_MainTextureTransform, UniGLTF.MaterialExporter.NORMAL_TEX_PROP, UniGLTF.glTFMaterial.normalTexture.
Referenced by UniGLTF.MaterialExporter.ExportMaterial.
static void UniGLTF.MaterialExporter.Export_Emission(Material m, ITextureExporter textureExporter, glTFMaterial material, bool useEmissiveMultiplier)
References UniGLTF.MaterialExporter.EMISSION_TEX_PROP, UniGLTF.glTFMaterial.emissiveTexture, UniGLTF.MaterialExporter.Export_MainTextureTransform.
Referenced by UniGLTF.MaterialExporter.ExportMaterial.
static void UniGLTF.MaterialExporter.Export_MainTextureTransform(Material m, glTFTextureInfo textureInfo)
References UniGLTF.MaterialExporter.COLOR_TEXTURE_PROP, UniGLTF.MaterialExporter.Export_TextureTransform.
Referenced by UniGLTF.MaterialExporter.Export_Color, UniGLTF.MaterialExporter.Export_Emission, UniGLTF.MaterialExporter.Export_Normal, UniGLTF.MaterialExporter.Export_OcclusionMetallicRoughness.
static void UniGLTF.MaterialExporter.Export_TextureTransform(Material m, glTFTextureInfo textureInfo, string propertyName)
References UniGLTF.TextureTransform.VerticalFlipScaleOffset.
Referenced by UniGLTF.MaterialExporter.Export_MainTextureTransform.
static glTFMaterial UniGLTF.MaterialExporter.Export_UnlitColor(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.
static glTFMaterial UniGLTF.MaterialExporter.Export_UnlitTexture(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.
static glTFMaterial UniGLTF.MaterialExporter.Export_UnlitTransparent(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.
static glTFMaterial UniGLTF.MaterialExporter.Export_UnlitCutout(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.
static glTFMaterial UniGLTF.MaterialExporter.Export_Standard(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.
static bool UniGLTF.MaterialExporter.IsUnlit(string shaderName)
Referenced by UniGLTF.DefaultMaterialValidator.GetGltfMaterialTypeFromUnityShaderName.
virtual glTFMaterial UniGLTF.MaterialExporter.CreateMaterial(Material m)
References UniGLTF.MaterialExporter.Export_Standard, UniGLTF.MaterialExporter.Export_UniUnlit, UniGLTF.MaterialExporter.Export_UnlitColor, UniGLTF.MaterialExporter.Export_UnlitCutout, UniGLTF.MaterialExporter.Export_UnlitTexture, UniGLTF.MaterialExporter.Export_UnlitTransparent.
Referenced by UniGLTF.MaterialExporter.ExportMaterial.
glTFMaterial UniGLTF.MaterialExporter.Export_UniUnlit(Material m)
Referenced by UniGLTF.MaterialExporter.CreateMaterial.