UniGLTF::GltfJsonUtil
const string UniGLTF.GltfJsonUtil.EXTENSION_USED_KEY
Referenced by UniGLTF.GltfJsonUtil.CopyJson.
static IEnumerable<object[]> UniGLTF.GltfJsonUtil.TraverseJsonPath(JsonNode node, List< object > path)
JsonPath を 再帰的に列挙する object[] の中身は int(array index) or string(object key)
node path
Referenced by UniGLTF.GltfJsonUtil.FindUsedExtensionsAndUpdateJson.
static string UniGLTF.GltfJsonUtil.FindUsedExtensionsAndUpdateJson(string src)
https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/glTF.schema.json
extensionUsed の更新を各拡張自身にやらせるのは無駄だし、手動でコントロールするのも間違いの元である。 完成品の JSON から後付けで作ることにした。 Exporter しか使わない処理なので、GC, 処理速度は気にしてない src
References UniGLTF.GltfJsonUtil.CopyJson, UniGLTF.GltfJsonUtil.TraverseJsonPath, UniGLTF.GltfJsonUtil.TryGetExtensionName.
static string UniGLTF.GltfJsonUtil.DoubleQuote(string src)
static bool UniGLTF.GltfJsonUtil.TryGetExtensionName(object[] path, out string extensionName)
jsonPath が
[..., "extensions", "EXTENSION_NAME"]で有る場合に EXTENSION_NAME を返す。 jsonPath extensionName
Referenced by UniGLTF.GltfJsonUtil.FindUsedExtensionsAndUpdateJson.
static void UniGLTF.GltfJsonUtil.CopyJson(IReadOnlyList< string > extensionUsed, JsonFormatter dst, JsonNode src, int level)
References UniGLTF.GltfJsonUtil.EXTENSION_USED_KEY, UniJSON.JsonFormatter.Value.
Referenced by UniGLTF.GltfJsonUtil.FindUsedExtensionsAndUpdateJson.