UniGLTF::TextureEnumerateTests
static glTF UniGLTF.TextureEnumerateTests.TwoTexture()
Referenced by UniGLTF.TextureEnumerateTests.TextureEnumerationTest.
static glTF UniGLTF.TextureEnumerateTests.TwoTextureOneUri()
Referenced by UniGLTF.TextureEnumerateTests.TextureEnumerationTest.
static glTF UniGLTF.TextureEnumerateTests.TwoTextureOneImage()
Referenced by UniGLTF.TextureEnumerateTests.TextureEnumerationTest.
static glTF UniGLTF.TextureEnumerateTests.CombineMetallicSmoothOcclusion()
Referenced by UniGLTF.TextureEnumerateTests.TextureEnumerationTest.
void UniGLTF.TextureEnumerateTests.TextureEnumerationTest()
Test uniqueness
References UniGLTF.TextureEnumerateTests.CombineMetallicSmoothOcclusion, UniGLTF.TextureEnumerateTests.CreateGltfData, UniGLTF.TextureEnumerateTests.TwoTexture, UniGLTF.TextureEnumerateTests.TwoTextureOneImage, UniGLTF.TextureEnumerateTests.TwoTextureOneUri.
GltfData UniGLTF.TextureEnumerateTests.CreateGltfData(glTF gltf)
Referenced by UniGLTF.TextureEnumerateTests.TextureEnumerationTest.