UniGLTF::InternalTPose
static void UniGLTF.InternalTPose.BuildMap(Transform t, Dictionary< string, TRS > map, Transform root=null)
References UniGLTF.InternalTPose.TRS.From.
Referenced by UniGLTF.InternalTPose.TrySampleBindPose.
static void UniGLTF.InternalTPose.ApplyMap(Transform t, Dictionary< string, TRS > map, Transform root=null)
Referenced by UniGLTF.InternalTPose.TrySampleBindPose.
static bool UniGLTF.InternalTPose.TrySampleBindPose(GameObject go)
References UniGLTF.InternalTPose.ApplyMap, UniGLTF.InternalTPose.BuildMap.
static bool UniGLTF.InternalTPose.TryMakePoseValid(GameObject go)
Referenced by VRM.VRMExporterWizard.DoGUI.