VRM::VRMMetaObjectEditor
MessageKeys
VRMMetaObject VRM.VRMMetaObjectEditor.m_target
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.TakeScreenShot.
SerializedProperty VRM.VRMMetaObjectEditor.m_Script
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
SerializedProperty VRM.VRMMetaObjectEditor.m_exporterVersion
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_thumbnail
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
ValidateProperty VRM.VRMMetaObjectEditor.m_title
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
ValidateProperty VRM.VRMMetaObjectEditor.m_version
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
ValidateProperty VRM.VRMMetaObjectEditor.m_author
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
ValidateProperty VRM.VRMMetaObjectEditor.m_contact
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
ValidateProperty VRM.VRMMetaObjectEditor.m_reference
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
SerializedProperty VRM.VRMMetaObjectEditor.m_AllowedUser
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_ViolentUssage
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_SexualUssage
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_CommercialUssage
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_OtherPermissionUrl
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_LicenseType
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
SerializedProperty VRM.VRMMetaObjectEditor.m_OtherLicenseUrl
Referenced by VRM.VRMMetaObjectEditor.OnEnable, VRM.VRMMetaObjectEditor.OnInspectorGUI.
bool VRM.VRMMetaObjectEditor.m_foldoutInfo
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
bool VRM.VRMMetaObjectEditor.m_foldoutPermission
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
bool VRM.VRMMetaObjectEditor.m_foldoutDistribution
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
VRM.VRMMetaObjectEditor.Rect
Referenced by VRM.VRMMetaObjectEditor.TakeScreenShot.
static string VRM.VRMMetaObjectEditor.RequiredMessage(string name)
References UniGLTF.M17N.LanguageGetter.Lang.
Referenced by VRM.VRMMetaObjectEditor.OnEnable.
static string VRM.VRMMetaObjectEditor.Msg(MessageKeys key)
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
static string VRM.VRMMetaObjectEditor.SaveDialog(VRMMetaObject meta, string ext)
Referenced by VRM.VRMMetaObjectEditor.TakeScreenShot.
static Rect VRM.VRMMetaObjectEditor.FixedRight(Rect r, int width)
Referenced by VRM.VRMMetaObjectEditor.RightFixedPropField.
static void VRM.VRMMetaObjectEditor.RightFixedPropField(SerializedProperty prop, string label)
References VRM.VRMMetaObjectEditor.FixedRight.
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
static Texture2D VRM.VRMMetaObjectEditor.TextureField(string name, Texture2D texture, int size)
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
void VRM.VRMMetaObjectEditor.OnEnable()
References VRM.VRMMetaObject.AllowedUser, VRM.VRMMetaObject.Author, VRM.VRMMetaObject.CommercialUssage, VRM.VRMMetaObject.ContactInformation, VRM.VRMMetaObject.ExporterVersion, VRM.VRMMetaObject.LicenseType, VRM.VRMMetaObjectEditor.m_AllowedUser, VRM.VRMMetaObjectEditor.m_author, VRM.VRMMetaObjectEditor.m_CommercialUssage, VRM.VRMMetaObjectEditor.m_contact, VRM.VRMMetaObjectEditor.m_exporterVersion, VRM.VRMMetaObjectEditor.m_LicenseType, VRM.VRMMetaObjectEditor.m_OtherLicenseUrl, VRM.VRMMetaObjectEditor.m_OtherPermissionUrl, VRM.VRMMetaObjectEditor.m_reference, VRM.VRMMetaObjectEditor.m_Script, VRM.VRMMetaObjectEditor.m_SexualUssage, VRM.VRMMetaObjectEditor.m_target, VRM.VRMMetaObjectEditor.m_thumbnail, VRM.VRMMetaObjectEditor.m_title, VRM.VRMMetaObjectEditor.m_version, VRM.VRMMetaObjectEditor.m_ViolentUssage, VRM.VRMMetaObject.OtherLicenseUrl, VRM.VRMMetaObject.OtherPermissionUrl, VRM.VRMMetaObject.Reference, VRM.VRMMetaObjectEditor.RequiredMessage, VRM.VRMMetaObject.SexualUssage, VRM.VRMMetaObject.Thumbnail, VRM.VRMMetaObject.Title, VRM.VRMMetaObject.Version, VRM.VRMMetaObject.ViolentUssage.
void VRM.VRMMetaObjectEditor.TakeScreenShot()
References VRM.VRMMetaObjectEditor.m_target, VRM.VRMMetaObjectEditor.Rect, VRM.VRMMetaObjectEditor.SaveDialog.
Referenced by VRM.VRMMetaObjectEditor.OnInspectorGUI.
override void VRM.VRMMetaObjectEditor.OnInspectorGUI()
References VRM.VRMVersion.IsNewer, VRM.VRMMetaObjectEditor.m_AllowedUser, VRM.VRMMetaObjectEditor.m_CommercialUssage, VRM.VRMMetaObjectEditor.m_exporterVersion, VRM.VRMMetaObjectEditor.m_foldoutDistribution, VRM.VRMMetaObjectEditor.m_foldoutInfo, VRM.VRMMetaObjectEditor.m_foldoutPermission, VRM.VRMMetaObjectEditor.m_LicenseType, VRM.VRMMetaObjectEditor.m_OtherLicenseUrl, VRM.VRMMetaObjectEditor.m_OtherPermissionUrl, VRM.VRMMetaObjectEditor.m_SexualUssage, VRM.VRMMetaObjectEditor.m_thumbnail, VRM.VRMMetaObjectEditor.m_ViolentUssage, VRM.VRMMetaObjectEditor.Msg, VRM.VRMMetaObjectEditor.RightFixedPropField, VRM.VRMMetaObjectEditor.TakeScreenShot, VRM.VRMMetaObjectEditor.TextureField.