VRM::VRMLookAt
bool VRM.VRMLookAt.DrawGizmo
Referenced by VRM.VRMLookAt.OnDrawGizmos.
bool VRM.VRMLookAt.UseUpdate
Referenced by VRM.VRMLookAt.LateUpdate.
Transform VRM.VRMLookAt.Target
Referenced by VRM.VRMLookAt.CopyTo, VRM.VRMLookAt.LateUpdate, VRM.VRMLookAt.Reset.
OffsetOnTransform VRM.VRMLookAt.LeftEye
Referenced by VRM.VRMLookAt.ApplyRotations, VRM.VRMLookAt.GetBones, VRM.VRMLookAt.OnDrawGizmos.
OffsetOnTransform VRM.VRMLookAt.RightEye
Referenced by VRM.VRMLookAt.ApplyRotations, VRM.VRMLookAt.GetBones, VRM.VRMLookAt.OnDrawGizmos.
OffsetOnTransform VRM.VRMLookAt.Head
Referenced by VRM.VRMLookAt.ApplyRotations, VRM.VRMLookAt.GetBones, VRM.VRMLookAt.LookFace, VRM.VRMLookAt.OnDrawGizmos.
CurveMapper VRM.VRMLookAt.HorizontalOuter
Referenced by VRM.VRMLookAt.CopyTo.
CurveMapper VRM.VRMLookAt.HorizontalInner
Referenced by VRM.VRMLookAt.CopyTo.
CurveMapper VRM.VRMLookAt.VerticalDown
Referenced by VRM.VRMLookAt.CopyTo.
CurveMapper VRM.VRMLookAt.VerticalUp
Referenced by VRM.VRMLookAt.CopyTo.
float VRM.VRMLookAt.Yaw
Referenced by VRM.VRMLookAt.LookWorldPosition.
float VRM.VRMLookAt.Pitch
Referenced by VRM.VRMLookAt.LookWorldPosition.
const float VRM.VRMLookAt.SIZE
Referenced by VRM.VRMLookAt.OnDrawGizmos.
Matrix4x4 VRM.VRMLookAt.YawMatrix
Texture2D VRM.VRMLookAt.CreateThumbnail()
void VRM.VRMLookAt.LookFace(Transform t)
References VRM.head, VRM.VRMLookAt.Head, VRM.OffsetOnTransform.Transform.
Referenced by VRM.VRMLookAt.CreateThumbnail.
void VRM.VRMLookAt.CopyTo(GameObject _dst, Dictionary< Transform, Transform > map)
References VRM.VRMLookAt.HorizontalInner, VRM.VRMLookAt.HorizontalOuter, VRM.VRMLookAt.Target, VRM.VRMLookAt.VerticalDown, VRM.VRMLookAt.VerticalUp.
void VRM.VRMLookAt.GetBones()
References VRM.VRMLookAt.Head, VRM.VRMLookAt.LeftEye, VRM.VRMLookAt.RightEye.
Referenced by VRM.VRMLookAt.Reset.
void VRM.VRMLookAt.LookWorldPosition(Vector3 targetPosition)
References VRM.VRMLookAt.ApplyRotations, VRM.VRMLookAt.Pitch, VRM.VRMLookAt.Yaw.
Referenced by VRM.VRMLookAt.LateUpdate.
void VRM.VRMLookAt.CreateThumbnail(Camera camera, Texture2D dst)
References VRM.VRMLookAt.LookFace.
void VRM.VRMLookAt.Reset()
References VRM.VRMLookAt.GetBones, VRM.VRMLookAt.Target.
void VRM.VRMLookAt.OnValidate()
void VRM.VRMLookAt.Awake()
void VRM.VRMLookAt.OnDrawGizmos()
References VRM.VRMLookAt.DrawGizmo, VRM.VRMLookAt.DrawMatrix, VRM.VRMLookAt.Head, VRM.VRMLookAt.LeftEye, VRM.VRMLookAt.RightEye, VRM.VRMLookAt.SIZE, VRM.OffsetOnTransform.Transform, VRM.OffsetOnTransform.WorldMatrix.
void VRM.VRMLookAt.LateUpdate()
References VRM.VRMLookAt.LookWorldPosition, VRM.VRMLookAt.Target, VRM.VRMLookAt.UseUpdate.
void VRM.VRMLookAt.ApplyRotations(float yaw, float pitch)
References VRM.VRMLookAt.Head, VRM.VRMLookAt.LeftEye, VRM.OffsetOnTransform.OffsetRotation, VRM.VRMLookAt.RightEye, VRM.OffsetOnTransform.Transform.
Referenced by VRM.VRMLookAt.LookWorldPosition.
static void VRM.VRMLookAt.DrawMatrix(Matrix4x4 m, float size)
Referenced by VRM.VRMLookAt.OnDrawGizmos.
static Matrix4x4 VRM.VRMLookAt.LookAtMatrixFromWorld(Vector3 from, Vector3 target)
References VRM.VRMLookAt.LookAtMatrix, UniGLTF.UnityExtensions.Matrix4x4FromColumns, UnityEngine.Vector3.x, UnityEngine.Vector3.y, UnityEngine.Vector3.z.
static Matrix4x4 VRM.VRMLookAt.LookAtMatrix(Vector3 up_vector, Vector3 localPosition)
Referenced by VRM.VRMLookAt.LookAtMatrix, VRM.VRMLookAt.LookAtMatrixFromWorld.
static Matrix4x4 VRM.VRMLookAt.LookAtMatrix(Matrix4x4 m, Vector3 target)
References VRM.VRMLookAt.LookAtMatrix.