UniJSON::JsonNode
List<JsonValue> UniJSON.JsonNode.m_Values
Whole tree nodes
Referenced by UniJSON.JsonNode.AddValue, UniJSON.JsonNode.JsonNode, UniJSON.JsonNode.SetValue.
int UniJSON.JsonNode._valueIndex
This node index
Referenced by UniJSON.JsonNode.AddValue, UniJSON.JsonNode.JsonNode.
bool UniJSON.JsonNode.IsValid
int UniJSON.JsonNode.ValueIndex
Referenced by UniJSON.JsonNode.AddKey, UniJSON.JsonNode.AddValue, UniJSON.JsonNode.SetValue.
JsonNode UniJSON.JsonNode.Prev
JsonValue UniJSON.JsonNode.Value
Referenced by UniGLTF.gltf_mesh_extras_targetNames.Deserialize, UniGLTF.glTF_KHR_texture_basisu.Deserialize, UniGLTF.glTF_KHR_texture_transform.Deserialize, UniGLTF.glTF_KHR_texture_transform.DeserializeFloat2, UniJSON.JsonNode.Diff, UniJSON.JsonNode.Equals, UniJSON.JsonNode.IncrementChildCount, UniGLTF.glTFExtensionImport.ObjectItems, UniJSON.JsonNode.SetValueBytesCount.
int UniJSON.JsonNode.ChildCount
IEnumerable<JsonNode> UniJSON.JsonNode.Children
JsonNode UniJSON.JsonNode.this[String key]
JsonNode UniJSON.JsonNode.this[Utf8String key]
JsonNode UniJSON.JsonNode.this[int index]
bool UniJSON.JsonNode.HasParent
JsonNode UniJSON.JsonNode.Parent
override int UniJSON.JsonNode.GetHashCode()
override bool UniJSON.JsonNode.Equals(object obj)
References UniJSON.JsonNode.JsonNode, UniJSON.JsonNode.Value, UniJSON.JsonValue.ValueType.
Referenced by UniJSON.JsonNode.Diff.
override string UniJSON.JsonNode.ToString()
Referenced by UniJSON.JsonNode.ToString.
IEnumerable<string> UniJSON.JsonNode.ToString(string indent, int level, bool value=false)
string UniJSON.JsonNode.ToString(string indent)
References UniJSON.JsonNode.ToString.
IEnumerable<JsonDiff> UniJSON.JsonNode.Diff(JsonNode rhs, JsonPointer path=default(JsonPointer))
References UniJSON.JsonNode.Equals, UniJSON.JsonNode.Value, UniJSON.JsonValue.ValueType.
void UniJSON.JsonNode.SetValue(JsonValue value)
References UniJSON.JsonNode.m_Values, UniJSON.JsonNode.ValueIndex.
Referenced by UniJSON.JsonNode.IncrementChildCount, UniJSON.JsonNode.SetValueBytesCount.
UniJSON.JsonNode.JsonNode(List< JsonValue > values, int index=0)
References UniJSON.JsonNode._valueIndex, UniJSON.JsonNode.m_Values.
Referenced by UniJSON.JsonNode.AddValue, UniJSON.JsonNode.Equals.
JsonNode UniJSON.JsonNode.AddKey(Utf8String key)
References UniJSON.JsonNode.AddValue, UniJSON.JsonNode.ValueIndex.
JsonNode UniJSON.JsonNode.AddValue(ArraySegment< byte > bytes, ValueNodeType valueType)
References UniJSON.JsonNode.ValueIndex.
Referenced by UniJSON.JsonNode.AddKey.
JsonNode UniJSON.JsonNode.AddValue(JsonValue value)
References UniJSON.JsonNode._valueIndex, UniJSON.JsonNode.IncrementChildCount, UniJSON.JsonNode.JsonNode, UniJSON.JsonNode.m_Values.
void UniJSON.JsonNode.IncrementChildCount()
References UniJSON.JsonNode.SetValue, UniJSON.JsonNode.Value.
Referenced by UniJSON.JsonNode.AddValue.
void UniJSON.JsonNode.SetValueBytesCount(int count)
References UniJSON.JsonNode.SetValue, UniJSON.JsonNode.Value.