UniJSON::Utf8String
readonly System.Text.Encoding UniJSON.Utf8String.Encoding
Referenced by UniJSON.Utf8String4.Create, UniJSON.Utf8String.From.
readonly ArraySegment<Byte> UniJSON.Utf8String.Bytes
Referenced by UniJSON.Utf8String.GetIterator, UniJSON.Utf8String.IndexOf, UniJSON.Utf8String.operator+, UniJSON.Utf8StringExtensions.Split, UniJSON.Utf8String.Subbytes, UniJSON.Utf8StringExtensions.ToByte, UniJSON.Utf8StringExtensions.ToInt16, UniJSON.Utf8StringExtensions.ToInt32, UniJSON.Utf8StringExtensions.ToInt64, UniJSON.Utf8StringExtensions.ToSByte, UniJSON.Utf8StringExtensions.ToUInt16, UniJSON.Utf8StringExtensions.ToUInt32, UniJSON.Utf8StringExtensions.ToUInt64, UniJSON.Utf8StringExtensions.TrySearchAscii, UniJSON.Utf8String.Utf8String.
int UniJSON.Utf8String.ByteLength
Referenced by UniJSON.Utf8String.CompareTo, UniJSON.Utf8String.Concat, UniJSON.Utf8String.EndsWith, UniJSON.Utf8String.Equals, UniJSON.JsonString.Quote, UniJSON.Utf8String.StartsWith, UniJSON.Utf8String.Subbytes, UniJSON.Utf8String.ToAscii, UniJSON.Utf8String.ToString, UniJSON.Utf8String.TrimEnd, UniJSON.Utf8String.TrimStart, UniJSON.JsonString.Unquote.
Byte UniJSON.Utf8String.this[int i]
bool UniJSON.Utf8String.IsEmpty
Referenced by UniJSON.JsonString.Escape.
bool UniJSON.Utf8String.IsInt
Utf8Iterator UniJSON.Utf8String.GetIterator()
References UniJSON.Utf8String.Bytes.
int UniJSON.Utf8String.CompareTo(Utf8String other)
References UniJSON.Utf8String.ByteLength.
UniJSON.Utf8String.Utf8String(ArraySegment< Byte > bytes)
References UniJSON.Utf8String.Bytes.
Referenced by UniJSON.Utf8String.Concat, UniJSON.Utf8String.From, UniJSON.Utf8String.operator+, UniJSON.Utf8String.Subbytes.
UniJSON.Utf8String.Utf8String(Byte[] bytes, int offset, int count)
UniJSON.Utf8String.Utf8String(Byte[] bytes)
Utf8String UniJSON.Utf8String.Concat(Utf8String rhs)
References UniJSON.Utf8String.ByteLength, UniJSON.Utf8String.Utf8String.
override string UniJSON.Utf8String.ToString()
References UniJSON.Utf8String.ByteLength.
Referenced by UniJSON.JsonValue.GetBoolean.
string UniJSON.Utf8String.ToAscii()
References UniJSON.Utf8String.ByteLength.
bool UniJSON.Utf8String.StartsWith(Utf8String rhs)
References UniJSON.Utf8String.ByteLength.
bool UniJSON.Utf8String.EndsWith(Utf8String rhs)
References UniJSON.Utf8String.ByteLength.
int UniJSON.Utf8String.IndexOf(Byte code)
int UniJSON.Utf8String.IndexOf(int offset, Byte code)
References UniJSON.Utf8String.Bytes.
Utf8String UniJSON.Utf8String.Subbytes(int offset)
References UniJSON.Utf8String.ByteLength.
Referenced by UniJSON.Utf8String.TrimEnd, UniJSON.Utf8String.TrimStart, UniJSON.JsonString.Unquote.
Utf8String UniJSON.Utf8String.Subbytes(int offset, int count)
References UniJSON.Utf8String.Bytes, UniJSON.Utf8String.Utf8String.
Utf8String UniJSON.Utf8String.TrimStart()
References UniJSON.Utf8String.ByteLength, UniJSON.Utf8String.IsSpace, UniJSON.Utf8String.Subbytes.
Referenced by UniJSON.Utf8String.Trim.
Utf8String UniJSON.Utf8String.TrimEnd()
References UniJSON.Utf8String.ByteLength, UniJSON.Utf8String.IsSpace, UniJSON.Utf8String.Subbytes.
Utf8String UniJSON.Utf8String.Trim()
References UniJSON.Utf8String.TrimStart.
override bool UniJSON.Utf8String.Equals(Object obj)
bool UniJSON.Utf8String.Equals(Utf8String other)
References UniJSON.Utf8String.ByteLength.
override int UniJSON.Utf8String.GetHashCode()
static Utf8String UniJSON.Utf8String.From(string src)
References UniJSON.Utf8String.Encoding, UniJSON.Utf8String.Utf8String.
Referenced by UniJSON.JsonValueTests.InfinityTest, UniJSON.JsonValueTests.MinusInfinityTest, UniJSON.JsonValueTests.NaNTest, UniJSON.JsonParser.Parse, UniJSON.Utf8StringTests.SplitIntegerTest, UniJSON.JsonFormatter.Value.
static Utf8String UniJSON.Utf8String.From(string src, Byte[] bytes)
References UniJSON.Utf8Iterator.Head1, UniJSON.Utf8Iterator.Head2, UniJSON.Utf8Iterator.Head3, UniJSON.Utf8Iterator.Mask11, UniJSON.Utf8Iterator.Mask4, UniJSON.Utf8Iterator.Mask5, UniJSON.Utf8Iterator.Mask6, UniJSON.Utf8Iterator.Mask7, UniJSON.Utf8String.Utf8String.
static Utf8String UniJSON.Utf8String.From(int src)
References UniJSON.Utf8String.Utf8String.
static bool UniJSON.Utf8String.IsSpace(Byte b)
Referenced by UniJSON.Utf8String.TrimEnd, UniJSON.Utf8String.TrimStart.
static bool UniJSON.Utf8String.operator==(Utf8String x, Utf8String y)
static bool UniJSON.Utf8String.operator!=(Utf8String x, Utf8String y)
static Utf8String UniJSON.Utf8String.operator+(Utf8String l, Utf8String r)
References UniJSON.Utf8String.Bytes, UniJSON.Utf8String.Utf8String.