UniGLTF::UnityPath
string UniGLTF.UnityPath.Value
Referenced by UniGLTF.UnityPath.Child, UniGLTF.UnityPath.Equals, UniGLTF.UnityPath.FromFullpath, UniGLTF.UnityPath.FromUnityPath, UniGLTF.UnityPath.GetAssetFolder, UniGLTF.UnityPath.ToString, UniGLTF.UnityPath.UnityPath.
bool UniGLTF.UnityPath.IsNull
Referenced by UniGLTF.UnityPath.Child, UniGLTF.UnityPath.GetHashCode.
bool UniGLTF.UnityPath.IsUnderAssetsFolder
Referenced by UniGLTF.UnityPath.GetAssetFolder, VRM.VRMImporterMenu.ImportAsset, VRM.vrmAssetPostprocessor.ImportVrm.
bool UniGLTF.UnityPath.IsStreamingAsset
string UniGLTF.UnityPath.FileName
string UniGLTF.UnityPath.FileNameWithoutExtension
Referenced by UniGLTF.UnityPath.GetAssetFolder.
string UniGLTF.UnityPath.Extension
Referenced by VRM.BlendShapeClipEditor.SaveResizedImage.
UnityPath UniGLTF.UnityPath.Parent
Referenced by UniGLTF.UnityPath.GetAssetFolder.
bool UniGLTF.UnityPath.HasParent
string UniGLTF.UnityPath.BaseFullPath
Referenced by UniGLTF.UnityPath.FromFullpath.
string UniGLTF.UnityPath.AssetFullPath
Referenced by UniGLTF.UnityPath.IsUnderAssetFolder.
string UniGLTF.UnityPath.FullPath
Referenced by VRM.vrmAssetPostprocessor.ImportVrm.
bool UniGLTF.UnityPath.IsFileExists
Referenced by VRM.VRMEditorImporterContext.SaveAsAsset.
bool UniGLTF.UnityPath.IsDirectoryExists
Referenced by UniGLTF.UnityPath.TraverseDir.
IEnumerable<UnityPath> UniGLTF.UnityPath.ChildDirs
Referenced by UniGLTF.UnityPath.TraverseDir.
IEnumerable<UnityPath> UniGLTF.UnityPath.ChildFiles
readonly char [] UniGLTF.UnityPath.EscapeChars
Referenced by UniGLTF.UnityPath.EscapeFilePath.
string UniGLTF.UnityPath.s_basePath
override string UniGLTF.UnityPath.ToString()
References UniGLTF.UnityPath.Value.
UnityPath UniGLTF.UnityPath.Child(string name)
References UniGLTF.UnityPath.IsNull, UniGLTF.UnityPath.UnityPath, UniGLTF.UnityPath.Value.
override int UniGLTF.UnityPath.GetHashCode()
References UniGLTF.UnityPath.IsNull.
override bool UniGLTF.UnityPath.Equals(object obj)
References UniGLTF.UnityPath.UnityPath, UniGLTF.UnityPath.Value.
UnityPath UniGLTF.UnityPath.GetAssetFolder(string suffix)
Remove extension and add suffix
prefabPath suffix
References UniGLTF.UnityPath.FileNameWithoutExtension, UniGLTF.UnityPath.IsUnderAssetsFolder, UniGLTF.UnityPath.Parent, UniGLTF.UnityPath.UnityPath, UniGLTF.UnityPath.Value.
UniGLTF.UnityPath.UnityPath(string value)
References UniGLTF.UnityPath.Value.
Referenced by UniGLTF.UnityPath.Child, UniGLTF.UnityPath.Equals, UniGLTF.UnityPath.FromFullpath, UniGLTF.UnityPath.GetAssetFolder.
IEnumerable<UnityPath> UniGLTF.UnityPath.TravserseDir()
References UniGLTF.UnityPath.TraverseDir.
IEnumerable<UnityPath> UniGLTF.UnityPath.TraverseDir()
References UniGLTF.UnityPath.ChildDirs, UniGLTF.UnityPath.IsDirectoryExists.
Referenced by UniGLTF.UnityPath.TravserseDir.
static string UniGLTF.UnityPath.EscapeFilePath(string path)
References UniGLTF.UnityPath.EscapeChars.
static UnityPath UniGLTF.UnityPath.FromUnityPath(string unityPath)
unityPath Relative from unity current path. GetParent(Application.dataPath)
References UniGLTF.UnityPath.FromFullpath, UniGLTF.UnityPath.Value.
Referenced by VRM.vrmAssetPostprocessor.OnPostprocessAllAssets, UniGLTF.TextureTests.TextureExtractTest.
static UnityPath UniGLTF.UnityPath.FromFullpath(string fullPath)
fullPath C:/path/to/file
References UniGLTF.UnityPath.BaseFullPath, UniGLTF.UnityPath.UnityPath, UniGLTF.UnityPath.Value.
Referenced by UniGLTF.UnityPath.FromUnityPath, VRM.VRMImporterMenu.OpenImportMenu.
static bool UniGLTF.UnityPath.IsUnderAssetFolder(string fullPath)
References UniGLTF.UnityPath.AssetFullPath.