UniGLTF::GlbChunk
GlbChunkType UniGLTF.GlbChunk.ChunkType
Referenced by UniGLTF.GlbChunk.GetPaddingByte, UniGLTF.Glb.Glb, UniGLTF.GlbChunk.WriteTo.
string UniGLTF.GlbChunk.ChunkTypeString
Referenced by UniGLTF.GlbChunk.GlbChunk.
ArraySegment<Byte> UniGLTF.GlbChunk.Bytes
Referenced by UniGLTF.GlbChunk.GlbChunk, UniGLTF.GlbChunk.WriteTo.
UniGLTF.GlbChunk.GlbChunk(string json)
Referenced by UniGLTF.GlbChunk.CreateBin, UniGLTF.GlbChunk.CreateJson.
UniGLTF.GlbChunk.GlbChunk(ArraySegment< Byte > bytes)
UniGLTF.GlbChunk.GlbChunk(string chunkTypeString, ArraySegment< Byte > bytes)
References UniGLTF.GlbChunk.Bytes, UniGLTF.GlbChunk.ChunkTypeString.
byte UniGLTF.GlbChunk.GetPaddingByte()
References UniGLTF.GlbChunk.ChunkType.
Referenced by UniGLTF.GlbChunk.WriteTo.
int UniGLTF.GlbChunk.WriteTo(Stream s)
References UniGLTF.GlbChunk.Bytes, UniGLTF.GlbChunk.ChunkType, UniGLTF.GlbChunk.GetPaddingByte.
static GlbChunk UniGLTF.GlbChunk.CreateJson(string json)
Referenced by UniGLTF.Glb.Create.
static GlbChunk UniGLTF.GlbChunk.CreateJson(ArraySegment< byte > bytes)
References UniGLTF.GlbChunk.GlbChunk.
static GlbChunk UniGLTF.GlbChunk.CreateBin(ArraySegment< Byte > bytes)
References UniGLTF.GlbChunk.GlbChunk.