UniJSON::Utf8String4
uint UniJSON.Utf8String4._value
Referenced by UniJSON.Utf8String4.Create, UniJSON.Utf8String4.Equals.
byte UniJSON.Utf8String4._byte0
Referenced by UniJSON.Utf8String4.GetEnumerator.
byte UniJSON.Utf8String4._byte1
Referenced by UniJSON.Utf8String4.GetEnumerator.
byte UniJSON.Utf8String4._byte2
Referenced by UniJSON.Utf8String4.GetEnumerator.
byte UniJSON.Utf8String4._byte3
Referenced by UniJSON.Utf8String4.GetEnumerator.
int UniJSON.Utf8String4.ByteLength
static Utf8String4 UniJSON.Utf8String4.Create(uint value)
References UniJSON.Utf8String4._value.
Referenced by UniJSON.Utf8String4.Create.
static Utf8String4 UniJSON.Utf8String4.Create(IEnumerable< byte > bytes)
static Utf8String4 UniJSON.Utf8String4.Create(string src)
References UniJSON.Utf8String4.Create, UniJSON.Utf8String.Encoding.
bool UniJSON.Utf8String4.Equals(Utf8String4 other)
References UniJSON.Utf8String4._value.
Referenced by UniJSON.Utf8String4.Equals.
override bool UniJSON.Utf8String4.Equals(object obj)
References UniJSON.Utf8String4.Equals, UniJSON.Utf8String4.ToString.
override int UniJSON.Utf8String4.GetHashCode()
override string UniJSON.Utf8String4.ToString()
Referenced by UniJSON.Utf8String4.Equals.
IEnumerator<byte> UniJSON.Utf8String4.GetEnumerator()
References UniJSON.Utf8String4._byte0, UniJSON.Utf8String4._byte1, UniJSON.Utf8String4._byte2, UniJSON.Utf8String4._byte3.
Referenced by UniJSON.Utf8String4.GetEnumerator.
IEnumerator IEnumerable. UniJSON.Utf8String4.GetEnumerator()
References UniJSON.Utf8String4.GetEnumerator.