VRM::BlendShapeKey
readonly Dictionary<BlendShapePreset, string> VRM.BlendShapeKey.PresetNameCacheDictionary
Enum.ToString() のGC回避用キャッシュ
Referenced by VRM.BlendShapeKey.BlendShapeKey.
readonly string VRM.BlendShapeKey.UnknownPresetPrefix
BlendShapePresetと同名の名前を持つ独自に追加したBlendShapeを区別するためのprefix
Referenced by VRM.BlendShapeKey.BlendShapeKey, VRM.BlendShapeKey.ToString.
string VRM.BlendShapeKey.Name
Referenced by VRM.BlendShapeKey.BlendShapeKey.
readonly BlendShapePreset VRM.BlendShapeKey.Preset
Referenced by VRM.BlendShapeKey.BlendShapeKey, VRM.BlendShapeKey.CompareTo.
readonly string VRM.BlendShapeKey.m_id
Referenced by VRM.BlendShapeKey.BlendShapeKey, VRM.BlendShapeKey.Equals.
VRM.BlendShapeKey.BlendShapeKey(string name, BlendShapePreset preset)
name と preset のペアからBlendShapeKeyを生成するが、 BlendShapePreset.Unknown のときと、それ以外のときで挙動が異なることを知っている必要があって、わかりにくいので private に変更。 v0.56
代わりに、public static 関数を使って生成しますCreateFromPreset(BlendShapePreset) CreateFromClip(BlendShapeClip) CreateUnknown(string)TODO ? 旧仕様(GC発生などでパフォーマンスは、あまりよろしくない) CreateLegacyFromString(string); name preset
References VRM.BlendShapeKey.m_id, VRM.BlendShapeKey.Name, VRM.BlendShapeKey.Preset, VRM.BlendShapeKey.PresetNameCacheDictionary, VRM.BlendShapeKey.UnknownPresetPrefix.
Referenced by VRM.BlendShapeKey.CreateFromClip, VRM.BlendShapeKey.CreateFromPreset, VRM.BlendShapeKey.CreateUnknown.
static BlendShapeKey VRM.BlendShapeKey.CreateFromPreset(BlendShapePreset preset)
PresetからBlendShapeKeyを生成
preset
References VRM.BlendShapeKey.BlendShapeKey.
Referenced by VRM.BlendShapeAvatar.GetClip.
static BlendShapeKey VRM.BlendShapeKey.CreateFromClip(BlendShapeClip clip)
BlendShapeClipからBlendShapeKeyを生成
clip
References VRM.BlendShapeKey.BlendShapeKey, VRM.BlendShapeClip.BlendShapeName, VRM.BlendShapeClip.Preset.
Referenced by VRM.BlendShapeKey.Match, VRM.VRMBlendShapeProxyEditor.OnEnable.
static BlendShapeKey VRM.BlendShapeKey.CreateUnknown(string name)
BlendShapePreset.Unknown である BlendShapeKey を name から作成する
name
References VRM.BlendShapeKey.BlendShapeKey.
Referenced by VRM.BlendShapeAvatar.GetClip.
override string VRM.BlendShapeKey.ToString()
References VRM.BlendShapeKey.UnknownPresetPrefix.
bool VRM.BlendShapeKey.Equals(BlendShapeKey other)
References VRM.BlendShapeKey.m_id.
Referenced by VRM.BlendShapeKey.Equals.
override bool VRM.BlendShapeKey.Equals(object obj)
References VRM.BlendShapeKey.Equals.
override int VRM.BlendShapeKey.GetHashCode()
bool VRM.BlendShapeKey.Match(BlendShapeClip clip)
References VRM.BlendShapeKey.CreateFromClip.
int VRM.BlendShapeKey.CompareTo(BlendShapeKey other)
References VRM.BlendShapeKey.Preset.